import ConfidenceLegend from '../../assets/images/lcmap/legends/lcmap_confidence_legend.png';
import landChangeOverview from '../../assets/images/lcmap/thumbnails/landChangeOverview.png';
import landCoverOverview from '../../assets/images/lcmap/thumbnails/landCoverOverview.png';
import spectralChangeOverview from '../../assets/images/lcmap/thumbnails/spectralChangeOverview.png';

export const layers = {
  overlays: [
    {
      type: 'folder',
      title: 'LCMAP Datasets',
      description: '',
      expanded: true,
      folder: [
        // Conus
        {
          type: 'folder',
          title: 'Primary Land Cover (LCPRI)',
          description: `The most likely thematic, classified land cover for the current product year – assessed on July 1st of each year as a representative date.<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-collection-13-science-product-guide' target='_blank'>this link</a> to learn more.<br><br><a href="https://www.usgs.gov/media/videos/lcmap-collection-1-science-products-primary-secondary-land-cover" target="_blank"><img class="thumbnailOverview" src="${landCoverOverview}" /></a>`,
          expanded: false,
          regionId: 'conus',
          folder: [
            {
              type: 'layer',
              name: 'primaryLandcover_us_1-day-365-{{year}}_data',
              id: 'primaryLandcover',
              isWMST: true,
              wmstName: 'lcmap_primary-landcover_conus_year_data:primary-landcover_conus_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: true,
              active: true,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                PALETTE_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_primary_landcover_conus_raster',
              legend: {
                style: 'lcmap_primary_landcover_conus_raster_legend',
                customImageURL: null,
                title: 'Primary Land Cover (LCPRI)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'primary-landcover_conus_year_data',
                identifyToolValues: {
                  0: 'No Data',
                  1: 'Developed',
                  2: 'Cropland',
                  3: 'Grass/Shrub',
                  4: 'Tree Cover',
                  5: 'Water',
                  6: 'Wetlands',
                  7: 'Ice/Snow',
                  8: 'Barren',
                },
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.primary-landcover_conus_year_data.start.day',
                  month: '',
                  year: 'LCMAP.primary-landcover_conus_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.primary-landcover_conus_year_data.end.day',
                  month: '',
                  year: 'LCMAP.primary-landcover_conus_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Primary Land Cover Confidence (LCPCONF)',
          description: `Provides a measure of confidence in the Primary Land Cover label or additional information regarding the provenance of the result if that label was not produced by the initial classification method.<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-collection-13-science-product-guide' target='_blank'>this link</a> to learn more.<br><br><a href="https://www.usgs.gov/media/videos/lcmap-collection-1-science-products-primary-secondary-land-cover" target="_blank"><img class="thumbnailOverview" src="${landCoverOverview}" /></a>`,
          expanded: false,
          regionId: 'conus',
          folder: [
            {
              type: 'layer',
              name: 'primaryConfidence_us_1-day-365-{{year}}_data',
              id: 'primaryConfidence',
              isWMST: true,
              wmstName: 'lcmap_primary-confidence_conus_year_data:primary-confidence_conus_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_primary_confidence_conus_raster',
              legend: {
                style: '',
                customImageURL: ConfidenceLegend,
                title: 'Primary Land Cover Confidence (LCPCONF)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'primary-confidence_conus_year_data',
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.primary-confidence_conus_year_data.start.day',
                  month: '',
                  year: 'LCMAP.primary-confidence_conus_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.primary-confidence_conus_year_data.end.day',
                  month: '',
                  year: 'LCMAP.primary-confidence_conus_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Secondary Land Cover (LCSEC)',
          description: `The second most likely thematic, classified land cover for the current product year – assessed on July 1st of each year as a representative date.<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-collection-13-science-product-guide' target='_blank'>this link</a> to learn more.<br><br><a href="https://www.usgs.gov/media/videos/lcmap-collection-1-science-products-primary-secondary-land-cover" target="_blank"><img class="thumbnailOverview" src="${landCoverOverview}" /></a>`,
          expanded: false,
          regionId: 'conus',
          folder: [
            {
              type: 'layer',
              name: 'secondaryLandcover_us_1-day-365-{{year}}_data',
              id: 'secondaryLandcover',
              isWMST: true,
              wmstName: 'lcmap_secondary-landcover_conus_year_data:secondary-landcover_conus_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                PALETTE_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_secondary_landcover_conus_raster',
              legend: {
                style: 'lcmap_secondary_landcover_conus_raster_legend',
                customImageURL: null,
                title: 'Secondary Land Cover (LCSEC)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'secondary-landcover_conus_year_data',
                identifyToolValues: {
                  0: 'No Data',
                  1: 'Developed',
                  2: 'Cropland',
                  3: 'Grass/Shrub',
                  4: 'Tree Cover',
                  5: 'Water',
                  6: 'Wetlands',
                  7: 'Ice/Snow',
                  8: 'Barren',
                },
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.secondary-landcover_conus_year_data.start.day',
                  month: '',
                  year: 'LCMAP.secondary-landcover_conus_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.secondary-landcover_conus_year_data.end.day',
                  month: '',
                  year: 'LCMAP.secondary-landcover_conus_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Secondary Land Cover Confidence (LCSCONF)',
          description: `Provides a measure of confidence in the Secondary Land Cover label or additional information regarding the provenance of the result if that label was not produced by the initial classification method.<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-collection-13-science-product-guide' target='_blank'>this link</a> to learn more.<br><br><a href="https://www.usgs.gov/media/videos/lcmap-collection-1-science-products-primary-secondary-land-cover" target="_blank"><img class="thumbnailOverview" src="${landCoverOverview}" /></a>`,
          expanded: false,
          regionId: 'conus',
          folder: [
            {
              type: 'layer',
              name: 'secondaryConfidence_us_1-day-365-{{year}}_data',
              id: 'secondaryConfidence',
              isWMST: true,
              wmstName: 'lcmap_secondary-confidence_conus_year_data:secondary-confidence_conus_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_secondary_confidence_conus_raster',
              legend: {
                style: '',
                customImageURL: ConfidenceLegend,
                title: 'Secondary Land Cover Confidence (LCSCONF)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'secondary-confidence_conus_year_data',
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.secondary-confidence_conus_year_data.start.day',
                  month: '',
                  year: 'LCMAP.secondary-confidence_conus_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.secondary-confidence_conus_year_data.end.day',
                  month: '',
                  year: 'LCMAP.secondary-confidence_conus_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Annual Land Cover Change (LCACHG)',
          description: `Synthesis of Primary Land Cover of current and previous year identifying changes in land cover class.<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-collection-13-science-product-guide' target='_blank'>this link</a> to learn more.<br><br><a href="https://www.usgs.gov/media/videos/lcmap-collection-1-science-products-annual-land-cover-change" target="_blank"><img class="thumbnailOverview" src="${landChangeOverview}" /></a>`,
          expanded: false,
          regionId: 'conus',
          folder: [
            {
              type: 'layer',
              name: 'coverChange_us_1-day-365-{{year}}_data',
              id: 'coverChange',
              isWMST: true,
              wmstName: 'lcmap_cover-change_conus_year_data:cover-change_conus_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                PALETTE_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_cover_change_conus_raster',
              legend: {
                style: 'lcmap_cover_change_conus_raster_legend',
                customImageURL: null,
                title: 'Annual Land Cover Change (LCACHG)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'cover-change_conus_year_data',
                identifyToolValues: {
                  0: 'No Data',
                  1: 'Developed',
                  2: 'Cropland',
                  3: 'Grass/Shrub',
                  4: 'Tree Cover',
                  5: 'Water',
                  6: 'Wetlands',
                  7: 'Ice/Snow',
                  8: 'Barren',
                },
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.cover-change_conus_year_data.start.day',
                  month: '',
                  year: 'LCMAP.cover-change_conus_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.cover-change_conus_year_data.end.day',
                  month: '',
                  year: 'LCMAP.cover-change_conus_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Time of Spectral Change (SCTIME)',
          description: `Represents the timing of a spectral change within the current product year as day-of-year (DOY).<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-collection-13-science-product-guide' target='_blank'>this link</a> to learn more.<br><br><a href="https://www.usgs.gov/media/videos/lcmap-time-spectral-change-spectral-change-magnitude" target="_blank"><img class="thumbnailOverview" src="${spectralChangeOverview}" /></a>`,
          expanded: false,
          regionId: 'conus',
          folder: [
            {
              type: 'layer',
              name: 'changeDay_us_1-day-365-{{year}}_data',
              id: 'changeDay',
              isWMST: true,
              wmstName: 'lcmap_change-day_conus_year_data:change-day_conus_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_change_day_conus_raster',
              legend: {
                style: 'lcmap_change_day_conus_raster_legend',
                customImageURL: null,
                title: 'Time of Spectral Change (SCTIME)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'change-day_conus_year_data',
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.change-day_conus_year_data.start.day',
                  month: '',
                  year: 'LCMAP.change-day_conus_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.change-day_conus_year_data.end.day',
                  month: '',
                  year: 'LCMAP.change-day_conus_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Change Magnitude (SCMAG)',
          description: `Represents the timing of a spectral change within the current product year as day-of-year (DOY).<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-collection-13-science-product-guide' target='_blank'>this link</a> to learn more.<br><br><a href="https://www.usgs.gov/media/videos/lcmap-time-spectral-change-spectral-change-magnitude" target="_blank"><img class="thumbnailOverview" src="${spectralChangeOverview}" /></a>`,
          expanded: false,
          regionId: 'conus',
          folder: [
            {
              type: 'layer',
              name: 'changeMag_us_1-day-365-{{year}}_data',
              id: 'changeMagnitude',
              isWMST: true,
              wmstName: 'lcmap_change-magnitude_conus_year_data:change-magnitude_conus_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_spectral_magnitude_conus_raster',
              legend: {
                style: 'lcmap_spectral_magnitude_conus_raster_legend',
                customImageURL: null,
                title: 'Change Magnitude (SCMAG)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'change-magnitude_conus_year_data',
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.change-magnitude_conus_year_data.start.year',
                  month: '',
                  year: 'LCMAP.change-magnitude_conus_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.change-magnitude_conus_year_data.end.year',
                  month: '',
                  year: 'LCMAP.change-magnitude_conus_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Spectral Stability Period (SCSTAB)',
          description:
            "Time, in days, that the spectral time series has been in its current state.<br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-collection-13-science-product-guide' target='_blank'>this link</a> to learn more.<br><br>",
          expanded: false,
          regionId: 'conus',
          folder: [
            {
              type: 'layer',
              name: 'spectralStability_us_1-day-365-{{year}}_data',
              id: 'spectralStability',
              isWMST: true,
              wmstName: 'lcmap_spectral-stability_conus_year_data:spectral-stability_conus_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_spectral_stability_conus_raster',
              legend: {
                style: 'lcmap_spectral_stability_conus_raster_legend',
                customImageURL: null,
                title: 'Spectral Stability Period (SCSTAB)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'spectral-stability_conus_year_data',
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.spectral-stability_conus_year_data.start.year',
                  month: '',
                  year: 'LCMAP.spectral-stability_conus_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.spectral-stability_conus_year_data.end.year',
                  month: '',
                  year: 'LCMAP.spectral-stability_conus_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Time Since Last Change (SCLAST)',
          description:
            "Time, in days, since the last identified Spectral Change (SCTIME).<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-collection-13-science-product-guide' target='_blank'>this link</a> to learn more.<br><br>",
          expanded: false,
          regionId: 'conus',
          folder: [
            {
              type: 'layer',
              name: 'spectralLastChange_us_1-day-365-{{year}}_data',
              id: 'spectralLastChange',
              isWMST: true,
              wmstName: 'lcmap_spectral-lastchange_conus_year_data:spectral-lastchange_conus_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_spectral_lastchange_conus_raster',
              legend: {
                style: 'lcmap_spectral_lastchange_conus_raster_legend',
                customImageURL: null,
                title: 'Time Since Last Change (SCLAST)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'spectral-lastchange_conus_year_data',
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.spectral-lastchange_conus_year_data.start.year',
                  month: '',
                  year: 'LCMAP.spectral-lastchange_conus_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.spectral-lastchange_conus_year_data.end.year',
                  month: '',
                  year: 'LCMAP.spectral-lastchange_conus_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Spectral Model Quality (SCMQA)',
          description:
            "Information regarding the type of time series model applied to the current year.<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-collection-13-science-product-guide' target='_blank'>this link</a> to learn more.<br><br>",
          expanded: false,
          regionId: 'conus',
          folder: [
            {
              type: 'layer',
              name: 'modelQuality_us_1-day-365-{{year}}_data',
              id: 'modelQuality',
              isWMST: true,
              wmstName: 'lcmap_model-quality_conus_year_data:model-quality_conus_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_spectral_model_quality_conus_raster',
              legend: {
                style: 'lcmap_spectral_model_quality_conus_raster_legend',
                customImageURL: null,
                title: 'Spectral Model Quality (SCMQA)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'model-quality_conus_year_data',
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.model-quality_conus_year_data.start.day',
                  month: '',
                  year: 'LCMAP.model-quality_conus_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.model-quality_conus_year_data.end.day',
                  month: '',
                  year: 'LCMAP.model-quality_conus_year_data.end.year',
                },
              },
            },
          ],
        },
        // Hawaii
        {
          type: 'folder',
          title: 'Primary Land Cover (LCPRI)',
          description: `The most likely thematic, classified land cover for the current product year – assessed on July 1st of each year as a representative date.<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-hawaii-collection-1-science-product-guide' target='_blank'>this link</a> to learn more.<br><br><a href="https://www.usgs.gov/media/videos/lcmap-collection-1-science-products-primary-secondary-land-cover" target="_blank"><img class="thumbnailOverview" src="${landCoverOverview}" /></a>`,
          expanded: false,
          regionId: 'hawaii',
          folder: [
            {
              type: 'layer',
              name: 'primaryLandcover_hawaii_1-day-365-{{year}}_data',
              id: 'hawaiiPrimaryLandcover',
              isWMST: true,
              wmstName: 'lcmap_primary-landcover_hawaii_year_data:primary-landcover_hawaii_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: true,
              active: true,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                PALETTE_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_primary_landcover_conus_raster',
              legend: {
                style: 'lcmap_primary_landcover_conus_raster_legend',
                customImageURL: null,
                title: 'Primary Land Cover (LCPRI)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'primary-landcover_hawaii_year_data',
                identifyToolValues: {
                  0: 'No Data',
                  1: 'Developed',
                  2: 'Cropland',
                  3: 'Grass/Shrub',
                  4: 'Tree Cover',
                  5: 'Water',
                  6: 'Wetlands',
                  7: 'Ice/Snow',
                  8: 'Barren',
                },
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.primary-landcover_hawaii_year_data.start.day',
                  month: '',
                  year: 'LCMAP.primary-landcover_hawaii_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.primary-landcover_hawaii_year_data.end.day',
                  month: '',
                  year: 'LCMAP.primary-landcover_hawaii_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Primary Land Cover Confidence (LCPCONF)',
          description: `Provides a measure of confidence in the Primary Land Cover label or additional information regarding the provenance of the result if that label was not produced by the initial classification method.<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-hawaii-collection-1-science-product-guide' target='_blank'>this link</a> to learn more.<br><br><a href="https://www.usgs.gov/media/videos/lcmap-collection-1-science-products-primary-secondary-land-cover" target="_blank"><img class="thumbnailOverview" src="${landCoverOverview}" /></a>`,
          expanded: false,
          regionId: 'hawaii',
          folder: [
            {
              type: 'layer',
              name: 'primaryConfidence_hawaii_1-day-365-{{year}}_data',
              id: 'hawaiiPrimaryConfidence',
              isWMST: true,
              wmstName: 'lcmap_primary-confidence_hawaii_year_data:primary-confidence_hawaii_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_primary_confidence_conus_raster',
              legend: {
                style: '',
                customImageURL: ConfidenceLegend,
                title: 'Primary Land Cover Confidence (LCPCONF)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'primary-confidence_hawaii_year_data',
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.primary-confidence_hawaii_year_data.start.day',
                  month: '',
                  year: 'LCMAP.primary-confidence_hawaii_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.primary-confidence_hawaii_year_data.end.day',
                  month: '',
                  year: 'LCMAP.primary-confidence_hawaii_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Secondary Land Cover (LCSEC)',
          description: `The second most likely thematic, classified land cover for the current product year – assessed on July 1st of each year as a representative date.<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-hawaii-collection-1-science-product-guide' target='_blank'>this link</a> to learn more.<br><br><a href="https://www.usgs.gov/media/videos/lcmap-collection-1-science-products-primary-secondary-land-cover" target="_blank"><img class="thumbnailOverview" src="${landCoverOverview}" /></a>`,
          expanded: false,
          regionId: 'hawaii',
          folder: [
            {
              type: 'layer',
              name: 'secondaryLandcover_hawaii_1-day-365-{{year}}_data',
              id: 'hawaiiSecondaryLandcover',
              isWMST: true,
              wmstName: 'lcmap_secondary-landcover_hawaii_year_data:secondary-landcover_hawaii_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                PALETTE_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_secondary_landcover_conus_raster',
              legend: {
                style: 'lcmap_secondary_landcover_conus_raster_legend',
                customImageURL: null,
                title: 'Secondary Land Cover (LCSEC)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'secondary-landcover_hawaii_year_data',
                identifyToolValues: {
                  0: 'No Data',
                  1: 'Developed',
                  2: 'Cropland',
                  3: 'Grass/Shrub',
                  4: 'Tree Cover',
                  5: 'Water',
                  6: 'Wetlands',
                  7: 'Ice/Snow',
                  8: 'Barren',
                },
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.secondary-landcover_hawaii_year_data.start.day',
                  month: '',
                  year: 'LCMAP.secondary-landcover_hawaii_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.secondary-landcover_hawaii_year_data.end.day',
                  month: '',
                  year: 'LCMAP.secondary-landcover_hawaii_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Secondary Land Cover Confidence (LCSCONF)',
          description: `Provides a measure of confidence in the Secondary Land Cover label or additional information regarding the provenance of the result if that label was not produced by the initial classification method.<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-hawaii-collection-1-science-product-guide' target='_blank'>this link</a> to learn more.<br><br><a href="https://www.usgs.gov/media/videos/lcmap-collection-1-science-products-primary-secondary-land-cover" target="_blank"><img class="thumbnailOverview" src="${landCoverOverview}" /></a>`,
          expanded: false,
          regionId: 'hawaii',
          folder: [
            {
              type: 'layer',
              name: 'secondaryConfidence_hawaii_1-day-365-{{year}}_data',
              id: 'hawaiiSecondaryConfidence',
              isWMST: true,
              wmstName: 'lcmap_secondary-confidence_hawaii_year_data:secondary-confidence_hawaii_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_secondary_confidence_conus_raster',
              legend: {
                style: '',
                customImageURL: ConfidenceLegend,
                title: 'Secondary Land Cover Confidence (LCSCONF)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'secondary-confidence_hawaii_year_data',
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.secondary-confidence_hawaii_year_data.start.day',
                  month: '',
                  year: 'LCMAP.secondary-confidence_hawaii_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.secondary-confidence_hawaii_year_data.end.day',
                  month: '',
                  year: 'LCMAP.secondary-confidence_hawaii_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Annual Land Cover Change (LCACHG)',
          description: `Synthesis of Primary Land Cover of current and previous year identifying changes in land cover class.<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-hawaii-collection-1-science-product-guide' target='_blank'>this link</a> to learn more.<br><br><a href="https://www.usgs.gov/media/videos/lcmap-collection-1-science-products-annual-land-cover-change" target="_blank"><img class="thumbnailOverview" src="${landChangeOverview}" /></a>`,
          expanded: false,
          regionId: 'hawaii',
          folder: [
            {
              type: 'layer',
              name: 'coverChange_hawaii_1-day-365-{{year}}_data',
              id: 'hawaiicoverChange',
              isWMST: true,
              wmstName: 'lcmap_cover-change_hawaii_year_data:cover-change_hawaii_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                PALETTE_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_cover_change_conus_raster',
              legend: {
                style: 'lcmap_cover_change_conus_raster_legend',
                customImageURL: null,
                title: 'Annual Land Cover Change (LCACHG)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'cover-change_hawaii_year_data',
                identifyToolValues: {
                  0: 'No Data',
                  1: 'Developed',
                  2: 'Cropland',
                  3: 'Grass/Shrub',
                  4: 'Tree Cover',
                  5: 'Water',
                  6: 'Wetlands',
                  7: 'Ice/Snow',
                  8: 'Barren',
                },
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.cover-change_hawaii_year_data.start.day',
                  month: '',
                  year: 'LCMAP.cover-change_hawaii_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.cover-change_hawaii_year_data.end.day',
                  month: '',
                  year: 'LCMAP.cover-change_hawaii_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Time of Spectral Change (SCTIME)',
          description: `Represents the timing of a spectral change within the current product year as day-of-year (DOY).<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-hawaii-collection-1-science-product-guide' target='_blank'>this link</a> to learn more.<br><br><a href="https://www.usgs.gov/media/videos/lcmap-time-spectral-change-spectral-change-magnitude" target="_blank"><img class="thumbnailOverview" src="${spectralChangeOverview}" /></a>`,
          expanded: false,
          regionId: 'hawaii',
          folder: [
            {
              type: 'layer',
              name: 'changeDay_hawaii_1-day-365-{{year}}_data',
              id: 'hawaiiChangeDay',
              isWMST: true,
              wmstName: 'lcmap_change-day_hawaii_year_data:change-day_hawaii_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_change_day_conus_raster',
              legend: {
                style: 'lcmap_change_day_conus_raster_legend',
                customImageURL: null,
                title: 'Time of Spectral Change (SCTIME)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'change-day_hawaii_year_data',
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.change-day_hawaii_year_data.start.day',
                  month: '',
                  year: 'LCMAP.change-day_hawaii_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.change-day_hawaii_year_data.end.day',
                  month: '',
                  year: 'LCMAP.change-day_hawaii_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Change Magnitude (SCMAG)',
          description: `Represents the timing of a spectral change within the current product year as day-of-year (DOY).<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-hawaii-collection-1-science-product-guide' target='_blank'>this link</a> to learn more.<br><br><a href="https://www.usgs.gov/media/videos/lcmap-time-spectral-change-spectral-change-magnitude" target="_blank"><img class="thumbnailOverview" src="${spectralChangeOverview}" /></a>`,
          expanded: false,
          regionId: 'hawaii',
          folder: [
            {
              type: 'layer',
              name: 'changeMag_hawaii_1-day-365-{{year}}_data',
              id: 'hawaiiChangeMagnitude',
              isWMST: true,
              wmstName: 'lcmap_change-magnitude_hawaii_year_data:change-magnitude_hawaii_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_spectral_magnitude_conus_raster',
              legend: {
                style: 'lcmap_spectral_magnitude_conus_raster_legend',
                customImageURL: null,
                title: 'Change Magnitude (SCMAG)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'change-magnitude_hawaii_year_data',
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.change-magnitude_hawaii_year_data.start.year',
                  month: '',
                  year: 'LCMAP.change-magnitude_hawaii_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.change-magnitude_hawaii_year_data.end.year',
                  month: '',
                  year: 'LCMAP.change-magnitude_hawaii_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Spectral Stability Period (SCSTAB)',
          description:
            "Time, in days, that the spectral time series has been in its current state.<br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-hawaii-collection-1-science-product-guide' target='_blank'>this link</a> to learn more.<br><br>",
          expanded: false,
          regionId: 'hawaii',
          folder: [
            {
              type: 'layer',
              name: 'spectralStability_hawaii_1-day-365-{{year}}_data',
              id: 'hawaiiSpectralStability',
              isWMST: true,
              wmstName: 'lcmap_spectral-stability_hawaii_year_data:spectral-stability_hawaii_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_spectral_stability_conus_raster',
              legend: {
                style: 'lcmap_spectral_stability_conus_raster_legend',
                customImageURL: null,
                title: 'Spectral Stability Period (SCSTAB)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'spectral-stability_hawaii_year_data',
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.spectral-stability_hawaii_year_data.start.year',
                  month: '',
                  year: 'LCMAP.spectral-stability_hawaii_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.spectral-stability_hawaii_year_data.end.year',
                  month: '',
                  year: 'LCMAP.spectral-stability_hawaii_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Time Since Last Change (SCLAST)',
          description:
            "Time, in days, since the last identified Spectral Change (SCTIME).<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-hawaii-collection-1-science-product-guide' target='_blank'>this link</a> to learn more.<br><br>",
          expanded: false,
          regionId: 'hawaii',
          folder: [
            {
              type: 'layer',
              name: 'spectralLastChange_hawaii_1-day-365-{{year}}_data',
              id: 'hawaiiSpectralLastChange',
              isWMST: true,
              wmstName: 'lcmap_spectral-lastchange_hawaii_year_data:spectral-lastchange_hawaii_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_spectral_lastchange_conus_raster',
              legend: {
                style: 'lcmap_spectral_lastchange_conus_raster_legend',
                customImageURL: null,
                title: 'Time Since Last Change (SCLAST)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'spectral-lastchange_hawaii_year_data',
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.spectral-lastchange_hawaii_year_data.start.year',
                  month: '',
                  year: 'LCMAP.spectral-lastchange_hawaii_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.spectral-lastchange_hawaii_year_data.end.year',
                  month: '',
                  year: 'LCMAP.spectral-lastchange_hawaii_year_data.end.year',
                },
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Spectral Model Quality (SCMQA)',
          description:
            "Information regarding the type of time series model applied to the current year.<br><br>For instruction please visit <a href='https://www.usgs.gov/media/files/lcmap-hawaii-collection-1-science-product-guide' target='_blank'>this link</a> to learn more.<br><br>",
          expanded: false,
          regionId: 'hawaii',
          folder: [
            {
              type: 'layer',
              name: 'modelQuality_hawaii_1-day-365-{{year}}_data',
              id: 'hawaiiModelQuality',
              isWMST: true,
              wmstName: 'lcmap_model-quality_hawaii_year_data:model-quality_hawaii_year_data',
              currentGranuleName: '',
              title: '',
              description: '',
              source: {
                wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
                wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
                gwc: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 1,
              transparency: true,
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'lcmap_spectral_model_quality_conus_raster',
              legend: {
                style: 'lcmap_spectral_model_quality_conus_raster_legend',
                customImageURL: null,
                title: 'Spectral Model Quality (SCMQA)',
              },
              additionalAttributes: {
                format: 'yyyy',
                statistic: 'data',
                rasterDataset: 'model-quality_hawaii_year_data',
              },
              timeseries: {
                type: 'year',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
                start: {
                  period: 'LCMAP.model-quality_hawaii_year_data.start.day',
                  month: '',
                  year: 'LCMAP.model-quality_hawaii_year_data.start.year',
                },
                end: {
                  period: 'LCMAP.model-quality_hawaii_year_data.end.day',
                  month: '',
                  year: 'LCMAP.model-quality_hawaii_year_data.end.year',
                },
              },
            },
          ],
        },
      ],
    },
    {
      type: 'folder',
      title: 'Download Layers',
      expanded: false,
      regionId: 'conus',
      folder: [
        {
          type: 'layer',
          name: 'lcmap_Viewer_Layers_Extent:Viewer_Layers_Extent',
          description: 'Shapefile layer for cDataDownload',
          source: {
            wfs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wfs?',
          },
          loadOnly: true,
          display: false,
          mask: false,
          transparency: false,
          zIndex: 1,
          srs: 'EPSG:3857',
        },
      ],
    },
    {
      type: 'folder',
      title: 'Download Layers',
      expanded: false,
      regionId: 'hawaii',
      folder: [
        {
          type: 'layer',
          name: 'lcmap_Viewer_Layers_Extent:Viewer_Layers_Extent',
          description: 'Shapefile layer for cDataDownload',
          source: {
            wfs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wfs?',
          },
          loadOnly: true,
          display: false,
          mask: false,
          transparency: false,
          zIndex: 1,
          srs: 'EPSG:3857',
        },
      ],
    },
  ],
  boundaries: [
    {
      type: 'folder',
      title: 'Reference Data',
      regionId: 'conus',
      expanded: true,
      folder: [
        {
          type: 'layer',
          name: 'lcmap_land_change_stories:land_change_stories',
          title: `<b style='color: red;'>New!</b> Land Change Stories`,
          description: '',
          source: {
            wms: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wms?',
            wcs: 'https://igskmncnlxvs226.cr.usgs.gov:8443/geoserver/wcs',
          },
          loadOnly: false,
          display: true,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          ignoreFolderTitle: true,
          isPrimaryFeature: true,
          featureInfo: {
            Title: {
              displayName: 'TITLE',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            URL: {
              displayName: '',
              displayValue: null,
              value: null,
              mapValues: [],
            },
          },
          style: 'lcmap_land_change_stories',
        },
        {
          type: 'layer',
          name: 'lcmap_lcmap_uscounties:lcmap_uscounties',
          title: 'U.S. County Boundaries',
          description: '',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
          },
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          featureInfo: {
            COUNTY_NAM: {
              displayName: 'COUNTY',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            COUNTY_FIP: {
              displayName: 'COUNTY FIPS',
              displayValue: null,
              value: null,
              mapValues: [],
            },
          },
          style: 'lcmap_uscounties',
        },
        {
          type: 'layer',
          name: 'lcmap_usstates:usstates',
          title: 'U.S. State Boundaries',
          description: '',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
          },
          loadOnly: false,
          display: true,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          featureInfo: {
            STATE_NAME: {
              displayName: 'STATE',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            STATE_FIPS: {
              displayName: 'STATE FIPS',
              displayValue: null,
              value: null,
              mapValues: [],
            },
          },
          style: 'lcmap_usstates',
        },
      ],
    },
    {
      type: 'folder',
      title: 'Reference Data',
      regionId: 'hawaii',
      expanded: true,
      folder: [
        // {
        //   type: 'layer',
        //   name: 'lcmap_land_change_stories:land_change_stories',
        //   title: `<b style='color: red;'>New!</b> Land Change Stories`,
        //   description: '',
        //   source: {
        //     wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
        //     wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs',
        //   },
        //   loadOnly: false,
        //   display: true,
        //   mask: false,
        //   zIndex: 0,
        //   regionIds: ['us'],
        //   srs: 'EPSG:3857',
        //   ignoreFolderTitle: true,
        //   isPrimaryFeature: true,
        //   featureInfo: {
        //     Title: {
        //       displayName: 'TITLE',
        //       displayValue: null,
        //       value: null,
        //       mapValues: [],
        //     },
        //     URL: {
        //       displayName: '',
        //       displayValue: null,
        //       value: null,
        //       mapValues: [],
        //     },
        //   },
        //   style: 'lcmap_land_change_stories',
        // },
        {
          type: 'layer',
          name: 'lcmap_lcmap_uscounties:lcmap_uscounties',
          title: 'U.S. County Boundaries',
          description: '',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
          },
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          featureInfo: {
            COUNTY_NAM: {
              displayName: 'COUNTY',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            COUNTY_FIP: {
              displayName: 'COUNTY FIPS',
              displayValue: null,
              value: null,
              mapValues: [],
            },
          },
          style: 'lcmap_uscounties',
        },
        {
          type: 'layer',
          name: 'lcmap_usstates:usstates',
          title: 'U.S. State Boundaries',
          description: '',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
          },
          loadOnly: false,
          display: true,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          featureInfo: {
            STATE_NAME: {
              displayName: 'STATE',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            STATE_FIPS: {
              displayName: 'STATE FIPS',
              displayValue: null,
              value: null,
              mapValues: [],
            },
          },
          style: 'lcmap_usstates',
        },
      ],
    },
  ],
  baselayers: [
    {
      type: 'folder',
      title: 'Base Layers',
      expanded: true,
      folder: [
        {
          type: 'layer',
          name: 'osm_0',
          title: 'Standard OpenStreetMap',
          description: '',
          loadOnly: false,
          display: true,
          mask: false,
          srs: 'EPSG:3857',
          loaded: 'true',
          brand: 'osm',
          source: {
            url: 'https://osm-{1-4}.gs.mil/tiles/default/{z}/{x}/{y}.png',
          },
          comments: '',
        },
        {
          type: 'layer',
          name: 'base_map:national_map_aerial_photography',
          title: 'Aerial Photography',
          description: '',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
          },
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          featureInfo: {},
          style: '',
        },
      ],
    },
  ],
};
