import quickdriCustomLegend from '../../assets/images/quickdri/quickdri_custom_legend.png';
import quickdriCustomDroughtLegend from '../../assets/images/quickdriImages/customDroughtLegend.png';
import quickdriCustomWaterWatchLegend from '../../assets/images/quickdriImages/customWaterWatchLegend.png';

export const layers = {
  overlays: [
    {
      type: 'folder',
      title: 'Dataset',
      expanded: true,
      folder: [
        {
          type: 'folder',
          title: 'VegDRI 7-Day eMODIS',
          description:
            'VegDRI refers to the Vegetation Drought Response Index. This geospatial data set shows seasonal drought impacts on vegetation. The weekly index is produced using a model trained on the self-calibrated Palmer Drought Severity Index using MODIS satellite-derived greenness anomaly integrated with precipitation, land cover, soils, and other biophysical data sets. Updated every Monday by 10 AM. For more information: https://vegdri.cr.usgs.gov/',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'qdvdemodis_id',
              name: 'qdvdemodis:qdvdemodis_qdhydrounits_1-sevenday-{{period}}-{{year}}_mm_data',
              isWMST: true,
              wmstName: 'quickdri_vegdri_conus_week_data:vegdri_conus_week_data',
              currentGranuleName: '',
              title: '',
              description:
                'VegDRI refers to the Vegetation Drought Response Index. This geospatial data set shows seasonal drought impacts on vegetation. The weekly index is produced using a model trained on the self-calibrated Palmer Drought Severity Index using MODIS satellite-derived greenness anomaly integrated with precipitation, land cover, soils, and other biophysical data sets. Updated every Monday by 10 AM. For more information: https://vegdri.cr.usgs.gov/',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
              },
              layerExtent: [-14307900.7315574940294027, 2568894.1629371135495603, -7279453.8376226529716253, 6758880.6791341546922922],
              resolution: '1277',
              pixelHeight: 3280,
              pixelWidth: 5502,
              loadOnly: false,
              display: true,
              active: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: ['something'],
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:4326',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'qdri_vegdri_raster',
              legend: {
                style: 'qdri_vegdri_raster_display',
                customImageURL: null,
                title: 'VegDRI 7-Day eMODIS',
                panelTitle: 'VegDRI 7-Day eMODIS',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'vegdri_conus_week_data',
              },
              timeseries: {
                type: 'week',
                format: 'f1',
                source: 'https://edcintl.cr.usgs.gov/geoengine5/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'QuickDRI 7-Day eMODIS',
          description:
            'QuickDRI refers to the Quick Drought Response Index. QuickDRI represents a drought “alarm” indicator of emerging or short-term changing drought conditions. The index is produced using a model trained on the Standardized Precipitation Evaporation Index. Input data include MODIS satellite-derived greenness anomaly, monthly precipitation anomaly, modeled soil moisture, land cover, soils, and other biophysical data. Updated every Monday by 10 AM. For more information: https://vegdri.cr.usgs.gov/',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'qdraster_id',
              name: 'qdraster_qdhydrounits_1-sevenday-{{period}}-{{year}}_mm_data',
              isWMST: true,
              wmstName: 'quickdri_quickdri_conus_week_data:quickdri_conus_week_data',
              title: '',
              description:
                'QuickDRI refers to the Quick Drought Response Index. QuickDRI represents a drought “alarm” indicator of emerging or short-term changing drought conditions. The index is produced using a model trained on the Standardized Precipitation Evaporation Index. Input data include MODIS satellite-derived greenness anomaly, monthly precipitation anomaly, modeled soil moisture, land cover, soils, and other biophysical data. Updated every Monday by 10 AM. For more information: https://vegdri.cr.usgs.gov/',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
              },
              resolution: '1277',
              pixelHeight: 3280,
              pixelWidth: 5502,
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: ['something'],
              srs: 'EPSG:3857',
              wcsOutputSRS: 'EPSG:4326',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'qdri_quickdri_raster',
              legend: {
                style: '',
                customImageURL: quickdriCustomLegend,
                title: 'QuickDRI 7-Day eMODIS',
                panelTitle: 'QuickDRI 7-Day eMODIS',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'quickdri_conus_week_data',
              },
              timeseries: {
                type: 'week',
                format: 'f1',
                source: 'https://edcintl.cr.usgs.gov/geoengine5/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Drought Monitor Current',
          description:
            'The U.S. Drought Monitor (USDM) is a map released every Thursday, showing parts of the U.S. that are in drought. The map uses five classes: abnormally dry (D0), showing areas that may be going into or are coming out of drought, and four levels of drought: moderate (D1), severe (D2), extreme (D3) and exceptional (D4). Updated every Thursday at 8:30 AM. For more information: https://droughtmonitor.unl.edu/',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              name: 'quickdri_drought:usdm_current',
              title: '',
              description:
                'The U.S. Drought Monitor (USDM) is a map released every Thursday, showing parts of the U.S. that are in drought. The map uses five classes: abnormally dry (D0), showing areas that may be going into or are coming out of drought, and four levels of drought: moderate (D1), severe (D2), extreme (D3) and exceptional (D4). Updated every Thursday at 8:30 AM. For more information: https://droughtmonitor.unl.edu/',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
              },
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:3857',
              style: '',
              legend: {
                style: '',
                customImageURL: quickdriCustomDroughtLegend,
                title: 'Drought Index',
                panelTitle: 'Drought Index',
              },
              unit: '',
            },
          ],
        },
        {
          type: 'folder',
          title: '30 Day Total Precipitation',
          description:
            'A precipitation derivative map showing total rainfall in the last 30 days. Updated daily at 7:00 PM. For more information: https://earlywarning.usgs.gov/usraindry/',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              isWMST: true,
              name: 'qdpreciptp30:qdpreciptp30_qdhydrounits_1-day-{{period}}-{{year}}_mm_data',
              wmstName: 'quickdri_precip-tp-30_conus_day_data:precip-tp-30_conus_day_data',
              title: '',
              description:
                'A precipitation derivative map showing total rainfall in the last 30 days. Updated daily at 7:00 PM. For more information: https://earlywarning.usgs.gov/usraindry/',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
              },
              resolution: '0.05',
              pixelWidth: '1178',
              pixelHeight: '510',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:4326',
              wcsOutputSRS: 'EPSG:4326',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'qdri_preciptp30_raster',
              legend: {
                style: 'qdri_preciptp30_raster_display',
                customImageURL: null,
                title: '30 Day Total Precipitation (Inches)',
                panelTitle: '30 Day Total Precipitation (Inches)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'precip-tp-30_conus_day_data',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://edcintl.cr.usgs.gov/geoengine5/rest/version/5.0/config',
                start: {
                  period: 'datasets.qdpreciptp30.regions.qdhydrounits.periodicities.1-day.data.start.day',
                  month: '',
                  year: 'datasets.qdpreciptp30.regions.qdhydrounits.periodicities.1-day.data.start.year',
                },
                end: {
                  period: 'datasets.qdpreciptp30.regions.qdhydrounits.periodicities.1-day.data.end.day',
                  month: '',
                  year: 'datasets.qdpreciptp30.regions.qdhydrounits.periodicities.1-day.data.end.year',
                },
                skip: null,
                others: [],
              },
            },
          ],
        },
        {
          type: 'folder',
          title: '7 Day Total Precipitation',
          description:
            'A precipitation derivative map showing total rainfall in the last 7 days. Updated daily at 7:00 PM. For more information: https://earlywarning.usgs.gov/usraindry/',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              isWMST: true,
              name: 'qdpreciptp7:qdpreciptp7_qdhydrounits_1-day-{{period}}-{{year}}_mm_data',
              wmstName: 'quickdri_precip-tp-7_conus_day_data:precip-tp-7_conus_day_data',
              title: '',
              description:
                'A precipitation derivative map showing total rainfall in the last 7 days. Updated daily at 7:00 PM. For more information: https://earlywarning.usgs.gov/usraindry/',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
              },
              resolution: '0.05',
              pixelWidth: '1178',
              pixelHeight: '510',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:4326',
              wcsOutputSRS: 'EPSG:4326',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'qdri_preciptp7_raster',
              legend: {
                style: 'qdri_preciptp7_raster_display',
                customImageURL: null,
                title: '7 Day Total Precipitation (Inches)',
                panelTitle: '7 Day Total Precipitation (Inches)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'precip-tp-7_conus_day_data',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://edcintl.cr.usgs.gov/geoengine5/rest/version/5.0/config',
                start: {
                  period: 'datasets.qdpreciptp7.regions.qdhydrounits.periodicities.1-day.data.start.day',
                  month: '',
                  year: 'datasets.qdpreciptp7.regions.qdhydrounits.periodicities.1-day.data.start.year',
                },
                end: {
                  period: 'datasets.qdpreciptp7.regions.qdhydrounits.periodicities.1-day.data.end.day',
                  month: '',
                  year: 'datasets.qdpreciptp7.regions.qdhydrounits.periodicities.1-day.data.end.year',
                },
                skip: null,
                others: [],
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Max Consecutive Dry Days (Past 30 Days)',
          description:
            'A precipitation derivative map showing the maximum number of consecutive days without precipitation in the last 30 days. Updated daily at 7:00 PM. For more information: https://earlywarning.usgs.gov/usraindry/',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              isWMST: true,
              name: 'qdprecipcdd30:qdprecipcdd30_qdhydrounits_1-day-{{period}}-{{year}}_mm_data',
              wmstName: 'quickdri_precip-cdd-30_conus_day_data:precip-cdd-30_conus_day_data',
              title: '',
              description:
                'A precipitation derivative map showing the maximum number of consecutive days without precipitation in the last 30 days. Updated daily at 7:00 PM. For more information: https://earlywarning.usgs.gov/usraindry/',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
              },
              resolution: '0.05',
              pixelWidth: '1178',
              pixelHeight: '510',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: ['something'],
              srs: 'EPSG:4326',
              wcsOutputSRS: 'EPSG:4326',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'qdri_precipcdd30_raster',
              legend: {
                style: 'qdri_precipcdd30_raster_display',
                customImageURL: null,
                title: 'Max Consecutive Dry Days (Past 30 Days)',
                panelTitle: 'Max Consecutive Dry Days (Past 30 Days)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'precip-cdd-30_conus_day_data',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://edcintl.cr.usgs.gov/geoengine5/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Max Consecutive Dry Days (Past 7 Days)',
          description:
            'A precipitation derivative map showing the maximum number of consecutive days without precipitation in the last 7 days. Updated daily at 7:00 PM. For more information: https://earlywarning.usgs.gov/usraindry/',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              isWMST: true,
              name: 'qdprecipcdd7:qdprecipcdd7_qdhydrounits_1-day-{{period}}-{{year}}_mm_data',
              wmstName: 'quickdri_precip-cdd-7_conus_day_data:precip-cdd-7_conus_day_data',
              title: '',
              description:
                'A precipitation derivative map showing the maximum number of consecutive days without precipitation in the last 7 days. Updated daily at 7:00 PM. For more information: https://earlywarning.usgs.gov/usraindry/',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
              },
              resolution: '0.05',
              pixelWidth: '1178',
              pixelHeight: '510',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:4326',
              wcsOutputSRS: 'EPSG:4326',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'qdri_precipcdd7_raster',
              legend: {
                style: 'qdri_precipcdd7_raster_display',
                customImageURL: null,
                title: 'Max Consecutive Dry Days (Past 7 Days)',
                panelTitle: 'Max Consecutive Dry Days (Past 7 Days)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'precip-cdd-7_conus_day_data',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://edcintl.cr.usgs.gov/geoengine5/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Days with Precipitation (Past 30 Days)',
          description:
            'A precipitation derivative map showing the number of days with recorded precipitation in the last 30 days. Updated daily at 7:00 PM. For more information: https://earlywarning.usgs.gov/usraindry/',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              isWMST: true,
              name: 'qdpreciprd30:qdpreciprd30_qdhydrounits_1-day-{{period}}-{{year}}_mm_data',
              wmstName: 'quickdri_precip-rd-30_conus_day_data:precip-rd-30_conus_day_data',
              title: '',
              description:
                'A precipitation derivative map showing the number of days with recorded precipitation in the last 30 days. Updated daily at 7:00 PM. For more information: https://earlywarning.usgs.gov/usraindry/',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
              },
              resolution: '0.05',
              pixelWidth: '1178',
              pixelHeight: '510',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:4326',
              wcsOutputSRS: 'EPSG:4326',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'qdri_preciprd30_raster',
              legend: {
                style: 'qdri_preciprd30_raster_display',
                customImageURL: null,
                title: 'Days with Precipitation (Past 30 Days)',
                panelTitle: 'Days with Precipitation (Past 30 Days)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'precip-rd-30_conus_day_data',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://edcintl.cr.usgs.gov/geoengine5/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Days with Precipitation (Past 7 Days)',
          description:
            'A precipitation derivative map showing the number of days with recorded precipitation in the last 7 days. Updated daily at 7:00 PM. For more information: https://earlywarning.usgs.gov/usraindry/',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              isWMST: true,
              name: 'qdpreciprd7:qdpreciprd7_qdhydrounits_1-day-{{period}}-{{year}}_mm_data',
              wmstName: 'quickdri_precip-rd-7_conus_day_data:precip-rd-7_conus_day_data',
              title: '',
              description:
                'A precipitation derivative map showing the number of days with recorded precipitation in the last 7 days. Updated daily at 7:00 PM. For more information: https://earlywarning.usgs.gov/usraindry/',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
              },
              resolution: '0.05',
              pixelWidth: '1178',
              pixelHeight: '510',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:4326',
              wcsOutputSRS: 'EPSG:4326',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'qdri_preciprd7_raster',
              legend: {
                style: 'qdri_preciprd7_raster_display',
                customImageURL: null,
                title: 'Days with Precipitation (Past 7 Days)',
                panelTitle: 'Days with Precipitation (Past 7 Days)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'precip-rd-7_conus_day_data',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://edcintl.cr.usgs.gov/geoengine5/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Days Since Precipitation',
          description:
            'A precipitation derivative map showing the number of days since the last recorded precipitation. Updated daily at 7:00 PM. For more information: https://earlywarning.usgs.gov/usraindry/',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              isWMST: true,
              name: 'qdprecipdsr:qdprecipdsr_qdhydrounits_1-day-{{period}}-{{year}}_mm_data',
              wmstName: 'quickdri_precip-dsr_conus_day_data:precip-dsr_conus_day_data',
              title: '',
              description:
                'A precipitation derivative map showing the number of days since the last recorded precipitation. Updated daily at 7:00 PM. For more information: https://earlywarning.usgs.gov/usraindry/',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
              },
              resolution: '0.05',
              pixelWidth: '1178',
              pixelHeight: '510',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:4326',
              wcsOutputSRS: 'EPSG:4326',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'qdri_precipdsr_raster',
              legend: {
                style: 'qdri_precipdsr_raster_display',
                customImageURL: null,
                title: 'Days Since Precipitation',
                panelTitle: 'Days Since Precipitation',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'precip-dsr_conus_day_data',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://edcintl.cr.usgs.gov/geoengine5/rest/version/5.0/config',
              },
            },
          ],
        },
      ],
    },
  ],
  boundaries: [
    {
      type: 'folder',
      title: 'Reference Data',
      regionId: 'us',
      expanded: true,
      folder: [
        {
          type: 'layer',
          name: 'quickdri_uscounties:uscounties',
          title: 'U.S. County Boundaries',
          description: '',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
          },
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          featureInfo: {
            COUNTY: {
              displayName: 'COUNTY',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            FIPS: {
              displayName: 'FIPS',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            STATE: {
              displayName: 'STATE',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            STATE_FIPS: {
              displayName: 'STATE_FIPS',
              displayValue: null,
              value: null,
              mapValues: [],
            },
          },
          style: '',
        },
        {
          type: 'layer',
          name: 'quickdri_usstates3857:usstates3857',
          title: 'U.S. State Boundaries',
          description: '',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
          },
          loadOnly: false,
          display: true,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          featureInfo: {
            STATE: {
              displayName: 'STATE',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            STPOSTAL: {
              displayName: 'STPOSTAL',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            STFIPS: {
              displayName: 'STFIPS',
              displayValue: null,
              value: null,
              mapValues: [],
            },
          },
          style: '',
        },
        {
          type: 'layer',
          id: 'qdhydrounits_id',
          name: 'quickdri_shapefile_HydrologicUnits:shapefile_HydrologicUnits',
          title: 'Land Cover/HydroUnit',
          description:
            'A zonal map derived by intersecting land cover (generalized NLCD) with hydrologic units (HUC6). Each unique combination of land cover and hydrologic unit is represented as a zone.  For more information: https://vegdri.cr.usgs.gov/',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
          },
          loadOnly: true,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          featureInfo: {
            Zone_ID: {
              displayName: 'Zone_ID',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            US_HUC6_NO: {
              displayName: 'US_HUC6_NO',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            NLCD: {
              displayName: 'NLCD',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            SEAS_START: {
              displayName: 'SEAS_START',
              displayValue: null,
              value: null,
              mapValues: [],
            },
          },
          style: 'qdri_admin0_transparent',
        },
        {
          type: 'layer',
          name: 'quickdri_shapefile_HydrologicUnits:shapefile_HydrologicUnits',
          title: 'Land Cover/HydroUnit',
          description:
            'A zonal map derived by intersecting land cover (generalized NLCD) with hydrologic units (HUC6). Each unique combination of land cover and hydrologic unit is represented as a zone.  For more information: https://vegdri.cr.usgs.gov/',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
          },
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          featureInfo: {
            Zone_ID: {
              displayName: 'Zone_ID',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            US_HUC6_NO: {
              displayName: 'US_HUC6_NO',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            NLCD: {
              displayName: 'NLCD',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            SEAS_START: {
              displayName: 'SEAS_START',
              displayValue: null,
              value: null,
              mapValues: [],
            },
          },
          style: 'qdri_admin_0_display',
        },
        {
          type: 'layer',
          name: 'quickdri_water_watch_today:water_watch_today',
          title: 'Water Watch - 7-Day Average Streamflow',
          description:
            '7-Day average streamflow map shows the average streamflow conditions for the past seven days. Updated daily at 10:00 AM. For more information:  https://waterwatch.usgs.gov/ ',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs',
          },
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          transparency: true,
          regionIds: ['us'],
          srs: 'EPSG:4326',
          featureInfo: {},
          style: '',
          legend: {
            style: '',
            customImageURL: quickdriCustomWaterWatchLegend,
            title: 'Water Watch - 7-Day Average Streamflow',
          },
          unit: '',
        },
        {
          type: 'layer',
          name: 'quickdri_MIrAD250m_2002v3:MIrAD250m_2002v3',
          title: '2002 MIrAD',
          description:
            '2002 Moderate Resolution Imaging Spectroradiometer (MODIS) Irrigated Agriculture Dataset for the United States (MIrAD-US).  For more information: https://earlywarning.usgs.gov/USirrigation',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
          },
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          featureInfo: {
            GRAY_INDEX: {
              displayName: 'Pixel Value',
              displayValue: null,
              value: null,
              mapValues: [],
            },
          },
          style: 'qdri_mirad_2002',
          legend: {
            style: 'qdri_mirad_2002_display',
            title: '2002 MIrAD',
          },
        },
        {
          type: 'layer',
          name: 'quickdri_MIrAD250m_2007v3:MIrAD250m_2007v3',
          title: '2007 MIrAD',
          description:
            '2007 Moderate Resolution Imaging Spectroradiometer (MODIS) Irrigated Agriculture Dataset for the United States (MIrAD-US).  For more information: https://earlywarning.usgs.gov/USirrigation',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
          },
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          featureInfo: {
            GRAY_INDEX: {
              displayName: 'Pixel Value',
              displayValue: null,
              value: null,
              mapValues: [],
            },
          },
          style: 'qdri_mirad_2007',
          legend: {
            style: 'qdri_mirad_2007_display',
            title: '2007 MIrAD',
          },
        },
        {
          type: 'layer',
          name: 'quickdri_MIrAD250m_2012v3:MIrAD250m_2012v3',
          title: '2012 MIrAD',
          description:
            '2012 Moderate Resolution Imaging Spectroradiometer (MODIS) Irrigated Agriculture Dataset for the United States (MIrAD-US).  For more information: https://earlywarning.usgs.gov/USirrigation',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
          },
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          featureInfo: {
            GRAY_INDEX: {
              displayName: 'Pixel Value',
              displayValue: null,
              value: null,
              mapValues: [],
            },
          },
          style: 'qdri_mirad_2012',
          legend: {
            style: 'qdri_mirad_2012_display',
            title: '2012 MIrAD',
          },
        },
      ],
    },
  ],
  baselayers: [
    {
      type: 'folder',
      title: 'Base Layers',
      expanded: true,
      folder: [
        {
          type: 'layer',
          name: 'osm_0',
          title: 'Standard OpenStreetMap',
          description: '',
          loadOnly: false,
          display: true,
          mask: false,
          srs: 'EPSG:3857',
          loaded: 'true',
          brand: 'osm',
          source: {
            url: 'https://osm-{1-4}.gs.mil/tiles/default/{z}/{x}/{y}.png',
          },
          comments: '',
        },
      ],
    },
  ],
};
