import mrlcLogo from '../../assets/images/mrlc/mrlc-logo.png';

export const template = {
  theme: 'ExtJSNeptune',
  cssFallback: true,
  analytics: {
    matomo: {
      baseUrl: '//edcintl.cr.usgs.gov/piwik/',
      id: '8',
    },
    google: {
      id: 'UA-127886240-1',
    },
  },
  blocks: [
    {
      block: 'top',
      name: 'cHeader',
      import: 'js.tools.shared.cHeader.cHeader',
      title: 'MRLC Viewer',
      add: true,
      width: 'auto',
      height: 70,
      cssClass: '',
      collapsible: true,
      content: `<div style='width: 100%; height: 100%; padding: 15px;'><a style='color:#2d2d2d;' href='/' title='Home'><img style='float: left; height: 40px; width: auto; padding-right: 15px' src='${mrlcLogo}' /><span style='float: left; margin: 0;'>Celebrating 20+ years of Partnership<br><b>Multi-Resolution Land Characteristics<br>Consortium</b></span></a></div>`,
      link: 'https://www.mrlc.gov',
    },
    {
      block: 'left',
      name: 'cToc',
      import: 'js.tools.shared.cToc.cToc',
      add: true,
      width: 380,
      height: 'auto',
      title: 'TOC',
      collapsible: true,
      blocks: [
        {
          block: 'center',
          name: 'cTocTabPanel',
          import: 'js.tools.shared.cTocTabPanel.cTocTabPanel',
          add: true,
          blocks: [
            {
              add: true,
              title: 'Contents',
              name: 'cTocContentsScrollTab',
              import: 'js.tools.shared.cTocContentsScrollTab.cTocContentsScrollTab',
              blocks: [
                {
                  height: 100,
                  name: 'cDefaultToc',
                  import: 'js.tools.shared.cDefaultToc.cDefaultToc',
                  add: true,
                  titleLength: 70,
                  hideDatePicker: true,
                },
                {
                  name: 'cTransparency',
                  add: true,
                  import: 'js.tools.shared.cTransparency.cTransparency',
                  height: 100,
                  width: '90%',
                },
              ],
              toolbar: {
                position: 'top',
                overflowMenu: false,
                items: [
                  {
                    name: 'cRegionTool',
                    import: 'js.tools.shared.cRegionTool.cRegionTool',
                    add: true,
                    width: 150,
                  },
                  {
                    name: 'cSpacer',
                    import: 'js.tools.shared.cSpacer.cSpacer',
                    add: true,
                  },
                  {
                    name: 'cAddMapWindowTool',
                    import: 'js.tools.shared.cAddMapWindowTool.cAddMapWindowTool',
                    title: '',
                    add: true,
                    cssClass: '',
                    tooltip: 'New Map Window',
                  },
                  {
                    name: 'cAddWMSLayerTool',
                    import: 'js.tools.shared.cAddWMSLayerTool.cAddWMSLayerTool',
                    add: true,
                    tooltip: 'Add WMS Layer',
                  },
                  {
                    name: 'cRemoveWMSLayerTool',
                    import: 'js.tools.shared.cRemoveWMSLayerTool.cRemoveWMSLayerTool',
                    add: true,
                    tooltip: 'Remove WMS Layer',
                  },
                ],
              },
            },
            {
              add: true,
              title: 'Legend',
              name: 'cTocLegendTab',
              import: 'js.tools.shared.cTocLegendTab.cTocLegendTab',
            },
          ],
        },
      ],
    },
    {
      block: 'center',
      blocks: [
        {
          block: 'relative',
          name: 'cMapWindow',
          import: 'js.tools.shared.cMapWindow.cMapWindow',
          initialWinNum: 2,
          add: true,
          width: 580,
          height: 650,
          x: 410,
          y: 90,
          collapsible: true,
          toolbar: {
            position: 'top',
            add: true,
            overflowMenu: true,
            items: [
              {
                name: 'cZoomToRegionTool',
                title: '',
                add: true,
                import: 'js.tools.shared.cZoomToRegionTool.cZoomToRegionTool',
                cssClass: '',
                tooltip: 'Zoom to Region',
              },
              {
                name: 'cPanTool',
                title: '',
                add: true,
                import: 'js.tools.shared.cPanTool.cPanTool',
                cssClass: '',
                tooltip: 'Pan Tool',
              },
              {
                name: 'cExtentDragBoxTool',
                title: '',
                add: true,
                import: 'js.tools.shared.cExtentDragBoxTool.cExtentDragBoxTool',
                cssClass: '',
                tooltip: 'Zoom to Extent',
              },
              {
                name: 'cRevertExtentTool',
                title: '',
                add: true,
                import: 'js.tools.shared.cRevertExtentTool.cRevertExtentTool',
                cssClass: '',
                tooltip: 'Zoom to Previous',
              },
              {
                name: 'cIdentifyTool',
                title: '',
                add: true,
                import: 'js.tools.shared.cIdentifyTool.cIdentifyTool',
                cssClass: '',
                tooltip: 'Identify Tool',
              },
              {
                name: 'cDataDownloadBtn',
                add: true,
                import: 'js.tools.mrlc.cDataDownloadBtn.cDataDownloadBtn',
                tooltip: 'Open Data Download Tool',
              },
              {
                name: 'cSpacer',
                import: 'js.tools.shared.cSpacer.cSpacer',
                add: true,
              },
              {
                name: 'cMapLegendTool',
                add: true,
                import: 'js.tools.shared.cMapLegendTool.cMapLegendTool',
                tooltip: 'Toggle map legend',
                pressed: false,
              },
            ],
          },
          blocks: [
            {
              name: 'cMapPanel',
              import: 'js.tools.shared.cMapPanel.cMapPanel',
              add: true,
              interactions: ['pan', 'zoom'],
              mouseCoordinates: {
                show: true,
                projection: 'EPSG:4326',
              },
              blocks: [
                {
                  name: 'cMapLegend',
                  block: 'relative',
                  import: 'js.tools.shared.cMapLegend.cMapLegend',
                  add: true,
                },
              ],
            },
          ],
        },
        {
          block: 'relative',
          name: 'cAddWMSLayerForm',
          import: 'js.tools.shared.cAddWMSLayerForm.cAddWMSLayerForm',
          add: true,
          width: 350,
          height: 105,
          x: 390,
          y: 222,
          title: 'Add WMS Layers',
        },
        {
          block: 'relative',
          name: 'cRemoveWMSLayerForm',
          import: 'js.tools.shared.cRemoveWMSLayerForm.cRemoveWMSLayerForm',
          add: true,
          width: 350,
          height: 105,
          x: 390,
          y: 222,
          title: 'Remove WMS Layers',
        },
      ],
    },
    {
      block: 'right',
      name: 'cTools',
      import: 'js.tools.shared.cTools.cTools',
      add: true,
      width: 250,
      height: 'auto',
      collapsible: true,
      collapsed: false,
      title: 'Tools',
      blocks: [
        {
          name: 'cDataDownload',
          add: true,
          collapsible: true,
          collapsed: true,
          import: 'js.tools.mrlc.cDataDownload.cDataDownload',
          addQueueLocation: '/viewerRest/addQueue.php',
          redirectText: `<b>NOTICE:</b><br> The extent of your download box<br>is too large. (Greater than 350000 <br>square km).
          <br><br>Please select a smaller area of<br>interest or go <a href="/data" target="_blank">here</a><br>to download a complete<br>dataset.`,
          noBoxText:
            'A box has not been drawn yet. <br><br> To draw one, please select the <br>Data Download tool <i class="fa fa-arrow-circle-o-down mrlc-fb"></i><br>in the map window toolbar.',
          maxArea: 350000,
          shapeFile: 'mrlc_display:Viewer_Layers_Extent',
          yearCheckboxes: [2019, 'All'],
          categories: {
            /* land_cover: '(NLCD_[a-z0-9_-]*2016[a-z0-9_-]*_Land_Cover)|(NLCD_Land_Cover_Change_Index)', */
            land_cover: '(((nlcd)|(NLCD))_2019_land_cover)|(nlcd_[a-z0-9_-]*_change_index)',
            science_products:
              '(NLCD_2019_Land_Cover_Science_Product)|(NLCD_2001_2019_Land_Cover_Change_Index)|(NLCD_Forest_Disturbance_Date)|(NLCD_01-19_Land_Cover_Change_First_Disturbance_Date)|(NLCD_01-19_Land_Cover_Change_Count)',
            tree_canopy: '(NLCD_2019_Tree_Canopy)|(NLCD_Tree_Canopy_Change_Index)',
            /* impervious: '(NLCD_[a-z0-9_-]*2016[a-z0-9_-]*_Impervious)|(NLCD_2016_Urban_Descriptor)', */
            impervious: '(((nlcd)|(NLCD))_2019_impervious)|(NLCD_2019_Urban_Descriptor)',
            default: '((nlcd)|(NLCD))_2019_',
          },
        },
        {
          name: 'cFeatureInfoPanel',
          import: 'js.tools.shared.cFeatureInfoPanel.cFeatureInfoPanel',
          add: true,
          title: 'Feature Info',
          height: 250,
          width: '100%',
          collapsible: true,
          collapsed: true,
          cssClass: '',
        },
        {
          name: 'cSpatialLocking',
          import: 'js.tools.shared.cSpatialLocking.cSpatialLocking',
          add: true,
          title: 'Spatial Locking Tool',
          height: 250,
          collapsible: true,
          cssClass: '',
          defaultLock: true,
        },
        {
          name: 'cArrangeWindows',
          import: 'js.tools.shared.cArrangeWindows.cArrangeWindows',
          add: true,
          title: 'Arrange Windows Tool',
          height: 250,
          collapsible: true,
          cssClass: '',
        },
      ],
    },
  ],
};
