import PSALegend from '../../assets/images/legends/firedanger_fpi_psa.png';
import FPIWindLegend from '../../assets/images/legends/fpiwind_legend.png';
import FPIWindDescription from '../../assets/images/legends/fpiwind_layer_description.png';

export const layers = {
  overlays: [
    {
      type: 'folder',
      title: 'Operational Fire Danger Forecast Products',
      expanded: true,
      folder: [
        // WFPI Forecasts
        {
          type: 'folder',
          title: 'WFPI Forecast - Day 1',
          description:
            'The Wildland Fire Potential Index is a unit-less number that ranges from 0 to about 150 and relates to vegetation flammability -- <a href="https://www.usgs.gov/ecosystems/lcsp/fire-danger-forecast/wind-enhanced-fire-potential-index-wfpi" target="_blank">more information</a>',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              title: '',
              id: 'wfpi_forecast_1',
              isWMST: true,
              wmstName: 'firedanger_emodis-wfpi-forecast-1_conus_day_data:emodis-wfpi-forecast-1_conus_day_data',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: true,
              active: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                PALETTE_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'firedanger_emodis_daily_wfpi_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wfpi_conus_raster_legend',
                customImageURL: null,
                title: 'WFPI',
                panelTitle: 'WFPI',
              },
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wfpi-forecast-1_conus_day_data',
                downloadCategoryTitle: 'WFPI Forecast - Day 1',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI Forecast - Day 2',
          description:
            'The operational Wildland Fire Potential Index (WFPI) product that was originally forecasted for one day past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wfpi_forecast_2',
              name: 'WFPI Forecast - Day 2',
              isWMST: true,
              wmstName: 'firedanger_emodis-wfpi-forecast-2_conus_day_data:emodis-wfpi-forecast-2_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                PALETTE_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'firedanger_emodis_daily_wfpi_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wfpi_conus_raster_legend',
                customImageURL: null,
                title: 'WFPI',
                panelTitle: 'WFPI',
              },
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wfpi-forecast-2_conus_day_data',
                downloadCategoryTitle: 'WFPI Forecast - Day 2',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI Forecast - Day 3',
          description:
            'The operational Wildland Fire Potential Index (WFPI) product that was originally forecasted for two days past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wfpi_forecast_3',
              name: 'WFPI Forecast - Day 3',
              isWMST: true,
              wmstName: 'firedanger_emodis-wfpi-forecast-3_conus_day_data:emodis-wfpi-forecast-3_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                PALETTE_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'firedanger_emodis_daily_wfpi_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wfpi_conus_raster_legend',
                customImageURL: null,
                title: 'WFPI',
                panelTitle: 'WFPI',
              },
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wfpi-forecast-3_conus_day_data',
                downloadCategoryTitle: 'WFPI Forecast - Day 3',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI Forecast - Day 4',
          description:
            'The operational Wildland Fire Potential Index (WFPI) product that was originally forecasted for three days past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wfpi_forecast_4',
              name: 'WFPI Forecast - Day 4',
              isWMST: true,
              wmstName: 'firedanger_emodis-wfpi-forecast-4_conus_day_data:emodis-wfpi-forecast-4_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                PALETTE_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'firedanger_emodis_daily_wfpi_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wfpi_conus_raster_legend',
                customImageURL: null,
                title: 'WFPI',
                panelTitle: 'WFPI',
              },
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wfpi-forecast-4_conus_day_data',
                downloadCategoryTitle: 'WFPI Forecast - Day 4',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI Forecast - Day 5',
          description:
            'The operational Wildland Fire Potential Index (WFPI) product that was originally forecasted for four days past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wfpi_forecast_5',
              name: 'WFPI Forecast - Day 5',
              isWMST: true,
              wmstName: 'firedanger_emodis-wfpi-forecast-5_conus_day_data:emodis-wfpi-forecast-5_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                PALETTE_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'firedanger_emodis_daily_wfpi_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wfpi_conus_raster_legend',
                customImageURL: null,
                title: 'WFPI',
                panelTitle: 'WFPI',
              },
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wfpi-forecast-5_conus_day_data',
                downloadCategoryTitle: 'WFPI Forecast - Day 5',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI Forecast - Day 6',
          description:
            'The operational Wildland Fire Potential Index (WFPI) product that was originally forecasted for five days past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wfpi_forecast_6',
              name: 'WFPI Forecast - Day 6',
              isWMST: true,
              wmstName: 'firedanger_emodis-wfpi-forecast-6_conus_day_data:emodis-wfpi-forecast-6_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                PALETTE_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'firedanger_emodis_daily_wfpi_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wfpi_conus_raster_legend',
                customImageURL: null,
                title: 'WFPI',
                panelTitle: 'WFPI',
              },
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wfpi-forecast-6_conus_day_data',
                downloadCategoryTitle: 'WFPI Forecast - Day 6',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI Forecast - Day 7',
          description:
            'The operational Wildland Fire Potential Index (WFPI) product that was originally forecasted for six days past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wfpi_forecast_7',
              name: 'WFPI Forecast - Day 7',
              isWMST: true,
              wmstName: 'firedanger_emodis-wfpi-forecast-7_conus_day_data:emodis-wfpi-forecast-7_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                PALETTE_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'firedanger_emodis_daily_wfpi_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wfpi_conus_raster_legend',
                customImageURL: null,
                title: 'WFPI',
                panelTitle: 'WFPI',
              },
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wfpi-forecast-7_conus_day_data',
                downloadCategoryTitle: 'WFPI Forecast - Day 7',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        // WFPI-based LFP
        {
          type: 'folder',
          title: 'WFPI-based Large Fire Probability - Day 1',
          description: `The Wildland Large Fire Probability is an estimate of the risk (probability) of occurrence of a new fire that will burn more than 500 acres (202 ha) -- <a href="https://www.usgs.gov/ecosystems/lcsp/fire-danger-forecast/wfpi-based-large-fire-probability-wlfp" target="_blank">more information</a>`,
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wlfp_forecast_1',
              isWMST: true,
              wmstName: 'firedanger_emodis-wlfp-forecast-1_conus_day_data:emodis-wlfp-forecast-1_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                  significantDigits: 2,
                },
              },
              style: 'firedanger_emodis_daily_wlfp_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wlfp_conus_raster_legend',
                customImageURL: null,
                title: 'WLFP<br />Probability (per million)',
                panelTitle: 'WLFP<br />Probability (per million)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wlfp-forecast-1_conus_day_data',
                downloadCategoryTitle: 'Large Fire Probability - Day 1',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI-based Large Fire Probability - Day 2',
          description:
            'The operational  Wildland Large Fire Probability (WLFP) product that was originally forecasted for one day past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wlfp_forecast_2',
              isWMST: true,
              wmstName: 'firedanger_emodis-wlfp-forecast-2_conus_day_data:emodis-wlfp-forecast-2_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                  significantDigits: 2,
                },
              },
              style: 'firedanger_emodis_daily_wlfp_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wlfp_conus_raster_legend',
                customImageURL: null,
                title: 'WLFP<br />Probability (per million)',
                panelTitle: 'WLFP<br />Probability (per million)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wlfp-forecast-2_conus_day_data',
                downloadCategoryTitle: 'Large Fire Probability - Day 2',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI-based Large Fire Probability - Day 3',
          description:
            'The operational  Wildland Large Fire Probability (WLFP) product that was originally forecasted for two days past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wlfp_forecast_3',
              isWMST: true,
              wmstName: 'firedanger_emodis-wlfp-forecast-3_conus_day_data:emodis-wlfp-forecast-3_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                  significantDigits: 2,
                },
              },
              style: 'firedanger_emodis_daily_wlfp_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wlfp_conus_raster_legend',
                customImageURL: null,
                title: 'WLFP<br />Probability (per million)',
                panelTitle: 'WLFP<br />Probability (per million)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wlfp-forecast-3_conus_day_data',
                downloadCategoryTitle: 'Large Fire Probability - Day 3',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI-based Large Fire Probability - Day 4',
          description:
            'The operational  Wildland Large Fire Probability (WLFP) product that was originally forecasted for three days past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wlfp_forecast_4',
              isWMST: true,
              wmstName: 'firedanger_emodis-wlfp-forecast-4_conus_day_data:emodis-wlfp-forecast-4_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                  significantDigits: 2,
                },
              },
              style: 'firedanger_emodis_daily_wlfp_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wlfp_conus_raster_legend',
                customImageURL: null,
                title: 'WLFP<br />Probability (per million)',
                panelTitle: 'WLFP<br />Probability (per million)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wlfp-forecast-4_conus_day_data',
                downloadCategoryTitle: 'Large Fire Probability - Day 4',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI-based Large Fire Probability - Day 5',
          description:
            'The operational  Wildland Large Fire Probability (WLFP) product that was originally forecasted for four days past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wlfp_forecast_5',
              isWMST: true,
              wmstName: 'firedanger_emodis-wlfp-forecast-5_conus_day_data:emodis-wlfp-forecast-5_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                  significantDigits: 2,
                },
              },
              style: 'firedanger_emodis_daily_wlfp_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wlfp_conus_raster_legend',
                customImageURL: null,
                title: 'WLFP<br />Probability (per million)',
                panelTitle: 'WLFP<br />Probability (per million)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wlfp-forecast-5_conus_day_data',
                downloadCategoryTitle: 'Large Fire Probability - Day 5',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI-based Large Fire Probability - Day 6',
          description:
            'The operational  Wildland Large Fire Probability (WLFP) product that was originally forecasted for five days past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wlfp_forecast_6',
              isWMST: true,
              wmstName: 'firedanger_emodis-wlfp-forecast-6_conus_day_data:emodis-wlfp-forecast-6_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                  significantDigits: 2,
                },
              },
              style: 'firedanger_emodis_daily_wlfp_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wlfp_conus_raster_legend',
                customImageURL: null,
                title: 'WLFP<br />Probability (per million)',
                panelTitle: 'WLFP<br />Probability (per million)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wlfp-forecast-6_conus_day_data',
                downloadCategoryTitle: 'Large Fire Probability - Day 6',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI-based Large Fire Probability - Day 7',
          description:
            'The operational  Wildland Large Fire Probability (WLFP) product that was originally forecasted for six days past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wlfp_forecast_7',
              isWMST: true,
              wmstName: 'firedanger_emodis-wlfp-forecast-7_conus_day_data:emodis-wlfp-forecast-7_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                  significantDigits: 2,
                },
              },
              style: 'firedanger_emodis_daily_wlfp_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wlfp_conus_raster_legend',
                customImageURL: null,
                title: 'WLFP<br />Probability (per million)',
                panelTitle: 'WLFP<br />Probability (per million)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wlfp-forecast-7_conus_day_data',
                downloadCategoryTitle: 'Large Fire Probability - Day 7',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        // WFPI-based FSP
        {
          type: 'folder',
          title: 'WFPI-based Fire Spread Probability - Day 1',
          description: `The wildland probability of fire spread is an estimate of the risk of an existing one-acre (0.4 ha) fire spreading to burn more than 500 acres (202ha) -- <a href="https://www.usgs.gov/ecosystems/lcsp/fire-danger-forecast/wfpi-based-fire-spread-probability-wfsp" target="_blank">more information</a>`,
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wfsp_forecast_1',
              isWMST: true,
              wmstName: 'firedanger_emodis-wfsp-forecast-1_conus_day_data:emodis-wfsp-forecast-1_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                  significantDigits: 2,
                },
              },
              style: 'firedanger_emodis_daily_wfsp_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wfsp_conus_raster_legend',
                customImageURL: null,
                title: 'WFSP<br />Probability (percent)',
                panelTitle: 'WFSP<br />Probability (percent)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wfsp-forecast-1_conus_day_data',
                downloadCategoryTitle: 'Fire Spread Probability - Day 1',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI-based Fire Spread Probability - Day 2',
          description:
            'The operational WFPI-based Probability of Fire Spread (WFSP) product that was originally forecasted for one day past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wfsp_forecast_2',
              isWMST: true,
              wmstName: 'firedanger_emodis-wfsp-forecast-2_conus_day_data:emodis-wfsp-forecast-2_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                  significantDigits: 2,
                },
              },
              style: 'firedanger_emodis_daily_wfsp_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wfsp_conus_raster_legend',
                customImageURL: null,
                title: 'WFSP<br />Probability (percent)',
                panelTitle: 'WFSP<br />Probability (percent)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wfsp-forecast-2_conus_day_data',
                downloadCategoryTitle: 'Fire Spread Probability - Day 2',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI-based Fire Spread Probability - Day 3',
          description:
            'The operational WFPI-based Probability of Fire Spread (WFSP) product that was originally forecasted for two days past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wfsp_forecast_3',
              isWMST: true,
              wmstName: 'firedanger_emodis-wfsp-forecast-3_conus_day_data:emodis-wfsp-forecast-3_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                  significantDigits: 2,
                },
              },
              style: 'firedanger_emodis_daily_wfsp_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wfsp_conus_raster_legend',
                customImageURL: null,
                title: 'WFSP<br />Probability (percent)',
                panelTitle: 'WFSP<br />Probability (percent)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wfsp-forecast-3_conus_day_data',
                downloadCategoryTitle: 'Fire Spread Probability - Day 3',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI-based Fire Spread Probability - Day 4',
          description:
            'The operational WFPI-based Probability of Fire Spread (WFSP) product that was originally forecasted for three days past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wfsp_forecast_4',
              isWMST: true,
              wmstName: 'firedanger_emodis-wfsp-forecast-4_conus_day_data:emodis-wfsp-forecast-4_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                  significantDigits: 2,
                },
              },
              style: 'firedanger_emodis_daily_wfsp_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wfsp_conus_raster_legend',
                customImageURL: null,
                title: 'WFSP<br />Probability (percent)',
                panelTitle: 'WFSP<br />Probability (percent)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wfsp-forecast-4_conus_day_data',
                downloadCategoryTitle: 'Fire Spread Probability - Day 4',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI-based Fire Spread Probability - Day 5',
          description:
            'The operational WFPI-based Probability of Fire Spread (WFSP) product that was originally forecasted for four days past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wfsp_forecast_5',
              isWMST: true,
              wmstName: 'firedanger_emodis-wfsp-forecast-5_conus_day_data:emodis-wfsp-forecast-5_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                  significantDigits: 2,
                },
              },
              style: 'firedanger_emodis_daily_wfsp_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wfsp_conus_raster_legend',
                customImageURL: null,
                title: 'WFSP<br />Probability (percent)',
                panelTitle: 'WFSP<br />Probability (percent)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wfsp-forecast-5_conus_day_data',
                downloadCategoryTitle: 'Fire Spread Probability - Day 5',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI-based Fire Spread Probability - Day 6',
          description:
            'The operational WFPI-based Probability of Fire Spread (WFSP) product that was originally forecasted for five days past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wfsp_forecast_6',
              isWMST: true,
              wmstName: 'firedanger_emodis-wfsp-forecast-6_conus_day_data:emodis-wfsp-forecast-6_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                  significantDigits: 2,
                },
              },
              style: 'firedanger_emodis_daily_wfsp_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wfsp_conus_raster_legend',
                customImageURL: null,
                title: 'WFSP<br />Probability (percent)',
                panelTitle: 'WFSP<br />Probability (percent)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wfsp-forecast-6_conus_day_data',
                downloadCategoryTitle: 'Fire Spread Probability - Day 6',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'WFPI-based Fire Spread Probability - Day 7',
          description:
            'The operational WFPI-based Probability of Fire Spread (WFSP) product that was originally forecasted for six days past the processing date.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wfsp_forecast_7',
              isWMST: true,
              wmstName: 'firedanger_emodis-wfsp-forecast-7_conus_day_data:emodis-wfsp-forecast-7_conus_day_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                  significantDigits: 2,
                },
              },
              style: 'firedanger_emodis_daily_wfsp_conus_raster',
              legend: {
                style: 'firedanger_emodis_daily_wfsp_conus_raster_legend',
                customImageURL: null,
                title: 'WFSP<br />Probability (percent)',
                panelTitle: 'WFSP<br />Probability (percent)',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-wfsp-forecast-7_conus_day_data',
                downloadCategoryTitle: 'Fire Spread Probability - Day 7',
              },
              timeseries: {
                type: 'day',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
      ],
    },
    {
      type: 'folder',
      title: 'NDVI/Greenness',
      expanded: true,
      regionId: 'us',
      folder: [
        {
          type: 'folder',
          title: 'NDVI Weekly Greenness',
          description: 'The weekly normalized difference vegetation (NDVI) index image shows the current greenness levels.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'wgreenFireDanger',
              name: 'greenness_us_1-sevenday-{{period}}-{{year}}_data',
              isWMST: true,
              wmstName: 'firedanger_emodis-ndvi-greenness_conus_week_data:emodis-ndvi-greenness_conus_week_data',
              title: '',
              description:
                'A precipitation derivative map showing total rainfall in the last 30 days. Updated daily at 7:00 PM. For more information: https://earlywarning.usgs.gov/usraindry/',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {
                PALETTE_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                  modifyDisplayValue: true,
                },
              },
              style: 'firedanger_emodis_weekly_ndvi_conus_raster',
              legend: {
                style: 'firedanger_emodis_weekly_ndvi_conus_raster_legend',
                customImageURL: null,
                title: 'NDVI Greennness',
                panelTitle: 'NDVI Greennness',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-ndvi-greenness_conus_week_data',
              },
              timeseries: {
                type: 'firedanger_week',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
        {
          type: 'folder',
          title: 'Relative Weekly Greenness',
          description: 'This relative greenness shows how green this time period is relative to the maximum greenness over the course of a year.',
          expanded: false,
          regionId: 'us',
          folder: [
            {
              type: 'layer',
              id: 'rgreenFireDanger',
              name: 'rgreen_us_week-{{period}}-{{year}}_data',
              isWMST: true,
              wmstName: 'firedanger_emodis-rg_conus_week_data:emodis-rg_conus_week_data',
              title: '',
              source: {
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
              },
              resolution: '0.05',
              pixelWidth: '3400',
              pixelHeight: '2000',
              loadOnly: false,
              display: false,
              mask: false,
              zIndex: 0,
              transparency: true,
              regionIds: ['us'],
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {
                PALETTE_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              style: 'firedanger_emodis_weekly_rg_conus_raster',
              legend: {
                style: 'firedanger_emodis_weekly_rg_conus_raster_legend',
                customImageURL: null,
                title: 'Relative Weekly Greenness',
                panelTitle: 'Relative Weekly Greenness',
              },
              unit: '',
              additionalAttributes: {
                statistic: 'data',
                rasterDataset: 'emodis-rg_conus_week_data',
              },
              timeseries: {
                type: 'firedanger_week',
                format: 'f1',
                source: 'https://stagegeoengine.cr.usgs.gov/api/rest/version/5.0/config',
              },
            },
          ],
        },
      ],
    },
    {
      type: 'folder',
      title: 'Download Layers',
      expanded: false,
      regionId: 'us',
      folder: [
        {
          type: 'layer',
          name: 'firedanger_Viewer_Layers_Extent_20210113:Viewer_Layers_Extent_20210113',
          description: 'Shapefile layer for cDataDownload',
          source: {
            wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
          },
          loadOnly: true,
          display: false,
          mask: false,
          transparency: false,
          zIndex: 0,
          srs: 'EPSG:2163',
        },
      ],
    },
  ],
  boundaries: [
    {
      type: 'folder',
      title: 'Reference Data',
      regionId: 'us',
      expanded: true,
      folder: [
        {
          type: 'layer',
          name: 'firedanger_predictive_service_area_extent:predictive_service_area_extent',
          title: 'Predictive Service Area',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
          },
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          style: '',
        },
        {
          type: 'layer',
          name: 'firedanger_national_atlas_federal_lands:national_atlas_federal_lands',
          title: 'National Atlas Federal Lands',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
          },
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          style: '',
        },
        {
          type: 'layer',
          name: 'firedanger_national_atlas_indian_lands:national_atlas_indian_lands',
          title: 'National Atlas Indian Lands',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
          },
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          style: '',
        },
        {
          type: 'layer',
          name: 'firedanger_national_atlas_waterbodies:national_atlas_waterbodies',
          title: 'National Atlas Waterbodies',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
          },
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          style: '',
        },
        {
          type: 'layer',
          name: 'firedanger_national_atlas_streams:national_atlas_streams',
          title: 'National Atlas Streams',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
          },
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          style: '',
        },
        {
          type: 'layer',
          name: 'firedanger_national_atlas_counties:national_atlas_counties',
          title: 'U.S. County Boundaries',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
          },
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          featureInfo: {
            COUNTY: {
              displayName: 'COUNTY',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            FIPS: {
              displayName: 'FIPS',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            STATE: {
              displayName: 'STATE',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            STATE_FIPS: {
              displayName: 'STATE_FIPS',
              displayValue: null,
              value: null,
              mapValues: [],
            },
          },
          style: '',
        },
        {
          type: 'layer',
          name: 'firedanger_national_atlas_states:national_atlas_states',
          title: 'U.S. State Boundaries',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            gwc: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
          },
          loadOnly: false,
          display: true,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          featureInfo: {
            STATE: {
              displayName: 'STATE',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            STPOSTAL: {
              displayName: 'STPOSTAL',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            STFIPS: {
              displayName: 'STFIPS',
              displayValue: null,
              value: null,
              mapValues: [],
            },
          },
          style: '',
        },
      ],
    },
  ],
  baselayers: [
    {
      type: 'folder',
      title: 'Base Layers',
      expanded: true,
      folder: [
        {
          type: 'layer',
          name: 'osm_0',
          title: 'Standard OpenStreetMap',
          loadOnly: false,
          display: true,
          mask: false,
          srs: 'EPSG:3857',
          loaded: 'true',
          brand: 'osm',
          source: {
            url: 'https://osm-{1-4}.gs.mil/tiles/default/{z}/{x}/{y}.png',
          },
          comments: '',
        },
        {
          type: 'layer',
          name: 'firedanger_GTOPO60_color_relief:GTOPO60_color_relief',
          title: 'GTOPO60 Color Shaded Relief',
          source: {
            gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
          },
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          style: '',
        },
      ],
    },
  ],
};
