import logo from '../../assets/images/logo.png';

export const template = {
  theme: 'ExtJSNeptune',
  cssFallback: true,
  analytics: {
    matomo: {
      baseUrl: '//edcintl.cr.usgs.gov/piwik/',
      id: '17',
    },
    google: {
      id: 'UA-185745030-1',
    },
  },
  blocks: [
    {
      block: 'top',
      name: 'cHeader',
      import: 'js.tools.shared.cHeader.cHeader',
      title: 'Fire Danger Viewer',
      add: true,
      width: 'auto',
      height: 70,
      cssClass: '',
      collapsible: true,
      content: `<header id='navbar' class='header-nav'  role='banner'><div class='tmp-container'><div class='header-search'><a class='logo-header' href='https://www.usgs.gov/' title='Home'><img class='img'  src='${logo}'  alt='Home' /></a><form action='https://www.usgs.gov/science-explorer-results' method='GET' id='search-box'><div class='fa-wrapper'><label for='se_search' class='only'>Search</label><input id='se_search' type='search' name='es' placeholder='Search'><button class='fa fa-search' type='submit'><span class='only'>Search</span></button></div></form></div></div></header>`,
    },
    {
      block: 'left',
      name: 'cToc',
      import: 'js.tools.shared.cToc.cToc',
      add: true,
      width: 380,
      height: 'auto',
      title: 'TOC',
      collapsible: true,
      blocks: [
        {
          block: 'center',
          name: 'cTocTabPanel',
          import: 'js.tools.shared.cTocTabPanel.cTocTabPanel',
          add: true,
          blocks: [
            {
              add: true,
              title: 'Contents',
              name: 'cTocContentsTab',
              import: 'js.tools.shared.cTocContentsTab.cTocContentsTab',
              blocks: [
                {
                  block: 'center',
                  add: true,
                  width: '100%',
                  height: '50%',
                  title: 'Dataset (Double click to open)',
                  name: 'cTocContainer',
                  import: 'js.tools.shared.cTocContainer.cTocContainer',
                  blocks: [
                    {
                      block: 'center',
                      name: 'cDatasetToc',
                      import: 'js.tools.shared.cDatasetToc.cDatasetToc',
                      add: true,
                      toolbar: {
                        position: 'top',
                        overflowMenu: false,
                        items: [
                          {
                            name: 'cRegionTool',
                            import: 'js.tools.shared.cRegionTool.cRegionTool',
                            add: false,
                            width: 200,
                          },
                          {
                            name: 'cExternalLinkButtonTool',
                            import: 'js.tools.shared.cExternalLinkButtonTool.cExternalLinkButtonTool',
                            add: true,
                            url: 'https://firedanger.cr.usgs.gov/apps/data-services-page',
                            tooltip: 'Fire Danger Data Services Page',
                            text: 'Data Services',
                            width: 100,
                          },
                        ],
                      },
                    },
                  ],
                },
                {
                  block: 'bottom',
                  add: true,
                  width: '100%',
                  height: '50%',
                  title: 'Layers',
                  name: 'cTocContainer',
                  import: 'js.tools.shared.cTocContainer.cTocContainer',
                  blocks: [
                    {
                      block: 'center',
                      name: 'cLayersToc',
                      import: 'js.tools.shared.cLayersToc.cLayersToc',
                      add: true,
                      toolbar: {
                        position: 'top',
                        overflowMenu: false,
                        items: [
                          {
                            name: 'cAddWMSLayerTool',
                            import: 'js.tools.shared.cAddWMSLayerTool.cAddWMSLayerTool',
                            add: true,
                            tooltip: 'Add WMS Layer',
                          },
                          {
                            name: 'cRemoveWMSLayerTool',
                            import: 'js.tools.shared.cRemoveWMSLayerTool.cRemoveWMSLayerTool',
                            add: true,
                            tooltip: 'Remove WMS Layer',
                          },
                        ],
                      },
                    },
                    {
                      name: 'cTransparency',
                      add: true,
                      import: 'js.tools.shared.cTransparency.cTransparency',
                      height: 100,
                      width: '90%',
                    },
                  ],
                },
              ],
            },
            {
              add: true,
              title: 'Legend',
              showBoundaries: true,
              name: 'cTocLegendTab',
              import: 'js.tools.shared.cTocLegendTab.cTocLegendTab',
            },
          ],
        },
      ],
    },
    {
      block: 'center',
      blocks: [
        {
          block: 'relative',
          name: 'cMapWindow',
          import: 'js.tools.shared.cMapWindow.cMapWindow',
          initialWinNum: 2,
          add: true,
          width: 580,
          height: 650,
          x: 410,
          y: 90,
          collapsible: true,
          toolbar: {
            position: 'top',
            add: true,
            overflowMenu: true,
            items: [
              {
                name: 'cZoomToRegionTool',
                title: '',
                add: true,
                import: 'js.tools.shared.cZoomToRegionTool.cZoomToRegionTool',
                cssClass: '',
                tooltip: 'Zoom to Region',
              },
              {
                name: 'cPanTool',
                title: '',
                add: true,
                import: 'js.tools.shared.cPanTool.cPanTool',
                cssClass: '',
                tooltip: 'Pan Tool',
              },
              {
                name: 'cExtentDragBoxTool',
                title: '',
                add: true,
                import: 'js.tools.shared.cExtentDragBoxTool.cExtentDragBoxTool',
                cssClass: '',
                tooltip: 'Zoom to Extent',
              },
              {
                name: 'cRevertExtentTool',
                title: '',
                add: true,
                import: 'js.tools.shared.cRevertExtentTool.cRevertExtentTool',
                cssClass: '',
                tooltip: 'Zoom to Previous',
              },
              {
                name: 'cIdentifyTool',
                title: '',
                add: true,
                import: 'js.tools.shared.cIdentifyTool.cIdentifyTool',
                cssClass: '',
                tooltip: 'Identify Tool',
              },
              {
                name: 'cDataDownloadBtn',
                add: true,
                import: 'js.tools.shared.cDataDownloadBtn.cDataDownloadBtn',
                tooltip: 'Data Download Tool',
              },
              {
                name: 'cSpacer',
                import: 'js.tools.shared.cSpacer.cSpacer',
                add: true,
              },
              {
                name: 'cDatePickerTool',
                import: 'js.tools.shared.cDatePickerTool.cDatePickerTool',
                title: '',
                add: true,
                cssClass: '',
                pickerType: 'combobox',
                tooltip: 'Select Date',
              },
              {
                name: 'cMapDownloadsTool',
                add: true,
                import: 'js.tools.shared.cMapDownloadsTool.cMapDownloadsTool',
                tooltip: '',
                items: [
                  {
                    name: 'cMenuLabel',
                    import: 'js.tools.shared.cMenuLabel.cMenuLabel',
                    add: true,
                    label: 'Download:',
                  },
                  {
                    name: 'cMapDownloadsMenuItem',
                    add: true,
                    import: 'js.tools.phenology.cMapDownloadsMenuItem.cMapDownloadsMenuItem',
                    type: 'wcs',
                    format: 'image/geotiff',
                    text: 'Geotiff (RAW)',
                  },
                  {
                    name: 'cMapDownloadsMenuItemPNG',
                    add: true,
                    import: 'js.tools.shared.cMapDownloadsMenuItemPNG.cMapDownloadsMenuItemPNG',
                    type: 'wms',
                    format: 'image/png',
                    text: 'Layers in display (PNG)',
                  },
                ],
              },
              {
                name: 'cMapLegendTool',
                add: true,
                import: 'js.tools.shared.cMapLegendTool.cMapLegendTool',
                tooltip: 'Toggle map legend',
                pressed: false,
              },
            ],
          },
          blocks: [
            {
              name: 'cMapPanel',
              import: 'js.tools.shared.cMapPanel.cMapPanel',
              add: true,
              addScaleLine: true,
              interactions: ['pan', 'zoom'],
              mouseCoordinates: {
                show: true,
                projection: 'EPSG:4326',
              },
              blocks: [
                {
                  name: 'cMapLegend',
                  block: 'relative',
                  import: 'js.tools.shared.cMapLegend.cMapLegend',
                  add: true,
                },
              ],
            },
          ],
        },
        {
          block: 'relative',
          name: 'cAddWMSLayerForm',
          import: 'js.tools.shared.cAddWMSLayerForm.cAddWMSLayerForm',
          add: true,
          width: 350,
          height: 105,
          x: 390,
          y: 222,
          title: 'Add WMS Layers',
        },
        {
          block: 'relative',
          name: 'cRemoveWMSLayerForm',
          import: 'js.tools.shared.cRemoveWMSLayerForm.cRemoveWMSLayerForm',
          add: true,
          width: 350,
          height: 105,
          x: 390,
          y: 222,
          title: 'Remove WMS Layers',
        },
      ],
    },
    {
      block: 'right',
      name: 'cTools',
      import: 'js.tools.shared.cTools.cTools',
      add: true,
      width: 265,
      height: 'auto',
      collapsible: true,
      collapsed: true,
      title: 'Tools',
      blocks: [
        {
          name: 'cDataDownload',
          add: true,
          addQueueLocation: '../downloads/addQueue.php',
          dateSelection: 'calendar',
          collapsible: true,
          collapsed: true,
          import: 'js.tools.shared.cDataDownload.cDataDownload',
          maxArea: 350000,
          noBoxText:
            'A box has not been drawn yet. <br><br> To draw one, please select the <br>Data Download tool <i class="fa fa-arrow-circle-o-down"></i><br>in the map window toolbar.',
          redirectButton: false,
          redirectText: `<div class="x-toolbar-text x-toolbar-text-default" id="redirectDownloadText"><b>NOTICE:</b><br> The extent of your download box<br>is too large. (Greater than 350000<br>square km).
          <br><br>Please select a smaller area of<br>interest or click <br><a href="https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/firedanger/download-tool/source_rasters/" target="_blank">here</a> to access complete datasets.</div>`,
        },
        {
          name: 'cMeasure',
          add: true,
          collapsible: true,
          collapsed: true,
          import: 'js.tools.firedanger.cMeasure.cMeasure',
          color: '#FF00DC',
        },
        {
          name: 'cSelectDatasetCategory',
          import: 'js.tools.firedanger.cSelectDatasetCategory.cSelectDatasetCategory',
          add: false,
          width: 230,
          height: 230,
        },
        {
          name: 'cFeatureInfoPanel',
          import: 'js.tools.firedanger.cFeatureInfoPanel.cFeatureInfoPanel',
          add: true,
          title: 'Feature Info',
          height: 250,
          width: '100%',
          collapsible: true,
          collapsed: true,
          cssClass: '',
        },
        {
          name: 'cSpatialLocking',
          import: 'js.tools.shared.cSpatialLocking.cSpatialLocking',
          add: true,
          title: 'Spatial Locking Tool',
          height: 250,
          collapsible: true,
          cssClass: '',
        },
        {
          name: 'cArrangeWindows',
          import: 'js.tools.shared.cArrangeWindows.cArrangeWindows',
          add: true,
          title: 'Arrange Windows Tool',
          height: 250,
          collapsible: true,
          cssClass: '',
        },
        {
          name: 'cSearch',
          add: true,
          import: 'js.tools.firedanger.cSearch.cSearch',
          width: 0,
          height: 0,
          zoomLevel: 5,
        },
      ],
    },
    {
      block: 'bottom',
      name: 'cFooter',
      import: 'js.tools.shared.cFooter.cFooter',
      add: true,
      width: 'auto',
      height: 80,
      cssClass: '',
      collapsible: false,
      collapsed: false,
      resizable: false,
      content:
        "<footer class='footer'><div class='tmp-container'><div class='footer-doi'><ul class='menu nav'><li class='first leaf menu-links menu-level-1'><a href='https://www.doi.gov/privacy'>DOI Privacy Policy</a></li><li class='leaf menu-links menu-level-1'><a href='https://www.usgs.gov/policies-and-notices'>Legal</a></li><li class='leaf menu-links menu-level-1'><a href='https://www.usgs.gov/accessibility-and-us-geological-survey'>Accessibility</a></li><li class='leaf menu-links menu-level-1'><a href='https://www.usgs.gov/sitemap.html'>Site Map</a></li><li class='last leaf menu-links menu-level-1'><a href='https://answers.usgs.gov/'>Contact USGS</a></li></ul></div><hr><div class='footer-doi'><ul class='menu nav'><li class='first leaf menu-links menu-level-1'><a href='https://www.doi.gov/'>U.S. Department of the Interior</a></li><li class='leaf menu-links menu-level-1'><a href='https://www.doioig.gov/'>DOI Inspector General</a></li><li class='leaf menu-links menu-level-1'><a href='https://www.whitehouse.gov/'>White House</a></li><li class='leaf menu-links menu-level-1'><a href='https://www.whitehouse.gov/omb/management/egov/'>E-gov</a></li><li class='leaf menu-links menu-level-1'><a href='https://www.doi.gov/pmb/eeo/no-fear-act'>No Fear Act</a></li><li class='last leaf menu-links menu-level-1'><a href='https://www.usgs.gov/foia'>FOIA</a></li></ul></div><div class='footer-social-links'><ul class='social'><li class='follow'>Follow</li><li class='twitter'><a href='https://twitter.com/usgs' target='_blank'><i class='fa fa-twitter-square'><span class='only'>Twitter</span></i></a></li><li class='facebook'><a href='https://facebook.com/usgeologicalsurvey' target='_blank'><i class='fa fa-facebook-square'><span class='only'>Facebook</span></i></a></li><li class='googleplus'><a href='https://plus.google.com/112624925658443863798/posts' target='_blank'><i class='fa fa-google-plus-square'><span class='only'>Google+</span></i></a></li><li class='github'><a href='https://github.com/usgs' target='_blank'><i class='fa fa-github'><span class='only'>GitHub</span></i></a></li><li class='flickr'><a href='https://flickr.com/usgeologicalsurvey' target='_blank'><i class='fa fa-flickr'><span class='only'>Flickr</span></i></a></li><li class='youtube'><a href='http://youtube.com/usgs' target='_blank'><i class='fa fa-youtube-play'><span class='only'>YouTube</span></i></a></li><li class='instagram'><a href='https://instagram.com/usgs' target='_blank'><i class='fa fa-instagram'><span class='only'>Instagram</span></i></a></li></ul></div></div></footer>",
    },
  ],
};
