import ConedLegend from '../../assets/images/legends/coned_tbdem_legend.png';

export const layers = {
  overlays: [
    {
      type: 'folder',
      title: 'Dataset',
      expanded: true,
      folder: [
        {
          type: 'folder',
          title: 'Central California',
          expanded: true,
          regionId: 'all',
          folder: [
            {
              type: 'layer',
              id: 'allSpatialCentCA',
              name: 'topo:Central_CA',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/centca_ab/{z}/{x}/{y}.pbf',
              },
              extent: [-13654382, 4081988, -13398986, 4554865],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'allCentCa',
              name: 'topo:CentCA_Topobathy_DEM_1m',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13654382, 4081988, -13398986, 4554865],
              loadOnly: false,
              display: true,
              active: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'Central California Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'allCentCaHS',
              name: 'topo:CentCA_Topobathy_DEM_1m_HS',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13654382, 4081988, -13398986, 4554865],
              loadOnly: false,
              display: true,
              active: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Chesapeake Bay',
          expanded: true,
          regionId: 'all',
          folder: [
            {
              type: 'layer',
              id: 'allSpatialChesapeake',
              name: 'topo:Chesapeake',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/chesapeake_bay_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-8704626, 4371716, -8347358, 4912763],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'allChesapeakeBay',
              name: 'topo:Chesapeake_Bay_Topobathy_DEM_1m_v2',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-8704626, 4371716, -8347358, 4912763],
              loadOnly: false,
              display: true,
              active: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'Chesapeake Bay Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'allChesapeakeBayHS',
              name: 'topo:Chesapeake_Bay_Topobathy_DEM_1m_v2_HS',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-8704626, 4371716, -8347358, 4912763],
              loadOnly: false,
              display: true,
              active: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Georgia',
          expanded: true,
          regionId: 'all',
          folder: [
            {
              type: 'layer',
              id: 'allSpatialGeorgia',
              name: 'topo:Chesapeake',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/georgia_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-9144896, 3558943, -8339305, 4379000],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'allGeorgia',
              name: 'topo:Georgia_CoNED_Topobathy_DEM_1m',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-9144896, 3558943, -8339305, 4379000],
              loadOnly: false,
              display: true,
              active: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'Georgia Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'allGeorgiaHS',
              name: 'topo:Georgia_CoNED_Topobathy_HS_1m',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-9144896, 3558943, -8339305, 4379000],
              loadOnly: false,
              display: true,
              active: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Juan de Fuca',
          expanded: true,
          regionId: 'all',
          folder: [
            {
              type: 'layer',
              id: 'allSpatialJuandeFuca',
              name: 'topo:Juan de Fuca',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/juan_de_fuca_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-13911861, 6113524, -13714894, 6197558],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'allJuandeFuca',
              name: 'topo:Juan_de_Fuca_CoNED_TBDEM_1m',
              title: 'TBDEM',
              source: {
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13911861, 6113524, -13714894, 6197558],
              loadOnly: false,
              display: true,
              active: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'Juan de Fuca Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'allJuandeFucaHS',
              name: 'topo:Juan_de_Fuca_CoNED_TBDEM_1m_hll',
              title: 'Hill Shade',
              source: {
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13911861, 6113524, -13714894, 6197558],
              loadOnly: false,
              display: true,
              active: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Lake Powell',
          expanded: true,
          regionId: 'all',
          folder: [
            {
              type: 'layer',
              id: 'allPowellSpatial',
              name: 'topo:Lake_Powell_TBDEM_Spatial_Metadata_webm',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/lake_powell_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-12425543, 4415771, -12260485, 4580353],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'allLakePowell',
              name: 'topo:Lake_Powell_Topobathy_DEM_1m',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-12425543, 4415771, -12260485, 4580353],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:6431',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_lake_powell_symbology',
                title: 'Lake Powell Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'allLakePowellHS',
              name: 'topo:Lake_Powell_Topobathy_DEM_hs',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-12425543, 4415771, -12260485, 4580353],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Majuro',
          expanded: true,
          regionId: 'all',
          folder: [
            {
              type: 'layer',
              id: 'allSpatialMajuro',
              name: 'topo:Majuro',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/Majuro_smd/{z}/{x}/{y}.pbf',
              },
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              extent: [19037972, 782835, 19084587, 807024],
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'allMajuro',
              name: 'topo:Majuro_Topobathy_DEM_1m',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [19037972, 782835, 19084587, 807024],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'Majuro Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'allMajuroHS',
              name: 'topo:Majuro_Topobathy_DEM_1m_HS',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [19037972, 782835, 19084587, 807024],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'New England',
          expanded: true,
          regionId: 'all',
          folder: [
            {
              type: 'layer',
              id: 'allSpatialNewEngland',
              name: 'topo:New_England',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/new_england_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-8325242, 4920959, -7765810, 5281386],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'allNewEnglandDEM',
              name: 'topo:New_England_Topobathy_DEM',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-8325242, 4920959, -7765810, 5281386],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'New England Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'allNewEnglandHS',
              name: 'topo:New_England_Topobathy_DEM_HS',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-8325242, 4920959, -7765810, 5281386],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'New Jersey and Delaware',
          expanded: true,
          regionId: 'all',
          folder: [
            {
              type: 'layer',
              id: 'allSpatialNjDelaware',
              name: 'topo:NJ_DE',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/nj_de_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-8478253, 4642112, -8207290, 5042260],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'allNewJerseyDE',
              name: 'topo:NJ_DE_Topobathy_DEM_v2',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-8478253, 4642112, -8207290, 5042260],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'New Jersey & Delaware Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'allNewJerseyDeHS',
              name: 'topo:NJ_DE_Topobathy_DEM_v2_hs',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-8478253, 4642112, -8207290, 5042260],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Northern California',
          expanded: true,
          regionId: 'all',
          folder: [
            {
              type: 'layer',
              id: 'allNorCalSpatial',
              name: 'topo:Nor_Cal',
              title: 'Spatial Metadata',
              source: {
                vectorTile:
                  'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/Northern_California_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-13867276, 4547010, -13630552, 5162865],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'allNorCal',
              name: 'topo:Northern_California_CoNED_TBDEM_1m_cog',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13867276, 4547010, -13630552, 5162865],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                title: 'Northern California Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'allNorCalHS',
              name: 'topo:Northern_California_CoNED_TBDEM_1m_HS_cog',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13867276, 4547010, -13630552, 5162865],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'North Carolina',
          expanded: true,
          regionId: 'all',
          folder: [
            {
              type: 'layer',
              id: 'allNorCarolinaSpatial',
              name: 'topo:Nor_Carolina',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/nc_tbdem_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-9082228, 3745724, -8339304, 4381182],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'allNorCarolina',
              name: 'topo:North_Carolina_CoNED_Topobathy_DEM_1m',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-9082228, 3745724, -8339304, 4381182],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                title: 'North Carolina Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'allNorCarolinaHS',
              name: 'topo:North_Carolina_CoNED_Topobathy_HS_1m',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-9082228, 3745724, -8339304, 4381182],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Northern Gulf of Mexico',
          expanded: true,
          regionId: 'all',
          folder: [
            {
              type: 'layer',
              id: 'allSpatialNGOM',
              name: 'topo:NGOM',
              title: 'Spatial Metadata',
              source: {
                vectorTile:
                  'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/north_gulf_of_mexico_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-10463888, 3337408, -9741756, 3639071],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'allNorthGulfMexicoDEM',
              name: 'topo:NGOM2_CoNED_Topobathy_DEM_1m_cog',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-10463888, 3337408, -9741756, 3639071],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'NGOM Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'allNorthGulfMexicoHS',
              name: 'topo:NGOM2_CoNED_Topobathy_HS_1m',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-10463888, 3337408, -9741756, 3639071],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Puget Sound',
          expanded: true,
          regionId: 'all',
          folder: [
            {
              type: 'layer',
              id: 'allSpatialPugetSound',
              name: 'topo:Puget',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/puget_sound_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-13715342, 5906289, -13578683, 6283657],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'allPugetSound',
              name: 'topo:Puget_Sound_CoNED_Topobathy_DEM_1m',
              title: 'TBDEM',
              source: {
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13715342, 5906289, -13578683, 6283657],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'Puget Sound Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'allPugetSoundHS',
              name: 'topo:Puget_Sound_CoNED_Topobathy_DEM_1m_hs',
              title: 'Hill Shade',
              source: {
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13715342, 5906289, -13578683, 6283657],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'San Francisco',
          expanded: true,
          regionId: 'all',
          folder: [
            {
              type: 'layer',
              id: 'allSpatialSF',
              name: 'topo:San_Francisco',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/sanfran_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-13725478, 4483875, -13564388, 4646469],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'allSanFrancisco2m',
              name: 'topo:San_Francisco_TopoBathy_Elevation_2m',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13725478, 4483875, -13564388, 4646469],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'San FranciscoTopobathy',
              },
            },
            {
              type: 'layer',
              id: 'allSanFrancisco2mHS',
              name: 'topo:San_Francisco_TopoBathy_Elevation_2m_hs',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13725478, 4483875, -13564388, 4646469],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Southern California',
          expanded: true,
          regionId: 'all',
          folder: [
            {
              type: 'layer',
              id: 'allSpatialSoCal',
              name: 'topo:SoCal',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/socal_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-13412970, 3827492, -13029544, 4104954],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'allSoCal',
              name: 'topo:Southern_California_Topobathy_DEM_1m',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13412970, 3827492, -13029544, 4104954],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'Southern California Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'allSoCalHS',
              name: 'topo:Southern_California_Topobathy_DEM_1m_HS',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13412970, 3827492, -13029544, 4104954],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'South Carolina',
          expanded: true,
          regionId: 'all',
          folder: [
            {
              type: 'layer',
              id: 'allSouthCarolinaSpatial',
              name: 'topo:South_Carolina',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/sc_tbdem_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-9082228, 3745724, -8339304, 4381182],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'allSouthCarolina',
              name: 'topo:South_Carolina_CoNED_Topobathy_DEM_1m',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-9082228, 3745724, -8339304, 4381182],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                title: 'South Carolina Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'allSouthCarolinaHS',
              name: 'topo:South_Carolina_CoNED_Topobathy_HS_1m',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-9082228, 3745724, -8339304, 4381182],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        // Region-Specified Layers
        {
          type: 'folder',
          title: 'Central California',
          expanded: true,
          regionId: 'california',
          folder: [
            {
              type: 'layer',
              id: 'spatialCentCA',
              name: 'topo:Central_CA',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/centca_ab/{z}/{x}/{y}.pbf',
              },
              extent: [-13654382, 4081988, -13398986, 4554865],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'centCa',
              name: 'topo:CentCA_Topobathy_DEM_1m',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13654382, 4081988, -13398986, 4554865],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              regionId: 'california',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'Central California Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'centCaHS',
              name: 'topo:CentCA_Topobathy_DEM_1m_HS',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13654382, 4081988, -13398986, 4554865],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              regionId: 'california',
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Georgia',
          expanded: true,
          regionId: 'CoastalSouthEast',
          folder: [
            {
              type: 'layer',
              id: 'CoastalSpatialGeorgia',
              name: 'topo:Chesapeake',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/georgia_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-9144896, 3558943, -8339305, 4379000],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'CoastalGeorgia',
              name: 'topo:Georgia_CoNED_Topobathy_DEM_1m',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-9144896, 3558943, -8339305, 4379000],
              loadOnly: false,
              display: true,
              active: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'Georgia Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'CoastalGeorgiaHS',
              name: 'topo:Georgia_CoNED_Topobathy_HS_1m',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-9144896, 3558943, -8339305, 4379000],
              loadOnly: false,
              display: true,
              active: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'North Carolina',
          expanded: true,
          regionId: 'CoastalSouthEast',
          folder: [
            {
              type: 'layer',
              id: 'NorCarolinaSpatial',
              name: 'topo:Nor_Carolina',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/nc_tbdem_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-9144896, 3558943, -8339305, 4379000],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'NorCarolina',
              name: 'topo:North_Carolina_CoNED_Topobathy_DEM_1m',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-9144896, 3558943, -8339305, 4379000],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                title: 'North Carolina Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'NorCarolinaHS',
              name: 'topo:North_Carolina_CoNED_Topobathy_HS_1m',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-9144896, 3558943, -8339305, 4379000],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'South Carolina',
          expanded: true,
          regionId: 'CoastalSouthEast',
          folder: [
            {
              type: 'layer',
              id: 'SouthCarolinaSpatial',
              name: 'topo:South_Carolina',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/sc_tbdem_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-9144896, 3558943, -8339305, 4379000],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'SouthCarolina',
              name: 'topo:South_Carolina_CoNED_Topobathy_DEM_1m',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-9144896, 3558943, -8339305, 4379000],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                title: 'South Carolina Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'SouthCarolinaHS',
              name: 'topo:South_Carolina_CoNED_Topobathy_HS_1m',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-9144896, 3558943, -8339305, 4379000],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Chesapeake Bay',
          expanded: true,
          regionId: 'northeast',
          folder: [
            {
              type: 'layer',
              id: 'spatialChesapeake',
              name: 'topo:Chesapeake',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/chesapeake_bay_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-8704626, 4371716, -8347358, 4912763],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'chesapeakeBay',
              name: 'topo:Chesapeake_Bay_Topobathy_DEM_1m_v2',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-8704626, 4371716, -8347358, 4912763],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'Chesapeake Bay Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'chesapeakeBayHS',
              name: 'topo:Chesapeake_Bay_Topobathy_DEM_1m_v2_HS',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-8704626, 4371716, -8347358, 4912763],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Lake Powell',
          expanded: true,
          regionId: 'powell',
          folder: [
            {
              type: 'layer',
              id: 'powellSpatial',
              name: 'topo:Lake_Powell_TBDEM_Spatial_Metadata_webm',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/lake_powell_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-12425543, 4415771, -12260485, 4580353],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'lakePowell',
              name: 'topo:Lake_Powell_Topobathy_DEM_1m',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-12425543, 4415771, -12260485, 4580353],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_lake_powell_symbology',
                title: 'Lake Powell Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'lakePowellHS',
              name: 'topo:Lake_Powell_Topobathy_DEM_hs',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-12425543, 4415771, -12260485, 4580353],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Majuro',
          expanded: true,
          regionId: 'majuro',
          folder: [
            {
              type: 'layer',
              id: 'spatialMajuro',
              name: 'topo:Majuro',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/Majuro_smd/{z}/{x}/{y}.pbf',
              },
              extent: [19037972, 782835, 19084587, 807024],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'majuro',
              name: 'topo:Majuro_Topobathy_DEM_1m',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [19037972, 782835, 19084587, 807024],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'Majuro Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'majuroHS',
              name: 'topo:Majuro_Topobathy_DEM_1m_HS',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [19037972, 782835, 19084587, 807024],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'New England',
          expanded: true,
          regionId: 'northeast',
          folder: [
            {
              type: 'layer',
              id: 'spatialNewEngland',
              name: 'topo:New_England',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/new_england_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-8325242, 4920959, -7765810, 5281386],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'newEnglandDEM',
              name: 'topo:New_England_Topobathy_DEM',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-8325242, 4920959, -7765810, 5281386],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'New England Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'newEnglandHS',
              name: 'topo:New_England_Topobathy_DEM_HS',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-8325242, 4920959, -7765810, 5281386],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'New Jersey and Delaware',
          expanded: true,
          regionId: 'northeast',
          folder: [
            {
              type: 'layer',
              id: 'spatialNjDelaware',
              name: 'topo:NJ_DE',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/nj_de_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-8478253, 4642112, -8207290, 5042260],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'newJerseyDE',
              name: 'topo:NJ_DE_Topobathy_DEM_v2',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-8478253, 4642112, -8207290, 5042260],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'New Jersey & Delaware Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'newJerseyDeHS',
              name: 'topo:NJ_DE_Topobathy_DEM_v2_hs',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-8478253, 4642112, -8207290, 5042260],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Northern California',
          expanded: true,
          regionId: 'california',
          folder: [
            {
              type: 'layer',
              id: 'spatialNorCal',
              name: 'topo:Nor_Cal',
              title: 'Spatial Metadata',
              source: {
                vectorTile:
                  'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/Northern_California_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-13867276, 4547010, -13630552, 5162865],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'norCal',
              name: 'topo:Northern_California_CoNED_TBDEM_1m_cog',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13867276, 4547010, -13630552, 5162865],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                title: 'Northern California Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'norCalHS',
              name: 'topo:Northern_California_CoNED_TBDEM_1m_HS_cog',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13867276, 4547010, -13630552, 5162865],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Northern Gulf of Mexico',
          expanded: true,
          regionId: 'ngom',
          folder: [
            {
              type: 'layer',
              id: 'spatialNGOM',
              name: 'topo:NGOM',
              title: 'Spatial Metadata',
              source: {
                vectorTile:
                  'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/north_gulf_of_mexico_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-10463888, 3337408, -9741756, 3639071],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'northGulfMexicoDEM',
              name: 'topo:NGOM2_CoNED_Topobathy_DEM_1m_cog',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-10463888, 3337408, -9741756, 3639071],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'NGOM Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'northGulfMexicoHS',
              name: 'topo:NGOM2_CoNED_Topobathy_HS_1m',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-10463888, 3337408, -9741756, 3639071],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Puget Sound',
          expanded: true,
          regionId: 'PacificNorthwest',
          folder: [
            {
              type: 'layer',
              id: 'spatialPugetSound',
              name: 'topo:Puget',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/puget_sound_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-13715342, 5906289, -13578683, 6283657],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'pugetSound',
              name: 'topo:Puget_Sound_CoNED_Topobathy_DEM_1m',
              title: 'TBDEM',
              source: {
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13715342, 5906289, -13578683, 6283657],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'Puget Sound Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'pugetSoundHS',
              name: 'topo:Puget_Sound_CoNED_Topobathy_DEM_1m_hs',
              title: 'Hill Shade',
              source: {
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13715342, 5906289, -13578683, 6283657],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Juan de Fuca',
          expanded: true,
          regionId: 'PacificNorthwest',
          folder: [
            {
              type: 'layer',
              id: 'SpatialJuandeFuca',
              name: 'topo:Juan de Fuca',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/juan_de_fuca_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-13911861, 6113524, -13714894, 6197558],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'JuandeFuca',
              name: 'topo:Juan_de_Fuca_CoNED_TBDEM_1m',
              title: 'TBDEM',
              source: {
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13911861, 6113524, -13714894, 6197558],
              loadOnly: false,
              display: true,
              active: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'Juan de Fuca Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'JuandeFucaHS',
              name: 'topo:Juan_de_Fuca_CoNED_TBDEM_1m_hll',
              title: 'Hill Shade',
              source: {
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13911861, 6113524, -13714894, 6197558],
              loadOnly: false,
              display: true,
              active: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
            },
          ],
        },
        {
          type: 'folder',
          title: 'San Francisco',
          expanded: true,
          regionId: 'california',
          folder: [
            {
              type: 'layer',
              id: 'spatialSF',
              name: 'topo:San_Francisco',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/sanfran_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-13725478, 4483875, -13564388, 4646469],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'sanFrancisco2m',
              name: 'topo:San_Francisco_TopoBathy_Elevation_2m',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13725478, 4483875, -13564388, 4646469],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              regionId: 'california',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'San Francisco Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'sanFrancisco2mHS',
              name: 'topo:San_Francisco_TopoBathy_Elevation_2m_hs',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13725478, 4483875, -13564388, 4646469],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              regionId: 'california',
            },
          ],
        },
        {
          type: 'folder',
          title: 'Southern California',
          expanded: true,
          regionId: 'california',
          folder: [
            {
              type: 'layer',
              id: 'spatialSoCal',
              name: 'topo:SoCal',
              title: 'Spatial Metadata',
              source: {
                vectorTile: 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/data/viewer/vector_tiles/socal_smd/{z}/{x}/{y}.pbf',
              },
              extent: [-13412970, 3827492, -13029544, 4104954],
              loadOnly: false,
              display: false,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              featureInfo: {},
            },
            {
              type: 'layer',
              id: 'soCal',
              name: 'topo:Southern_California_Topobathy_DEM_1m',
              title: 'TBDEM',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13412970, 3827492, -13029544, 4104954],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              regionId: 'california',
              featureInfo: {
                GRAY_INDEX: {
                  displayName: 'Pixel Value',
                  displayValue: null,
                  value: null,
                  mapValues: [],
                },
              },
              legend: {
                style: 'topo_dem_color_symbology',
                customImageUrl: ConedLegend,
                title: 'Southern California Topobathy',
              },
            },
            {
              type: 'layer',
              id: 'soCalHS',
              name: 'topo:Southern_California_Topobathy_DEM_1m_HS',
              title: 'Hill Shade',
              source: {
                gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
                wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
                wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
                wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
              },
              extent: [-13412970, 3827492, -13029544, 4104954],
              loadOnly: false,
              display: true,
              mask: false,
              transparency: true,
              srs: 'EPSG:3857',
              regionId: 'california',
            },
          ],
        },
        {
          type: 'layer',
          name: 'topo:Viewer_Layers_Extent_20200325',
          description: 'Shapefile layer for cDataDownload',
          source: {
            wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
          },
          loadOnly: true,
          display: false,
          mask: false,
          transparency: false,
          zIndex: 1,
          srs: 'EPSG:3857',
        },
      ],
    },
  ],
  boundaries: [
    {
      type: 'folder',
      title: 'Boundaries',
      expanded: true,
      folder: [
        {
          type: 'layer',
          id: 'natBoundary',
          name: 'topo:national_boundary__nocoast_webmer',
          title: 'National Border',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
          },
          loadOnly: false,
          display: true,
          mask: false,
          srs: 'EPSG:3857',
        },
        {
          type: 'layer',
          id: 'natStates',
          name: 'topo:state_boundary_webmer',
          title: 'State Borders (National Atlas)',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
          },
          loadOnly: false,
          display: true,
          mask: false,
          srs: 'EPSG:3857',
        },
        {
          type: 'layer',
          id: 'natCounties',
          name: 'topo:county_boundary_webmer',
          title: 'County Boundaries (National Atlas)',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
          },
          loadOnly: false,
          display: true,
          mask: false,
          srs: 'EPSG:3857',
        },
        {
          type: 'layer',
          id: 'allCountyBorder',
          name: 'topo:uscounties',
          title: 'Counties',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
          },
          loadOnly: true,
          display: false,
          mask: false,
          zIndex: 0,
          panelQuery: true,
          srs: 'EPSG:3857',
          featureInfo: {
            COUNTY: {
              displayName: 'County Name',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            STATE: {
              displayName: 'State',
              displayValue: null,
              value: null,
              mapValues: [],
            },
          },
        },
      ],
    },
  ],
  baselayers: [
    {
      type: 'folder',
      title: 'Base Layers',
      expanded: true,
      folder: [
        {
          type: 'layer',
          name: 'osm_0',
          title: 'Standard OpenStreetMap',
          description: '',
          loadOnly: false,
          display: true,
          mask: false,
          srs: 'EPSG:3857',
          loaded: 'true',
          brand: 'osm',
          source: {
            url: 'https://osm-{1-4}.gs.mil/tiles/default/{z}/{x}/{y}.png',
          },
          comments: '',
        },
      ],
    },
  ],
};
