import logo from '../../assets/images/logo.png';

export const template = {
  theme: 'ExtJSNeptune',
  cssFallback: true,
  analytics: {
    matomo: {
      baseUrl: '//edcintl.cr.usgs.gov/piwik/',
      id: '16',
    },
    google: {
      id: 'UA-22121470-19',
    },
  },
  blocks: [
    {
      block: 'top',
      name: 'cHeader',
      import: 'js.tools.shared.cHeader.cHeader',
      tile: 'CoNED Viewer',
      add: true,
      width: 'auto',
      height: 70,
      cssClass: '',
      collapsible: true,
      content: `<header id="navbar" class="header-nav" role="banner"><div class="tmp-container"><div class="header-search"><a class="logo-header" href="https://www.usgs.gov/" title="Home"><img class="img" src="${logo}" alt="Home" /></a><span class= "x-panel-header-text-container-default" style='float: left; margin-top: 1em; margin-left: 1%; overflow: visible; font-size: 30px'>CoNED Viewer</b></span><form action="https://www.usgs.gov/science-explorer-results" method="GET" id="search-box"><div class="fa-wrapper"><label for="se_search" class="only">Search</label><input id="se_search" type="search" name="es" placeholder="Search"><button class="fa fa-search" type="submit"><span class="only">Search</span></button></div></form></div></div></header>`,
    },
    {
      block: 'left',
      name: 'cTOCDesktopLike',
      import: 'js.tools.shared.cTOCDesktopLike.cTOCDesktopLike',
      add: false,
      width: 320,
      height: 'auto',
      title: 'TOC',
      collapsible: true,
      collapsed: false,
      blocks: [
        {
          block: 'top',
          name: 'cTocContainer',
          import: 'js.tools.shared.cTocContainer.cTocContainer',
          width: '100%',
          height: 'auto',
          add: true,
          blocks: [
            {
              name: 'cDefaultToc',
              import: 'js.tools.shared.cDefaultToc.cDefaultToc',
              add: true,
              width: '100%',
              height: 'auto',
              titleLength: 30,
              hideDatePicker: true,
            },
          ],
        },
        {
          name: 'cTransparency',
          add: true,
          import: 'js.tools.shared.cTransparency.cTransparency',
          height: 100,
          width: '90%',
        },
      ],
    },
    {
      block: 'left',
      name: 'cToc',
      import: 'js.tools.shared.cToc.cToc',
      add: true,
      width: 380,
      height: 'auto',
      title: 'TOC',
      collapsible: true,
      blocks: [
        {
          block: 'center',
          name: 'cTocTabPanel',
          import: 'js.tools.shared.cTocTabPanel.cTocTabPanel',
          add: true,
          blocks: [
            {
              add: true,
              title: 'Contents',
              name: 'cTocContentsScrollTab',
              import: 'js.tools.shared.cTocContentsScrollTab.cTocContentsScrollTab',
              blocks: [
                {
                  height: 100,
                  name: 'cDefaultToc',
                  import: 'js.tools.shared.cDefaultToc.cDefaultToc',
                  add: true,
                  titleLength: 30,
                  hideDatePicker: true,
                },
                {
                  name: 'cTransparency',
                  add: true,
                  import: 'js.tools.shared.cTransparency.cTransparency',
                  height: 100,
                  width: '90%',
                },
              ],
              toolbar: {
                position: 'top',
                overflowMenu: false,
                items: [
                  {
                    name: 'cRegionTool',
                    import: 'js.tools.shared.cRegionTool.cRegionTool',
                    add: true,
                    width: 150,
                  },
                  {
                    name: 'cSpacer',
                    import: 'js.tools.shared.cSpacer.cSpacer',
                    add: true,
                  },
                  {
                    name: 'cAddWMSLayerTool',
                    import: 'js.tools.shared.cAddWMSLayerTool.cAddWMSLayerTool',
                    add: true,
                    tooltip: 'Add WMS Layer',
                  },
                  {
                    name: 'cRemoveWMSLayerTool',
                    import: 'js.tools.shared.cRemoveWMSLayerTool.cRemoveWMSLayerTool',
                    add: true,
                    tooltip: 'Remove WMS Layer',
                  },
                ],
              },
            },
            {
              add: true,
              title: 'Legend',
              name: 'cTocLegendTab',
              import: 'js.tools.shared.cTocLegendTab.cTocLegendTab',
              autoScroll: true,
            },
          ],
        },
      ],
    },
    {
      block: 'center',
      name: 'cMapWindow',
      import: 'js.tools.shared.cMapWindow.cMapWindow',
      add: true,
      collapsible: false,
      hideTitle: true,
      toolbar: {
        position: 'top',
        add: true,
        overflowMenu: true,
        items: [
          {
            name: 'cZoomToRegionTool',
            title: '',
            add: true,
            import: 'js.tools.shared.cZoomToRegionTool.cZoomToRegionTool',
            cssClass: '',
            tooltip: 'Zoom to Region',
          },
          {
            name: 'cPanTool',
            title: '',
            add: true,
            import: 'js.tools.shared.cPanTool.cPanTool',
            cssClass: '',
            tooltip: 'Pan Tool',
          },
          {
            name: 'cExtentDragBoxTool',
            title: '',
            add: true,
            import: 'js.tools.shared.cExtentDragBoxTool.cExtentDragBoxTool',
            cssClass: '',
            tooltip: 'Zoom to Extent',
          },
          {
            name: 'cRevertExtentTool',
            title: '',
            add: true,
            import: 'js.tools.shared.cRevertExtentTool.cRevertExtentTool',
            cssClass: '',
            tooltip: 'Zoom to Previous',
          },
          {
            name: 'cIdentifyTool',
            title: '',
            add: true,
            import: 'js.tools.shared.cIdentifyTool.cIdentifyTool',
            cssClass: '',
            tooltip: 'Identify Tool',
          },
          {
            name: 'cDataDownloadBtn',
            add: true,
            import: 'js.tools.mrlc.cDataDownloadBtn.cDataDownloadBtn',
            tooltip: 'Open Data Download Tool',
          },
          {
            name: 'cSpacer',
            import: 'js.tools.shared.cSpacer.cSpacer',
            add: true,
          },
          {
            name: 'cMapLegendTool',
            add: true,
            import: 'js.tools.shared.cMapLegendTool.cMapLegendTool',
            tooltip: 'Toggle map legend',
            pressed: false,
          },
        ],
      },
      blocks: [
        {
          name: 'cMapPanel',
          import: 'js.tools.shared.cMapPanel.cMapPanel',
          add: true,
          maxZoom: 15,
          interactions: ['pan', 'zoom'],
          mouseCoordinates: {
            show: true,
            projection: 'EPSG:4326',
          },
          blocks: [
            {
              name: 'cMapLegend',
              block: 'relative',
              import: 'js.tools.shared.cMapLegend.cMapLegend',
              add: true,
            },
          ],
        },
      ],
    },
    {
      block: 'right',
      name: 'cTools',
      import: 'js.tools.shared.cTools.cTools',
      add: true,
      width: 250,
      height: 'auto',
      collapsible: true,
      collapsed: true,
      title: 'Tools',
      blocks: [
        {
          name: 'cDataDownload',
          add: true,
          collapsible: true,
          collapsed: true,
          import: 'js.tools.mrlc.cDataDownload.cDataDownload',
          addQueueLocation: '../downloads/addQueue.php',
          redirectText: `<div class="x-toolbar-text x-toolbar-text-default" id="redirectDownloadText"><b>NOTICE:</b><br> The extent of your download box<br>is too large. (Greater than 10,000<br>square km).
          <br><br>Please select a smaller area of<br>interest or go to:<br><a href="https://topotools.cr.usgs.gov/topobathy_viewer/dwndata.htm" target="_blank">https://topotools.cr.usgs.gov/topobathy_viewer/dwndata.htm</a><br>to download a complete<br>dataset.</div>`,
          maxArea: 10000,
          noBoxText:
            'A box has not been drawn yet. <br><br> To draw one, please select the <br>Data Download tool <i class="fa fa-arrow-circle-o-down"></i><br>in the map window toolbar.',
        },
        {
          name: 'cFeatureInfoPanel',
          import: 'js.tools.shared.cFeatureInfoPanel.cFeatureInfoPanel',
          add: true,
          title: 'Feature Info',
          height: 585,
          width: '100%',
          collapsible: true,
          collapsed: true,
          cssClass: '',
          replaceNullWithNoData: true,
        },
        {
          name: 'cArrangeWindows',
          import: 'js.tools.shared.cArrangeWindows.cArrangeWindows',
          add: false,
          title: 'Arrange Windows Tool',
          height: 250,
          collapsible: true,
          cssClass: '',
          hideFromDom: true,
        },
      ],
    },
  ],
};
