import logo from '../../assets/images/logo.png';
import rangelandLogo from '../../assets/images/shrubland/logo.png';
import barGraph from '../../assets/images/bar_graph_black.png';
import lineChart from '../../assets/images/line_chart.png';
import graphImage from '../../assets/images/shrubland/graphingWindow.png';

export const template = {
  theme: 'ExtJSNeptune',
  cssFallback: true,
  analytics: {
    matomo: {
      baseUrl: '//edcintl.cr.usgs.gov/piwik/',
      id: '8',
    },
    google: {
      id: 'UA-127886240-1',
    },
  },
  blocks: [
    {
      block: 'top',
      name: 'cHeader',
      import: 'js.tools.shared.cHeader.cHeader',
      title: 'MRLC Rangeland Viewer',
      add: true,
      width: 'auto',
      height: 70,
      cssClass: '',
      collapsible: true,
      content: `<head><meta charset="UTF-8"><title>MRLC Rangeland Viewer</title></head><div style="height: 100%" class="header-nav"><div class="tmp-container"><a class="logo-header" href="https://www.usgs.gov/" title="Home"><img style="height: 62px" class="img"  src="${logo}"  alt="Home" /><img style="height: 62px" class="img"  src="${rangelandLogo}"  alt="Home" /></a><span class="x-panel-header-text-container-default" style="float: left; margin-top: 1em; margin-left: 1%; overflow: visible; font-size: 30px">MRLC Rangeland Viewer</span></div></div>`,
    },
    {
      block: 'left',
      name: 'cTOCDesktopLike',
      import: 'js.tools.shared.cTOCDesktopLike.cTOCDesktopLike',
      add: false,
      width: 370,
      height: 'auto',
      title: 'TOC',
      blocks: [
        {
          block: 'top',
          name: 'cTocContainer',
          import: 'js.tools.shared.cTocContainer.cTocContainer',
          width: '100%',
          height: 'auto',
          add: true,
          blocks: [
            {
              name: 'cDefaultToc',
              import: 'js.tools.shared.cDefaultToc.cDefaultToc',
              add: true,
              width: '100%',
              height: 'auto',
              titleLength: 20,
            },
          ],
        },
        {
          name: 'cTransparency',
          import: 'js.tools.shared.cTransparency.cTransparency',
          add: true,
          height: 100,
          width: '90%',
        },
      ],
      toolbar: {
        position: 'top',
        overflowMenu: false,
        items: [
          {
            name: 'cRegionTool',
            import: 'js.tools.shared.cRegionTool.cRegionTool',
            add: false,
            width: 200,
          },
        ],
      },
    },
    {
      block: 'left',
      name: 'cToc',
      import: 'js.tools.shared.cToc.cToc',
      add: true,
      width: 405,
      height: 'auto',
      title: 'TOC',
      collapsible: true,
      blocks: [
        {
          block: 'center',
          name: 'cTocTabPanel',
          import: 'js.tools.shared.cTocTabPanel.cTocTabPanel',
          add: true,
          blocks: [
            {
              add: true,
              title: 'Contents',
              name: 'cTocContentsTab',
              import: 'js.tools.shared.cTocContentsTab.cTocContentsTab',
              blocks: [
                {
                  block: 'center',
                  add: true,
                  width: '100%',
                  height: '65%',
                  title: 'Dataset (Double click to open)',
                  name: 'cTocContainer',
                  import: 'js.tools.shared.cTocContainer.cTocContainer',
                  blocks: [
                    {
                      block: 'center',
                      name: 'cDatasetToc',
                      import: 'js.tools.shared.cDatasetToc.cDatasetToc',
                      titleLength: 41,
                      subfolders: true,
                      add: true,
                    },
                  ],
                },
                {
                  block: 'bottom',
                  add: true,
                  width: '100%',
                  height: '35%',
                  title: 'Layers',
                  name: 'cTocContainer',
                  import: 'js.tools.shared.cTocContainer.cTocContainer',
                  blocks: [
                    {
                      block: 'center',
                      name: 'cLayersToc',
                      import: 'js.tools.shared.cLayersToc.cLayersToc',
                      titleLength: 41,
                      add: true,
                      toolbar: {
                        position: 'top',
                        overflowMenu: false,
                        items: [
                          {
                            name: 'cAddWMSLayerTool',
                            import: 'js.tools.shared.cAddWMSLayerTool.cAddWMSLayerTool',
                            add: true,
                            tooltip: 'Add WMS Layer',
                          },
                          {
                            name: 'cRemoveWMSLayerTool',
                            import: 'js.tools.shared.cRemoveWMSLayerTool.cRemoveWMSLayerTool',
                            add: true,
                            tooltip: 'Remove WMS Layer',
                          },
                          {
                            name: 'cPopupButtonTool',
                            add: true,
                            import: 'js.tools.shrubland.cPopupButtonTool.cPopupButtonTool',
                            popupTitle: 'Notice to users',
                            popupBody: `RCMAP 06012021 dated versions of time-series cover replace the 06182020 versions on the MRLC <a href="https://www.mrlc.gov/data">Data</a> and <a href="https://www.mrlc.gov/rangeland-viewer/">Rangeland Viewer</a> pages. 06182020 dated RCMAP products will remain available on a <a href="https://www.sciencebase.gov/catalog/item/5ebaabd682ce25b513617fb5">ScienceBase page</a>, however, users are encouraged to use the most recent release. <br><br> New to MRLC Rangeland Viewer: A graphing tool which plots yearly zonal means by component across various boundary types (pastures, watersheds, etc.). A tutorial for use is available in the 'Help' tab. <br><br> <img src="${graphImage}" style='display:block; width: 100%; text-align:center;'>`,
                            popupHeight: 520,
                            tooltip: 'Notice',
                            alwaysShow: true,
                            useOkButtons: false,
                            icon: 'fa-exclamation-triangle',
                            width: 30,
                          },
                        ],
                      },
                    },
                  ],
                },
              ],
            },
            {
              add: true,
              title: 'Legend',
              showBoundaries: true,
              name: 'cTocLegendTab',
              import: 'js.tools.shared.cTocLegendTab.cTocLegendTab',
            },
            {
              add: true,
              title: 'Help',
              name: 'cHelpTab',
              import: 'js.tools.shrubland.cHelpTab.cHelpTab',
              blocks: [
                {
                  name: 'cHelpContents',
                  import: 'js.tools.shrubland.cHelpContents.cHelpContents',
                  add: true,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      block: 'center',
      blocks: [
        {
          block: 'relative',
          name: 'cAddWMSLayerForm',
          import: 'js.tools.shared.cAddWMSLayerForm.cAddWMSLayerForm',
          add: true,
          width: 350,
          height: 110,
          x: 390,
          y: 425,
          title: 'Add WMS Layers',
        },
        {
          block: 'relative',
          name: 'cRemoveWMSLayerForm',
          import: 'js.tools.shared.cRemoveWMSLayerForm.cRemoveWMSLayerForm',
          add: true,
          width: 350,
          height: 105,
          x: 390,
          y: 550,
          title: 'Remove WMS Layers',
        },
        {
          block: 'relative',
          name: 'cMapWindow',
          import: 'js.tools.shared.cMapWindow.cMapWindow',
          add: true,
          width: 580,
          height: 650,
          x: 410,
          y: 90,
          collapsible: true,
          toolbar: {
            position: 'top',
            overflowMenu: true,
            items: [
              {
                name: 'cZoomToRegionTool',
                import: 'js.tools.shared.cZoomToRegionTool.cZoomToRegionTool',
                title: '',
                add: false,
                cssClass: '',
                tooltip: 'Zoom to Region',
              },
              {
                name: 'cPanTool',
                import: 'js.tools.shared.cPanTool.cPanTool',
                title: '',
                add: true,
                cssClass: '',
                tooltip: 'Pan Tool',
              },
              {
                name: 'cExtentDragBoxTool',
                import: 'js.tools.shared.cExtentDragBoxTool.cExtentDragBoxTool',
                title: '',
                add: true,
                cssClass: '',
                tooltip: 'Zoom to Extent',
              },
              {
                name: 'cRevertExtentTool',
                import: 'js.tools.shared.cRevertExtentTool.cRevertExtentTool',
                title: '',
                add: true,
                cssClass: '',
                tooltip: 'Zoom to Previous',
              },
              {
                name: 'cIdentifyTool',
                import: 'js.tools.shared.cIdentifyTool.cIdentifyTool',
                title: '',
                add: true,
                cssClass: '',
                tooltip: 'Identify Tool',
              },
              {
                name: 'cDataDownloadBtn',
                add: true,
                import: 'js.tools.shrubland.cDataDownloadBtn.cDataDownloadBtn',
                tooltip: 'Data Download Tool',
              },
              {
                name: 'cGraphTool',
                title: '',
                add: true,
                import: 'js.tools.shared.cGraphTool.cGraphTool',
                cssClass: '',
                pressed: true,
                tooltip: 'Graph Tool',
                layers: [
                  {
                    id: 'shapefile_USFS_BLM_Allotments_wm',
                    featureInfo: [
                      {
                        propertyName: 'POLY_NAME',
                        type: 'display',
                      },
                    ],
                  },
                  {
                    id: 'shapefile_BLM_USFS_Pastures',
                    featureInfo: [
                      {
                        propertyName: 'POLY_NAME',
                        type: 'display',
                      },
                    ],
                  },
                  {
                    id: 'shapefile_HUC_level_6',
                    featureInfo: [
                      {
                        propertyName: 'POLY_NAME',
                        type: 'display',
                      },
                    ],
                  },
                  {
                    id: 'shapefile_HUC_level_8',
                    featureInfo: [
                      {
                        propertyName: 'POLY_NAME',
                        type: 'display',
                      },
                    ],
                  },
                  {
                    id: 'shapefile_HUC_level_10',
                    featureInfo: [
                      {
                        propertyName: 'POLY_NAME',
                        type: 'display',
                      },
                    ],
                  },
                  {
                    id: 'shapefile_BLM_Priority_Habitat_Area',
                    featureInfo: [
                      {
                        propertyName: 'POLY_NAME',
                        type: 'display',
                      },
                    ],
                  },
                  {
                    id: 'shapefile_BLM_herd_managment_area',
                    featureInfo: [
                      {
                        propertyName: 'POLY_NAME',
                        type: 'display',
                      },
                    ],
                  },
                ],
              },
              {
                name: 'cSpacer',
                import: 'js.tools.shared.cSpacer.cSpacer',
                add: true,
              },
              {
                name: 'cDatasetExplorerTool',
                import: 'js.tools.shared.cDatasetExplorerTool.cDatasetExplorerTool',
                title: '',
                add: false,
                cssClass: '',
                tooltip: 'Select displayed layer',
              },
              {
                name: 'cDatePickerTool',
                import: 'js.tools.shared.cDatePickerTool.cDatePickerTool',
                title: '',
                add: true,
                cssClass: '',
                pickerType: 'combobox',
                tooltip: 'Select Date',
              },
              {
                name: 'cMapLegendTool',
                import: 'js.tools.shared.cMapLegendTool.cMapLegendTool',
                add: true,
                tooltip: 'Toggle map legend',
                pressed: false,
              },
            ],
          },
          blocks: [
            {
              block: 'top',
              name: 'cMapPanel',
              import: 'js.tools.shared.cMapPanel.cMapPanel',
              add: true,
              interactions: ['pan', 'zoom'],
              mouseCoordinates: {
                show: true,
                projection: 'EPSG:4326',
              },
              blocks: [
                {
                  name: 'cMapLegend',
                  import: 'js.tools.shared.cMapLegend.cMapLegend',
                  block: 'relative',
                  add: true,
                },
              ],
            },
            {
              block: 'relative',
              title: 'Zonal Mean Plot',
              name: 'cMapWindowChartArea',
              width: 850,
              height: 500,
              add: true,
              import: 'js.tools.shared.cMapWindowChartArea.cMapWindowChartArea',
              collapsible: true,
              blocks: [
                {
                  block: 'center',
                  name: 'cChartContainer',
                  import: 'js.tools.shared.cChartContainer.cChartContainer',
                  add: true,
                  isDefault: true,
                  closable: false,
                  toolbar: {
                    overflowMenu: true,
                    items: [
                      {
                        name: 'cZonesCombo',
                        import: 'js.tools.shared.cZonesCombo.cZonesCombo',
                        title: '',
                        add: true,
                        tooltip: 'Select Zone',
                        saveSelection: true,
                        allowAll: true,
                        width: 197,
                      },
                      {
                        name: 'cSpacer',
                        import: 'js.tools.shared.cSpacer.cSpacer',
                        add: true,
                      },
                      {
                        name: 'cDockChart',
                        import: 'js.tools.shared.cDockChart.cDockChart',
                        title: '',
                        add: false,
                        tooltip: 'Dock Window',
                        saveSelection: true,
                        dockedState: 'docked',
                      },
                      {
                        name: 'cChartToolsMenu',
                        import: 'js.tools.shared.cChartToolsMenu.cChartToolsMenu',
                        title: '',
                        height: 24,
                        width: 45,
                        add: true,
                        tooltip: 'Chart Tools',
                        items: [
                          {
                            name: 'cMenuLabel',
                            add: true,
                            label: 'Download:',
                            import: 'js.tools.shared.cMenuLabel.cMenuLabel',
                          },
                          {
                            name: 'cExportPNG',
                            import: 'js.tools.shared.cExportPNG.cExportPNG',
                            title: 'PNG',
                            add: true,
                            cssClass: '',
                            tooltip: 'Save chart as PNG',
                          },
                          {
                            name: 'cExportCSV',
                            import: 'js.tools.shared.cExportCSV.cExportCSV',
                            title: 'CSV',
                            add: true,
                            cssClass: '',
                            tooltip: 'Export data as CSV',
                          },
                        ],
                      },
                      {
                        name: 'cChartLegend',
                        import: 'js.tools.shared.cChartLegend.cChartLegend',
                        title: '',
                        add: true,
                        cssClass: '',
                        tooltip: 'Show Chart Legend',
                        pressed: true,
                        legendPosition: 'bottom',
                      },
                    ],
                  },
                },
              ],
            },
          ],
        },
      ],
    },
    {
      block: 'right',
      name: 'cTools',
      import: 'js.tools.shared.cTools.cTools',
      add: true,
      width: 325,
      height: 'auto',
      collapsible: true,
      collapsed: false,
      title: 'Tools',
      blocks: [
        {
          name: 'cDataDownload',
          add: true,
          collapsible: true,
          collapsed: true,
          import: 'js.tools.shrubland.cDataDownload.cDataDownload',
          addQueueLocation: '/viewerRest/addQueue.php',
          redirectText: `<b>NOTICE:</b><br> The extent of your download box<br>is too large. (Greater than 350000 <br>square km).
          <br><br>Please select a smaller area of<br>interest or go <a href="/data" target="_blank">here</a><br>to download a complete<br>dataset.`,
          maxArea: 350000,
          noBoxText:
            'A box has not been drawn yet. <br><br> To draw one, please select the <br>Data Download tool <i class="fa fa-arrow-circle-o-down"></i><br>in the map window toolbar.',
          geoserver: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
          shapeFile: 'viewer_layers_extent_shrub_20210528',
          workspace: 'mrlc_viewer_layers_extent_shrub_20210528',
          dateSelection: 'yearSliders',
        },
        {
          name: 'cFeatureInfoPanel',
          import: 'js.tools.shared.cFeatureInfoPanel.cFeatureInfoPanel',
          add: true,
          title: 'Feature Info',
          height: 200,
          width: '100%',
          collapsible: true,
          collapsed: true,
          cssClass: '',
        },
        {
          name: 'cSpatialLocking',
          import: 'js.tools.shared.cSpatialLocking.cSpatialLocking',
          add: true,
          title: 'Spatial Locking Tool',
          height: 250,
          collapsible: true,
          cssClass: '',
          defaultLock: true,
        },
        {
          name: 'cArrangeWindows',
          import: 'js.tools.shared.cArrangeWindows.cArrangeWindows',
          add: true,
          title: 'Arrange Windows Tool',
          height: 250,
          collapsible: true,
          cssClass: '',
        },
      ],
    },
  ],
  host: 'earlywarning.usgs.gov',
};
