export const layers = {
  overlays: [
    {
      type: 'folder',
      title: 'Display Layers',
      expanded: true,
      folder: [
        {
          type: 'layer',
          id: 'firePoints',
          name: 'mtbs:mtbs_fire_points',
          title: 'Fire Points',
          description:
            "This dataset is a vector point shapefile of the locations of all currently completed MTBS fires occurring between calendar year 1984 and 2019 for the continental United States, Alaska, Hawaii and Puerto Rico.  <a href='http://edcintl.cr.usgs.gov/downloads/sciweb1/shared/MTBS_Fire/data/composite_data/fod_pt_shapefile/mtbs_fod_pts_data.zip'> Download</a> the shapefile.",
          source: {
            wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
            wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
            wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
          },
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          transparency: false,
          chartIds: [],
          srs: 'EPSG:3857',
          geometryName: 'geom',
        },
        {
          type: 'folder',
          title: 'Yearly Burn Severity',
          description:
            "The MTBS Yearly Burn Severity layers are available annually by US State and Region (continental US, Alaska, Hawaii and Puerto Rico). Each mosaic includes the classified burn severity data for all mapped fires that intersect the selected State or Region. The mosaics are in GeoTiff file format and available for download from the <a href='/direct-download'>MTBS Direct Download page</a>.",
          expanded: false,
          folder: [
            {
              type: 'folder',
              title: 'Alaska',
              expanded: false,
              folder: [
                {
                  type: 'layer',
                  id: 'burnSeverityAK2020',
                  name: 'mtbs:mtbs_AK_2020',
                  title: '2020',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2019',
                  name: 'mtbs:mtbs_AK_2019',
                  title: '2019',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2018',
                  name: 'mtbs:mtbs_AK_2018',
                  title: '2018',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2017',
                  name: 'mtbs:mtbs_AK_2017',
                  title: '2017',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2016',
                  name: 'mtbs:mtbs_AK_2016',
                  title: '2016',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2015',
                  name: 'mtbs:mtbs_AK_2015',
                  title: '2015',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2014',
                  name: 'mtbs:mtbs_AK_2014',
                  title: '2014',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2013',
                  name: 'mtbs:mtbs_AK_2013',
                  title: '2013',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2012',
                  name: 'mtbs:mtbs_AK_2012',
                  title: '2012',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2011',
                  name: 'mtbs:mtbs_AK_2011',
                  title: '2011',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2010',
                  name: 'mtbs:mtbs_AK_2010',
                  title: '2010',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2009',
                  name: 'mtbs:mtbs_AK_2009',
                  title: '2009',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2008',
                  name: 'mtbs:mtbs_AK_2008',
                  title: '2008',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2007',
                  name: 'mtbs:mtbs_AK_2007',
                  title: '2007',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2006',
                  name: 'mtbs:mtbs_AK_2006',
                  title: '2006',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2005',
                  name: 'mtbs:mtbs_AK_2005',
                  title: '2005',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2004',
                  name: 'mtbs:mtbs_AK_2004',
                  title: '2004',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2003',
                  name: 'mtbs:mtbs_AK_2003',
                  title: '2003',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2002',
                  name: 'mtbs:mtbs_AK_2002',
                  title: '2002',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2001',
                  name: 'mtbs:mtbs_AK_2001',
                  title: '2001',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK2000',
                  name: 'mtbs:mtbs_AK_2000',
                  title: '2000',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK1999',
                  name: 'mtbs:mtbs_AK_1999',
                  title: '1999',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK1998',
                  name: 'mtbs:mtbs_AK_1998',
                  title: '1998',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK1997',
                  name: 'mtbs:mtbs_AK_1997',
                  title: '1997',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK1996',
                  name: 'mtbs:mtbs_AK_1996',
                  title: '1996',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK1995',
                  name: 'mtbs:mtbs_AK_1995',
                  title: '1995',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK1994',
                  name: 'mtbs:mtbs_AK_1994',
                  title: '1994',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK1993',
                  name: 'mtbs:mtbs_AK_1993',
                  title: '1993',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK1992',
                  name: 'mtbs:mtbs_AK_1992',
                  title: '1992',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK1991',
                  name: 'mtbs:mtbs_AK_1991',
                  title: '1991',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK1990',
                  name: 'mtbs:mtbs_AK_1990',
                  title: '1990',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK1989',
                  name: 'mtbs:mtbs_AK_1989',
                  title: '1989',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK1988',
                  name: 'mtbs:mtbs_AK_1988',
                  title: '1988',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK1987',
                  name: 'mtbs:mtbs_AK_1987',
                  title: '1987',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK1986',
                  name: 'mtbs:mtbs_AK_1986',
                  title: '1986',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK1985',
                  name: 'mtbs:mtbs_AK_1985',
                  title: '1985',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityAK1984',
                  name: 'mtbs:mtbs_AK_1984',
                  title: '1984',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
              ],
            },
            {
              type: 'folder',
              title: 'CONUS',
              expanded: false,
              folder: [
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2021',
                  name: 'mtbs:mtbs_CONUS_2021',
                  title: '2021',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2020',
                  name: 'mtbs:mtbs_CONUS_2020',
                  title: '2020',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2019',
                  name: 'mtbs:mtbs_CONUS_2019',
                  title: '2019',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2018',
                  name: 'mtbs:mtbs_CONUS_2018',
                  title: '2018',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2017',
                  name: 'mtbs:mtbs_CONUS_2017',
                  title: '2017',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2016',
                  name: 'mtbs:mtbs_CONUS_2016',
                  title: '2016',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2015',
                  name: 'mtbs:mtbs_CONUS_2015',
                  title: '2015',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2014',
                  name: 'mtbs:mtbs_CONUS_2014',
                  title: '2014',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2013',
                  name: 'mtbs:mtbs_CONUS_2013',
                  title: '2013',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2012',
                  name: 'mtbs:mtbs_CONUS_2012',
                  title: '2012',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2011',
                  name: 'mtbs:mtbs_CONUS_2011',
                  title: '2011',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2010',
                  name: 'mtbs:mtbs_CONUS_2010',
                  title: '2010',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2009',
                  name: 'mtbs:mtbs_CONUS_2009',
                  title: '2009',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2008',
                  name: 'mtbs:mtbs_CONUS_2008',
                  title: '2008',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2007',
                  name: 'mtbs:mtbs_CONUS_2007',
                  title: '2007',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2006',
                  name: 'mtbs:mtbs_CONUS_2006',
                  title: '2006',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2005',
                  name: 'mtbs:mtbs_CONUS_2005',
                  title: '2005',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2004',
                  name: 'mtbs:mtbs_CONUS_2004',
                  title: '2004',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2003',
                  name: 'mtbs:mtbs_CONUS_2003',
                  title: '2003',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2002',
                  name: 'mtbs:mtbs_CONUS_2002',
                  title: '2002',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2001',
                  name: 'mtbs:mtbs_CONUS_2001',
                  title: '2001',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS2000',
                  name: 'mtbs:mtbs_CONUS_2000',
                  title: '2000',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS1999',
                  name: 'mtbs:mtbs_CONUS_1999',
                  title: '1999',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS1998',
                  name: 'mtbs:mtbs_CONUS_1998',
                  title: '1998',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS1997',
                  name: 'mtbs:mtbs_CONUS_1997',
                  title: '1997',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS1996',
                  name: 'mtbs:mtbs_CONUS_1996',
                  title: '1996',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS1995',
                  name: 'mtbs:mtbs_CONUS_1995',
                  title: '1995',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS1994',
                  name: 'mtbs:mtbs_CONUS_1994',
                  title: '1994',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS1993',
                  name: 'mtbs:mtbs_CONUS_1993',
                  title: '1993',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS1992',
                  name: 'mtbs:mtbs_CONUS_1992',
                  title: '1992',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS1991',
                  name: 'mtbs:mtbs_CONUS_1991',
                  title: '1991',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS1990',
                  name: 'mtbs:mtbs_CONUS_1990',
                  title: '1990',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS1989',
                  name: 'mtbs:mtbs_CONUS_1989',
                  title: '1989',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS1988',
                  name: 'mtbs:mtbs_CONUS_1988',
                  title: '1988',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS1987',
                  name: 'mtbs:mtbs_CONUS_1987',
                  title: '1987',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS1986',
                  name: 'mtbs:mtbs_CONUS_1986',
                  title: '1986',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS1985',
                  name: 'mtbs:mtbs_CONUS_1985',
                  title: '1985',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityCONUS1984',
                  name: 'mtbs:mtbs_CONUS_1984',
                  title: '1984',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
              ],
            },
            {
              type: 'folder',
              title: 'Hawaii',
              expanded: false,
              folder: [
                {
                  type: 'layer',
                  id: 'burnSeverityHI2019',
                  name: 'mtbs:mtbs_HI_2019',
                  title: '2019',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityHI2018',
                  name: 'mtbs:mtbs_HI_2018',
                  title: '2018',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityHI2017',
                  name: 'mtbs:mtbs_HI_2017',
                  title: '2017',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityHI2016',
                  name: 'mtbs:mtbs_HI_2016',
                  title: '2016',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityHI2015',
                  name: 'mtbs:mtbs_HI_2015',
                  title: '2015',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityHI2012',
                  name: 'mtbs:mtbs_HI_2012',
                  title: '2012',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityHI2009',
                  name: 'mtbs:mtbs_HI_2009',
                  title: '2009',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityHI2007',
                  name: 'mtbs:mtbs_HI_2007',
                  title: '2007',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityHI2005',
                  name: 'mtbs:mtbs_HI_2005',
                  title: '2005',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityHI2003',
                  name: 'mtbs:mtbs_HI_2003',
                  title: '2003',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityHI2002',
                  name: 'mtbs:mtbs_HI_2002',
                  title: '2002',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityHI2000',
                  name: 'mtbs:mtbs_HI_2000',
                  title: '2000',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityHI1992',
                  name: 'mtbs:mtbs_HI_1992',
                  title: '1992',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
              ],
            },
            {
              type: 'folder',
              title: 'Puerto Rico',
              expanded: false,
              folder: [
                {
                  type: 'layer',
                  id: 'burnSeverityPR2013',
                  name: 'mtbs:mtbs_PR_2013',
                  title: '2013',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityPR2007',
                  name: 'mtbs:mtbs_PR_2007',
                  title: '2007',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
                {
                  type: 'layer',
                  id: 'burnSeverityPR2005',
                  name: 'mtbs:mtbs_PR_2005',
                  title: '2005',
                  source: {
                    wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
                    wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
                    wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
                    gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
                  },
                  loadOnly: false,
                  display: false,
                  mask: false,
                  srs: 'EPSG:3857',
                  featureInfo: {},
                  loaded: 'true',
                  geometryName: 'geom',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'folder',
      title: 'Query Layers',
      expanded: true,
      folder: [
        {
          type: 'layer',
          id: 'firePolygons',
          name: 'mtbs:mtbs_fire_polygons',
          title: 'Fire Polygons',
          description:
            "This dataset is a vector polygon shapefile of the extent of the burned areas of all currently completed MTBS fires occurring between calendar year 1984 and 2019 for the continental United States, Alaska, Hawaii and Puerto Rico. <a href='http://edcintl.cr.usgs.gov/downloads/sciweb1/shared/MTBS_Fire/data/composite_data/burned_area_extent_shapefile/mtbs_perimeter_data.zip'> Download</a> the shapefile.",
          source: {
            wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
            wcs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wcs?',
            wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
          },
          info_format: 'application/json',
          loadOnly: false,
          display: true,
          active: true,
          mask: false,
          zIndex: 0,
          transparency: false,
          chartIds: [],
          srs: 'EPSG:3857',
          geometryName: 'geom',
          featureInfo: {
            burnbndac: {
              displayName: 'Acres',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            event_id: {
              displayName: 'Fire Id',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            incid_name: {
              displayName: 'Fire Name',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            ig_date: {
              displayName: 'Ignition Date',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            incid_type: {
              displayName: 'Fire Type',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            geom: {
              displayName: 'Geom',
              displayValue: null,
              value: null,
              mapValues: [],
            },
          },
        },
      ],
    },
  ],
  boundaries: [
    {
      type: 'folder',
      title: 'Boundaries',
      expanded: true,
      folder: [
        {
          type: 'layer',
          id: 'states',
          name: 'mtbs:mtbs_states',
          title: 'States',
          description:
            'Cartographic boundaries for all U.S. states; produced by the U.S. Census Bureau as part of the national TIGER Database at a resolution of 1:5,000,000.',
          source: {
            wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
            wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
            gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
          },
          info_format: 'application/json',
          loadOnly: false,
          display: true,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          geometryName: 'geom',
          legend: {
            style: '',
            customImageURL: null,
            title: '',
          },
        },
        {
          type: 'layer',
          id: 'counties',
          name: 'mtbs:mtbs_counties',
          title: 'Counties',
          description:
            'Cartographic boundaries for all U.S. counties; produced by the U.S. Census Bureau as part of the national TIGER Database at a resolution of 1:5,000,000.',
          source: {
            wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
            wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
            gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
          },
          info_format: 'application/json',
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          geometryName: 'geom',
          legend: {
            style: '',
            customImageURL: null,
            title: '',
          },
        },
        {
          type: 'layer',
          id: 'watersheds',
          name: 'mtbs:mtbs_watersheds',
          title: 'Watersheds',
          description:
            "Hydrologic Unit Maps the surface water drainage for the entirety of the US, georeferenced to 1:24,000 topographic based maps.  The hydrologic units vary are mapped at different scales which are assigned a Hydrologic Unit Code (HUC).  HUC hierarchy is based on the number of digits of the group ranging from 2-12, with higher numbers representing smaller subregion size. The units present for this layer is the HUC 8, which maps at the subbasin region.  Please see <a href='https://enviroatlas.epa.gov/enviroatlas/DataFactSheets/pdf/Supplemental/HUC.pdf'>https://enviroatlas.epa.gov/enviroatlas/DataFactSheets/pdf/Supplemental/HUC.pdf</a> and <a href='https://water.usgs.gov/GIS/huc.html'>https://water.usgs.gov/GIS/huc.html</a> for additional details.",
          source: {
            wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
            wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
            gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
          },
          info_format: 'application/json',
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          geometryName: 'geom',
          legend: {
            style: '',
            customImageURL: null,
            title: '',
          },
        },
        {
          type: 'layer',
          id: 'protectedAreas',
          name: 'mtbs:mtbs_protected_areas',
          title: 'Protected Areas',
          description:
            "Protected Areas – “Fee lands of GAP Status 3 or higher. Produced by the USGS Gap Analysis Program. Data and documentation available at <a href='https://gapanalysis.usgs.gov/padus/'>https://gapanalysis.usgs.gov/padus/</a>. Current to May 2016.",
          source: {
            wms: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wms?',
            wfs: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/wfs?',
            gwc: 'https://igskmncnlxvs196.cr.usgs.gov:8443/geoserver/gwc/service/wms?',
          },
          info_format: 'application/json',
          loadOnly: true,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          geometryName: 'geom',
          style: '',
          legend: {
            style: '',
            customImageURL: null,
            title: '',
          },
        },
      ],
    },
  ],
  baselayers: [
    {
      type: 'folder',
      title: 'Base Layers',
      expanded: true,
      folder: [
        {
          type: 'layer',
          name: 'ArcGIS',
          title: 'ESRI World Imagery',
          description: '',
          loadOnly: false,
          display: true,
          mask: false,
          srs: 'EPSG:3857',
          loaded: 'true',
          brand: 'osm',
          source: {
            url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
          },
          comments: '',
        },
        {
          type: 'layer',
          name: 'osm_0',
          title: 'OpenStreetMap',
          description: '',
          loadOnly: false,
          display: false,
          mask: false,
          srs: 'EPSG:3857',
          loaded: 'true',
          brand: 'osm',
          source: {
            url: 'https://osm-{1-4}.gs.mil/tiles/default/{z}/{x}/{y}.png',
          },
          comments: '',
        },
      ],
    },
  ],
};
