export const layers = {
  overlays: [
    {
      type: 'folder',
      title: 'Query Layers',
      expanded: true,
      folder: [
        {
          type: 'layer',
          id: 'lidar_plots',
          name: 'fwslidar:intEliMon_shapefile_lidar_plots_universal_outputs',
          title: 'Lidar Plots',
          description:
            "This dataset is a vector polygon shapefile of the extent of the burned areas of all currently completed MTBS fires occurring between calendar year 1984 and 2019 for the continental United States, Alaska, Hawaii and Puerto Rico. <a href='http://edcintl.cr.usgs.gov/downloads/sciweb1/shared/MTBS_Fire/data/composite_data/burned_area_extent_shapefile/mtbs_perimeter_data.zip'> Download</a> the shapefile.",
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wcs: 'https://dmsdata.cr.usgs.gov/geoserver/wcs?',
            wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
          },
          info_format: 'application/json',
          loadOnly: false,
          display: true,
          active: true,
          mask: false,
          zIndex: 0,
          transparency: false,
          chartIds: [],
          srs: 'EPSG:3857',
          geometryName: 'geom',
          featureInfo: {
            PlotID: {
              displayName: 'Acres',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            Id: {
              displayName: 'Id',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            Site: {
              displayName: 'Site',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            PlotNo: {
              displayName: 'Plot Number',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            Year: {
              displayName: 'Year',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            Month: {
              displayName: 'Month',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            Day: {
              displayName: 'Day',
              displayValue: null,
              value: null,
              mapValues: [],
            },
            the_geom: {
              displayName: 'Geom',
              displayValue: null,
              value: null,
              mapValues: [],
            },
          },
        },
      ],
    },
  ],
  boundaries: [
    {
      type: 'folder',
      title: 'Boundaries',
      expanded: true,
      folder: [
        {
          type: 'layer',
          id: 'states',
          name: 'fwslidar_fwslidar_states:fwslidar_states',
          title: 'States',
          description:
            'Cartographic boundaries for all U.S. states; produced by the U.S. Census Bureau as part of the national TIGER Database at a resolution of 1:5,000,000.',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
            gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
          },
          info_format: 'application/json',
          loadOnly: false,
          display: true,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          geometryName: 'geom',
          legend: {
            style: '',
            customImageURL: null,
            title: '',
          },
        },
        {
          type: 'layer',
          id: 'counties',
          name: 'fwslidar_fwslidar_counties:fwslidar_counties',
          title: 'Counties',
          description:
            'Cartographic boundaries for all U.S. counties; produced by the U.S. Census Bureau as part of the national TIGER Database at a resolution of 1:5,000,000.',
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
            gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
          },
          info_format: 'application/json',
          loadOnly: false,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          geometryName: 'geom',
          legend: {
            style: '',
            customImageURL: null,
            title: '',
          },
        },
        {
          type: 'layer',
          id: 'protectedAreas',
          name: 'mtbs:mtbs_protected_areas',
          title: 'Protected Areas',
          description:
            "Protected Areas – “Fee lands of GAP Status 3 or higher. Produced by the USGS Gap Analysis Program. Data and documentation available at <a href='https://gapanalysis.usgs.gov/padus/'>https://gapanalysis.usgs.gov/padus/</a>. Current to May 2016.",
          source: {
            wms: 'https://dmsdata.cr.usgs.gov/geoserver/wms?',
            wfs: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
            gwc: 'https://dmsdata.cr.usgs.gov/geoserver/gwc/service/wms?',
          },
          info_format: 'application/json',
          loadOnly: true,
          display: false,
          mask: false,
          zIndex: 0,
          regionIds: ['us'],
          srs: 'EPSG:3857',
          geometryName: 'geom',
          style: '',
          legend: {
            style: '',
            customImageURL: null,
            title: '',
          },
        },
      ],
    },
  ],
  baselayers: [
    {
      type: 'folder',
      title: 'Base Layers',
      expanded: true,
      folder: [
        {
          type: 'layer',
          name: 'ArcGIS',
          title: 'ESRI World Imagery',
          description: '',
          loadOnly: false,
          display: true,
          mask: false,
          srs: 'EPSG:3857',
          loaded: 'true',
          brand: 'osm',
          source: {
            url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
          },
          comments: '',
        },
        {
          type: 'layer',
          name: 'osm_0',
          title: 'OpenStreetMap',
          description: '',
          loadOnly: false,
          display: false,
          mask: false,
          srs: 'EPSG:3857',
          loaded: 'true',
          brand: 'osm',
          source: {
            url: 'https://osm-{1-4}.gs.mil/tiles/default/{z}/{x}/{y}.png',
          },
          comments: '',
        },
      ],
    },
  ],
};
