export const layers = {
  overlays: [
    {
      type: 'folder',
      title: 'Layers',
      description: "<a href='https://www.geosur.info/ogcservices/rest/services/GeoSUR/GEOSUR_MIAC/MapServer' target='_blank'>Description</a>",
      expanded: true,
      regionId: 'camcar',
      folder: [
        {
          type: 'folder',
          title: 'Central American Integrated Map',
          description: "<a href='https://www.geosur.info/ogcservices/rest/services/GeoSUR/GEOSUR_MIAC/MapServer' target='_blank'>Description</a>",
          expanded: true,
          regionId: 'camcar',
          folder: [
            {
              type: 'layer',
              id: '',
              name: 'Topónimo',
              title: 'Place name',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/arcgis/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Topónimo',
                title: 'Place name',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Poblado',
              title: 'Populated place',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Poblado',
                title: 'Populated place',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Punto acotado',
              title: 'Bounded Point',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Punto acotado',
                title: 'Bounded Point',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Punto de interés',
              title: 'Point of interest',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Punto de interés',
                title: 'Point of interest',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Etiquetas de país',
              title: 'Country labels',
              description: '',
              brand: 'image',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Etiquetas de país',
                title: 'Country labels',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'País',
              title: 'Country',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=País',
                title: 'Country',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Nivel_1A',
              title: 'Admin level 1',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Nivel_1A',
                title: 'Admin level 1',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Nivel_2A',
              title: 'Admin level 2',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Nivel_2A',
                title: 'Admin level 2',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Nivel_3A',
              title: 'Admin level 3',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Nivel_3A',
                title: 'Admin level 3',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Línea de costa',
              title: 'Coast line',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Línea de costa',
                title: 'Coast line',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Mancha urbana',
              title: 'Urban spot',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Mancha urbana',
                title: 'Urban spot',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Autopista',
              title: 'Highway',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Autopista',
                title: 'Highway',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Otras carreteras',
              title: 'Other roads',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Otras carreteras',
                title: 'Other roads',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Vía de ferrocarril',
              title: 'Railway',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Vía de ferrocarril',
                title: 'Railway',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Isla',
              title: 'Island',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Isla',
                title: 'Island',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Lagos y rios',
              title: 'Lakes and rivers',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Lagos y rios',
                title: 'Lakes and rivers',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Otro tipo de cuerpo de agua',
              title: 'Other type of water body',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Otro tipo de cuerpo de agua',
                title: 'Other type of water body',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Forma hidrográfica',
              title: 'Hydrographic form',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Forma hidrográfica',
                title: 'Hydrographic form',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Curso principal de agua',
              title: 'Main water course',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Curso principal de agua',
                title: 'Main water course',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Tipo de curso de agua',
              title: 'Other water course',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Tipo de curso de agua',
                title: 'Other water course',
              },
            },
            {
              type: 'layer',
              id: '',
              name: 'Elevaciones',
              title: 'Elevations',
              description: '',
              source: {
                wms: 'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WMSServer?',
              },
              infoFormat: 'application/geojson',
              loadOnly: false,
              display: true,
              mask: false,
              zIndex: 0,
              transparency: true,
              chartIds: [],
              srs: 'EPSG:3857',
              featureInfo: {},
              style: '',
              legend: {
                style: '',
                customImageURL:
                  'https://www.geosur.info/ogcservices/services/GeoSUR/GEOSUR_MIAC/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=Elevaciones',
                title: 'Elevations',
              },
            },
          ],
        },
      ],
    },
  ],
  boundaries: [],
  baselayers: [
    {
      type: 'folder',
      title: 'Basemaps',
      regionId: 'camcar',
      expanded: true,
      folder: [
        {
          type: 'layer',
          name: 'osm_0',
          title: 'Transport OpenStreetMap',
          description:
            "<p>Maps © <a href='https://www.thunderforest.com/maps/' target='_blank'>Thunderforest</a>, Data © <a href='https://www.openstreetmap.org/copyright' target='blank'>OpenStreetMap contributors</a></p><p>Thunderforest is a project by Gravitystorm Limited.</p>",
          loadOnly: false,
          display: true,
          mask: false,
          srs: 'EPSG:3857',
          loaded: 'true',
          brand: 'osm',
          source: {
            url: 'https://tile.thunderforest.com/transport/{z}/{x}/{y}.png?apikey=6a016c81411f47cf996ecf50d662545c',
          },
          comments: '',
        },
        {
          type: 'layer',
          name: 'osm_0',
          title: 'Standard OpenStreetMap',
          description: "<p>© <a href='https://www.openstreetmap.org/copyright' target='blank'>OpenStreetMap contributors</a></p>",
          loadOnly: false,
          display: false,
          mask: false,
          srs: 'EPSG:3857',
          loaded: 'true',
          brand: 'osm',
          source: {},
          comments: '',
        },
      ],
    },
  ],
};
