import logo from '../../assets/images/logo.png';

export const template = {
  theme: 'ExtJSNeptune',
  cssFallback: true,
  analytics: {
    matomo: {
      baseUrl: '//edcintl.cr.usgs.gov/piwik/',
      id: '15',
    },
    google: {
      id: 'UA-71865847-3',
    },
  },
  blocks: [
    {
      block: 'top',
      name: 'cHeader',
      import: 'js.tools.shared.cHeader.cHeader',
      title: 'Phenology Viewer',
      add: true,
      width: 'auto',
      height: 68,
      cssClass: '',
      bodyStyle: 'padding: 0px',
      collapsible: true,
      content: `<header id='navbar' class='header-nav'  role='banner'><div class='tmp-container'><div class='header-search'><a class='logo-header' href='https://www.usgs.gov/' title='Home'><img class='img'  src='${logo}' alt='Home' /></a><form action='https://www.usgs.gov/science-explorer-results' method='GET' id='search-box'><div class='a-wrapper'><label for='se_search' class='only'>Search</label><input id='se_search' type='search' name='es' placeholder='Search'><button class='fa fa-search' type='submit'<span class='only'></span></button></div></form></div></div></header>`,
      link: 'http://earlywarning.usgs.gov',
      toolbar: {
        position: 'bottom',
        add: false,
        style: 'background-color: black;',
        overflowMenu: false,
        items: [
          {
            name: 'cExternalLinkButtonTool',
            add: false,
            import: 'js.tools.shared.cExternalLinkButtonTool.cExternalLinkButtonTool',
            url: 'http://vegdri.cr.usgs.gov',
            tooltip: 'Monitoring Drought - Home',
            icon: 'fa-home',
            width: 30,
          },
          {
            name: 'cPopupButtonTool',
            import: 'js.tools.quickdri.cPopupButtonTool.cPopupButtonTool',
            add: false,
            popupTitle: 'Vegetation Dynamics Viewer',
            popupBody:
              'This interactive map service provides regularly updated geospatial data related to drought conditions, including eMODIS VegDRI (each Monday by 8:00 AM), 7-Day Average Streamflows (USGS Water Watch: updated daily at 10:00 AM), Precipitation Derivatives (NWS Precipitation Analysis: Updated daily at 7:00 PM), and the weekly U.S. Drought Monitor (Thursday at 8:30 AM).',
            popupHeight: 360,
            tooltip: 'Collaborators',
            text: '?',
            width: 30,
          },
          {
            name: 'cPopupButtonTool',
            add: false,
            import: 'js.tools.quickdri.cPopupButtonTool.cPopupButtonTool',
            popupTitle: 'Vegetation Dynamics Viewer',
            popupBody:
              "<table border=0 cellspacing=2 cellpadding=2><tr><td align=left><a href='http://vegdri.unl.edu' target='_blank'><img src='images/quickdriImages/logo1b.png' alt='National Drought Mitigation Center' title='National Drought Mitigation Center'></a></td align=left><td align=left>National Drought Mitigation Center</td align=left><td align=left><a href='http://www.hprcc.unl.edu' target='_blank'><img src='images/quickdriImages/logo2b.png' alt='High Plains Regional Climate Center' title='High Plains Regional Climate Center'></a></td align=left><td align=left>High Plains Regional Climate Center</td align=left></tr><tr><td align=left><br /></td align=left></tr><tr><td align=left><a href='http://hrsl.arsusda.gov/drought/' target='_blank'><img src='images/quickdriImages/logo3b.jpg' alt='USDA Agriculture Research Service' title='USDA Agriculture Research Service'></a></td align=left><td align=left>USDA Agriculture Research Service</td align=left><td align=left><a href='http://ldas.gsfc.nasa.gov/index.php' target='_blank'><img src='images/quickdriImages/logo4b.png' alt='Land Data Assimilation System' title='Land Data Assimilation System'></a></td align=left><td align=left>Land Data Assimilation System</td align=left></tr><tr><td align=left><br /></td align=left></tr><tr><td align=left><a href='https://c3.nasa.gov/water/ ' target='_blank'><img src='images/quickdriImages/logo5b.jpg' alt='National Aeronautics and Space Administration' title='National Aeronautics and Space Administration'></a></td align=left><td align=left>National Aeronautics and Space Administration</td align=left><td align=left><a href='http://www.rma.usda.gov' target='_blank'><img src='images/quickdriImages/logo6b.jpg' alt='U.S. Department of Agriculture Risk Management Agency' title='U.S. Department of Agriculture Risk Management Agency'></a></td align=left><td align=left>U.S. Department of Agriculture Risk Management Agency</td align=left></tr></table>",
            popupHeight: 700,
            tooltip: 'Collaborators',
            icon: 'fa-users',
            width: 30,
          },
        ],
      },
    },
    {
      block: 'left',
      name: 'cTOCDesktopLike',
      import: 'js.tools.shared.cTOCDesktopLike.cTOCDesktopLike',
      add: false,
      width: 370,
      height: 'auto',
      title: 'TOC',
      blocks: [
        {
          block: 'top',
          name: 'cTocContainer',
          import: 'js.tools.shared.cTocContainer.cTocContainer',
          width: '100%',
          height: 'auto',
          add: true,
          blocks: [
            {
              name: 'cDefaultToc',
              import: 'js.tools.shared.cDefaultToc.cDefaultToc',
              add: true,
              width: '100%',
              height: 'auto',
              titleLength: 20,
            },
          ],
        },
        {
          name: 'cTransparency',
          import: 'js.tools.shared.cTransparency.cTransparency',
          add: true,
          height: 100,
          width: '90%',
        },
      ],
      toolbar: {
        position: 'top',
        overflowMenu: false,
        items: [
          {
            name: 'cRegionTool',
            import: 'js.tools.shared.cRegionTool.cRegionTool',
            add: false,
            width: 200,
          },
        ],
      },
    },
    {
      block: 'left',
      name: 'cToc',
      import: 'js.tools.shared.cToc.cToc',
      add: true,
      width: 325,
      height: 'auto',
      title: 'TOC',
      collapsible: true,
      blocks: [
        {
          block: 'center',
          name: 'cTocTabPanel',
          import: 'js.tools.shared.cTocTabPanel.cTocTabPanel',
          add: true,
          blocks: [
            {
              add: true,
              title: 'Contents',
              name: 'cTocContentsTab',
              import: 'js.tools.shared.cTocContentsTab.cTocContentsTab',
              blocks: [
                {
                  block: 'center',
                  add: true,
                  width: '100%',
                  height: '50%',
                  title: 'Dataset (Double click to open)',
                  name: 'cTocContainer',
                  import: 'js.tools.shared.cTocContainer.cTocContainer',
                  blocks: [
                    {
                      block: 'center',
                      name: 'cDatasetToc',
                      import: 'js.tools.phenology.cDatasetToc.cDatasetToc',
                      add: true,
                      toolbar: {
                        position: 'top',
                        overflowMenu: false,
                        items: [
                          {
                            name: 'cRegionTool',
                            import: 'js.tools.shared.cRegionTool.cRegionTool',
                            add: false,
                            width: 200,
                          },
                          {
                            name: 'cExternalLinkButtonTool',
                            import: 'js.tools.shared.cExternalLinkButtonTool.cExternalLinkButtonTool',
                            add: true,
                            url: 'https://www.usgs.gov/land-resources/eros/phenology',
                            tooltip: 'Phenology - Home',
                            icon: 'fa-home',
                            width: 30,
                          },
                          {
                            name: 'cPopupButtonTool',
                            add: true,
                            import: 'js.tools.quickdri.cPopupButtonTool.cPopupButtonTool',
                            popupTitle: 'Notice to users',
                            popupBody: `We are releasing the 2019 Remote Sensing Phenology metrics with a caution to the user community: we have identified anomalies and have concerns regarding the End of Season Time (EOST) metric, especially within the state of Montana. In parts of the state, the EOST occurs many weeks later than in previous years. The delayed EOST affects several other phenology metrics, i.e., Duration (DUR), End of Season NDVI (EOSN), and Time Integrated NDVI (TIN). We apologize for any inconvenience this causes. Investigation into the root cause of this anomaly is ongoing.`,
                            popupHeight: 400,
                            tooltip: 'Notice',
                            alwaysShow: true,
                            showOnFirstLoad: false,
                            useOkButtons: false,
                            icon: 'fa-exclamation-triangle',
                            width: 30,
                          },
                        ],
                      },
                    },
                  ],
                },
                {
                  block: 'bottom',
                  add: true,
                  width: '100%',
                  height: '50%',
                  title: 'Layers',
                  name: 'cTocContainer',
                  import: 'js.tools.shared.cTocContainer.cTocContainer',
                  blocks: [
                    {
                      block: 'center',
                      name: 'cLayersToc',
                      import: 'js.tools.phenology.cLayersToc.cLayersToc',
                      add: true,
                      toolbar: {
                        position: 'top',
                        overflowMenu: false,
                        items: [
                          {
                            name: 'cAddWMSLayerTool',
                            import: 'js.tools.shared.cAddWMSLayerTool.cAddWMSLayerTool',
                            add: true,
                            tooltip: 'Add WMS Layer',
                          },
                          {
                            name: 'cRemoveWMSLayerTool',
                            import: 'js.tools.shared.cRemoveWMSLayerTool.cRemoveWMSLayerTool',
                            add: true,
                            tooltip: 'Remove WMS Layer',
                          },
                        ],
                      },
                    },
                  ],
                },
              ],
            },
            {
              add: true,
              title: 'Legend',
              showBoundaries: true,
              name: 'cTocLegendTab',
              import: 'js.tools.shared.cTocLegendTab.cTocLegendTab',
            },
          ],
        },
      ],
    },
    {
      block: 'center',
      blocks: [
        {
          block: 'relative',
          name: 'cAddWMSLayerForm',
          import: 'js.tools.shared.cAddWMSLayerForm.cAddWMSLayerForm',
          add: true,
          width: 350,
          height: 105,
          x: 390,
          y: 550,
          title: 'Add WMS Layers',
        },
        {
          block: 'relative',
          name: 'cRemoveWMSLayerForm',
          import: 'js.tools.shared.cRemoveWMSLayerForm.cRemoveWMSLayerForm',
          add: true,
          width: 350,
          height: 105,
          x: 390,
          y: 550,
          title: 'Remove WMS Layers',
        },
        {
          block: 'relative',
          name: 'cMapWindow',
          import: 'js.tools.shared.cMapWindow.cMapWindow',
          add: true,
          width: 580,
          height: 650,
          x: 410,
          y: 90,
          collapsible: true,
          // toolbar: {
          //   position: 'top',
          //   overflowMenu: true,
          //   items: [
          //     {
          //       name: 'cZoomToRegionTool',
          //       import: 'js.tools.shared.cZoomToRegionTool.cZoomToRegionTool',
          //       title: '',
          //       add: false,
          //       cssClass: '',
          //       tooltip: 'Zoom to Region',
          //     },
          //     {
          //       name: 'cPanTool',
          //       import: 'js.tools.shared.cPanTool.cPanTool',
          //       title: '',
          //       add: true,
          //       cssClass: '',
          //       tooltip: 'Pan Tool',
          //     },
          //     {
          //       name: 'cExtentDragBoxTool',
          //       import: 'js.tools.shared.cExtentDragBoxTool.cExtentDragBoxTool',
          //       title: '',
          //       add: true,
          //       cssClass: '',
          //       tooltip: 'Zoom to Extent',
          //     },
          //     {
          //       name: 'cRevertExtentTool',
          //       import: 'js.tools.shared.cRevertExtentTool.cRevertExtentTool',
          //       title: '',
          //       add: true,
          //       cssClass: '',
          //       tooltip: 'Zoom to Previous',
          //     },
          //     {
          //       name: 'cIdentifyTool',
          //       import: 'js.tools.shared.cIdentifyTool.cIdentifyTool',
          //       title: '',
          //       add: true,
          //       cssClass: '',
          //       tooltip: 'Identify Tool',
          //     },
          //     {
          //       name: 'cGraphTool',
          //       import: 'js.tools.shared.cGraphTool.cGraphTool',
          //       title: '',
          //       add: false,
          //       cssClass: '',
          //       pressed: true,
          //       tooltip: 'Graph Tool',
          //       layers: [
          //         {
          //           id: 'qdhydrounits_id',
          //           featureInfo: [],
          //         },
          //       ],
          //     },
          //     {
          //       name: 'cSpacer',
          //       import: 'js.tools.shared.cSpacer.cSpacer',
          //       add: true,
          //     },
          //     {
          //       name: 'cDatasetExplorerTool',
          //       import: 'js.tools.shared.cDatasetExplorerTool.cDatasetExplorerTool',
          //       title: '',
          //       add: false,
          //       cssClass: '',
          //       tooltip: 'Select displayed layer',
          //     },
          //     {
          //       name: 'cDatePickerTool',
          //       import: 'js.tools.shared.cDatePickerTool.cDatePickerTool',
          //       title: '',
          //       add: true,
          //       cssClass: '',
          //       pickerType: 'combobox',
          //       tooltip: 'Select Date',
          //     },
          //     {
          //       name: 'cAddMapWindowTool',
          //       import: 'js.tools.shared.cAddMapWindowTool.cAddMapWindowTool',
          //       title: '',
          //       add: false,
          //       cssClass: '',
          //       tooltip: 'New Map Window',
          //     },
          //     {
          //       name: 'cMapDownloadsTool',
          //       import: 'js.tools.quickdri.cMapDownloadsTool.cMapDownloadsTool',
          //       add: true,
          //       tooltip: '',
          //       items: [
          //         {
          //           name: 'cMenuLabel',
          //           import: 'js.tools.shared.cMenuLabel.cMenuLabel',
          //           add: true,
          //           label: 'Download:',
          //         },
          //         {
          //           name: 'cMapDownloadsMenuItem',
          //           import: 'js.tools.phenology.cMapDownloadsMenuItem.cMapDownloadsMenuItem',
          //           add: true,
          //           type: 'wcs',
          //           format: 'image/geotiff',
          //           text: 'Geotiff (RAW)',
          //         },
          //         {
          //           name: 'cMapDownloadsMenuItemZipExternalLink',
          //           import: 'js.tools.phenology.cMapDownloadsMenuItemZipExternalLink.cMapDownloadsMenuItemZipExternalLink',
          //           add: true,
          //           text: 'Full Extent (East) Zips',
          //           link: 'https://phenology.cr.usgs.gov/get_data_Aqua_C6_250e.php',
          //         },
          //         {
          //           name: 'cMapDownloadsMenuItemZipExternalLink',
          //           import: 'js.tools.phenology.cMapDownloadsMenuItemZipExternalLink.cMapDownloadsMenuItemZipExternalLink',
          //           add: true,
          //           text: 'Full Extent (West) Zips',
          //           link: 'https://phenology.cr.usgs.gov/get_data_Aqua_C6_250w.php',
          //         },
          //         {
          //           name: 'cMapDownloadsMenuItemPNG',
          //           import: 'js.tools.phenology.cMapDownloadsMenuItemPNG.cMapDownloadsMenuItemPNG',
          //           add: true,
          //           type: 'wms',
          //           format: 'image/png',
          //           text: 'Layers in display (PNG)',
          //         },
          //       ],
          //     },
          //     {
          //       name: 'cMapLegendTool',
          //       import: 'js.tools.shared.cMapLegendTool.cMapLegendTool',
          //       add: true,
          //       tooltip: 'Toggle map legend',
          //       pressed: false,
          //     },
          //   ],
          // },
          blocks: [
            {
              name: 'cPanTool_olext',
              import: 'js.tools.shared.cPanTool.cPanTool_olext',
              add: true,
            },

            {
              name: 'cExtentDragBoxTool_olext',
              import: 'js.tools.shared.cExtentDragBoxTool.cExtentDragBoxTool_olext',
              add: true,
            },

            {
              name: 'cRevertExtentTool_olext',
              import: 'js.tools.shared.cRevertExtentTool.cRevertExtentTool_olext',
              add: true,
            },
            {
              name: 'cIdentifyTool_olext',
              import: 'js.tools.shared.cIdentifyTool.cIdentifyTool_olext',
              add: true,
            },

            {
              name: 'cDatePickerTool_olext',
              import: 'js.tools.shared.cDatePickerTool.cDatePickerTool_olext',
              add: true,
            },

            {
              name: 'cMapDownloadsTool_olext',
              import: 'js.tools.shared.cMapDownloadsTool.cMapDownloadsTool_olext',
              add: true,
            },
            {
              name: 'cMapLegend_olext',
              import: 'js.tools.shared.cMapLegend.cMapLegend_olext',
              add: true,
            },

            {
              block: 'top',
              name: 'cMapPanel',
              import: 'js.tools.shared.cMapPanel.cMapPanel',
              add: true,
              interactions: ['pan', 'zoom'],
              controls: [
                {
                  name: 'toolbar',
                  position: 'top-left',
                  controls: [
                    {
                      name: 'toolbar',
                      options: {
                        toggleOne: true,
                        group: true,
                      },
                      controls: ['pan', 'drag-zoom', 'revert-extent', 'identify'],
                    },
                    // 'revert-extent',
                    // {
                    //   name: 'toolbar',
                    //   options: {
                    //     toggleOne: true,
                    //     group: true,
                    //   },
                    //   controls: ['identify', 'download-tool'],
                    // },
                    {
                      name: 'notification',
                      options: {
                        // header: '',
                        // width: '18em',
                        active: true,
                        className: 'datePopup',
                      },
                      controls: ['date-picker'],
                    },
                    {
                      name: 'download',
                      controls: [
                        {
                          type: 'link',
                          text: 'Full Extent (East) Zips',
                          url: 'https://phenology.cr.usgs.gov/get_data_Aqua_C6_250e.php',
                        },
                        {
                          type: 'link',
                          text: 'Full Extent (West) Zips',
                          url: 'https://phenology.cr.usgs.gov/get_data_Aqua_C6_250w.php',
                        },
                        {
                          type: 'wcs',
                          text: 'Geotiff (RAW)',
                          format: 'image/geotiff',
                          extentSize: 'current',
                          useNativeSrs: false,
                        },
                        {
                          type: 'wms',
                          text: 'Layers in display (PNG)',
                          format: 'image/png',
                          layersInDisplay: true,
                        },
                      ],
                    },
                  ],
                },
                'legend',
                // {
                //   name: 'overlay',
                //   options: {
                //     header: '',
                //     width: '18em',
                //   },
                //   controls: ['date-picker'],
                // },
              ],
              mouseCoordinates: {
                show: true,
                projection: 'EPSG:4326',
              },
              blocks: [
                {
                  name: 'cMapLegend',
                  import: 'js.tools.shared.cMapLegend.cMapLegend',
                  block: 'relative',
                  add: false,
                },
              ],
            },
            {
              block: 'bottom',
              title: 'Historical Zonal Statistics Plot',
              name: 'cMapWindowChartArea',
              import: 'js.tools.shared.cMapWindowChartArea.cMapWindowChartArea',
              add: false,
              collapsible: true,
              blocks: [
                {
                  block: 'center',
                  name: 'cTabPanel',
                  import: 'js.tools.shared.cTabPanel.cTabPanel',
                  add: true,
                  blocks: [
                    {
                      block: 'center',
                      name: 'cChartContainer',
                      import: 'js.tools.shared.cChartContainer.cChartContainer',
                      add: true,
                      isDefault: false,
                      toolbar: {
                        overflowMenu: true,
                        items: [
                          {
                            name: 'cPeriodTypeCombo',
                            import: 'js.tools.shared.cPeriodTypeCombo.cPeriodTypeCombo',
                            title: '',
                            add: true,
                            tooltip: 'Select Period Type',
                            saveSelection: true,
                            width: 75,
                          },
                          {
                            name: 'cYearsCombo',
                            import: 'js.tools.shared.cYearsCombo.cYearsCombo',
                            title: '',
                            add: true,
                            tooltip: 'Select Years',
                            saveSelection: true,
                            showByDefault: {
                              top: 3,
                              list: ['stm'],
                            },
                            width: 120,
                          },
                          {
                            name: 'cZonesCombo',
                            import: 'js.tools.shared.cZonesCombo.cZonesCombo',
                            title: '',
                            add: true,
                            tooltip: 'Select Zone',
                            saveSelection: true,
                            width: 120,
                          },
                          {
                            name: 'cChartTypeCombo',
                            import: 'js.tools.shared.cChartTypeCombo.cChartTypeCombo',
                            title: '',
                            add: true,
                            tooltip: 'Select Chart Type',
                            saveSelection: true,
                            width: 90,
                          },
                          {
                            name: 'cSpacer',
                            import: 'js.tools.shared.cSpacer.cSpacer',
                            add: true,
                          },
                          {
                            name: 'cDockChart',
                            import: 'js.tools.shared.cDockChart.cDockChart',
                            title: '',
                            add: true,
                            tooltip: 'Dock Window',
                            saveSelection: true,
                            dockedState: 'docked',
                          },
                          {
                            name: 'cChartToolsMenu',
                            import: 'js.tools.shared.cChartToolsMenu.cChartToolsMenu',
                            title: '',
                            height: 24,
                            width: 45,
                            add: true,
                            tooltip: 'Chart Tools',
                            items: [
                              {
                                name: 'cMenuLabel',
                                import: 'js.tools.shared.cMenuLabel.cMenuLabel',
                                add: true,
                                label: 'Download:',
                              },
                              {
                                name: 'cExportPNG',
                                import: 'js.tools.shared.cExportPNG.cExportPNG',
                                title: 'PNG',
                                add: true,
                                cssClass: '',
                                tooltip: 'Save chart as PNG',
                              },
                              {
                                name: 'cExportCSV',
                                import: 'js.tools.shared.cExportCSV.cExportCSV',
                                title: 'CSV',
                                add: true,
                                cssClass: '',
                                tooltip: 'Export data as CSV',
                              },
                            ],
                          },
                          {
                            name: 'cChartLegend',
                            import: 'js.tools.shared.cChartLegend.cChartLegend',
                            title: '',
                            add: true,
                            cssClass: '',
                            tooltip: 'Show Chart Legend',
                            pressed: true,
                            legendPosition: 'bottom',
                          },
                        ],
                      },
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          block: 'relative',
          name: 'cChartContainer',
          import: 'js.tools.shared.cChartContainer.cChartContainer',
          isDefault: true,
          add: false,
          width: 850,
          height: 500,
          cssClass: '<should define the top-left position of the chart window>',
          toolbar: {
            overflowMenu: true,
            items: [
              {
                name: 'cPeriodTypeCombo',
                import: 'js.tools.shared.cPeriodTypeCombo.cPeriodTypeCombo',
                title: '',
                add: true,
                tooltip: 'Select Period Type',
                saveSelection: true,
                width: 75,
              },
              {
                name: 'cYearsCombo',
                import: 'js.tools.shared.cYearsCombo.cYearsCombo',
                title: '',
                add: true,
                tooltip: 'Select Years',
                saveSelection: true,
                showByDefault: {
                  top: 3,
                  list: ['stm'],
                },
                width: 120,
              },
              {
                name: 'cZonesCombo',
                import: 'js.tools.shared.cZonesCombo.cZonesCombo',
                title: '',
                add: true,
                tooltip: 'Select Zone',
                saveSelection: true,
                width: 120,
              },
              {
                name: 'cChartTypeCombo',
                import: 'js.tools.shared.cChartTypeCombo.cChartTypeCombo',
                title: '',
                add: true,
                tooltip: 'Select Chart Type',
                saveSelection: true,
                width: 90,
              },
              {
                name: 'cSpacer',
                import: 'js.tools.shared.cSpacer.cSpacer',
                add: true,
              },
              {
                name: 'cDockChart',
                import: 'js.tools.shared.cDockChart.cDockChart',
                title: '',
                add: true,
                tooltip: 'Dock Window',
                saveSelection: true,
                dockedState: 'undocked',
              },
              {
                name: 'cChartToolsMenu',
                import: 'js.tools.shared.cChartToolsMenu.cChartToolsMenu',
                title: '',
                height: 24,
                width: 45,
                add: true,
                tooltip: 'Chart Tools',
                items: [
                  {
                    name: 'cMenuLabel',
                    import: 'js.tools.shared.cMenuLabel.cMenuLabel',
                    add: true,
                    label: 'Download:',
                  },
                  {
                    name: 'cExportPNG',
                    import: 'js.tools.shared.cExportPNG.cExportPNG',
                    title: 'PNG',
                    add: true,
                    cssClass: '',
                    tooltip: 'Save chart as PNG',
                  },
                  {
                    name: 'cExportCSV',
                    import: 'js.tools.shared.cExportCSV.cExportCSV',
                    title: 'CSV',
                    add: true,
                    cssClass: '',
                    tooltip: 'Export data as CSV',
                  },
                ],
              },
              {
                name: 'cChartLegend',
                import: 'js.tools.shared.cChartLegend.cChartLegend',
                title: '',
                add: true,
                cssClass: '',
                tooltip: 'Show Chart Legend',
                pressed: true,
                legendPosition: 'bottom',
              },
            ],
          },
        },
      ],
    },
    {
      block: 'right',
      name: 'cTools',
      import: 'js.tools.shared.cTools.cTools',
      add: true,
      width: 250,
      height: 'auto',
      collapsible: true,
      collapsed: true,
      title: 'Tools',
      blocks: [
        {
          name: 'cFeatureInfoPanel',
          import: 'js.tools.phenology.cFeatureInfoPanel.cFeatureInfoPanel',
          add: true,
          ignoreDisplayNames: ['SEAS_START'],
          title: 'Feature Info',
          height: 200,
          width: '100%',
          collapsible: true,
          collapsed: true,
          cssClass: '',
        },
        {
          name: 'cSpatialLocking',
          import: 'js.tools.shared.cSpatialLocking.cSpatialLocking',
          add: true,
          title: 'Spatial Locking Tool',
          height: 250,
          collapsible: true,
          cssClass: '',
        },
        {
          name: 'cArrangeWindows',
          import: 'js.tools.shared.cArrangeWindows.cArrangeWindows',
          add: true,
          title: 'Arrange Windows Tool',
          height: 250,
          collapsible: true,
          cssClass: '',
        },
      ],
    },
    {
      block: 'bottom',
      name: 'cFooter',
      import: 'js.tools.shared.cFooter.cFooter',
      add: true,
      width: 'auto',
      height: 94,
      cssClass: '',
      collapsible: false,
      collapsed: false,
      resizable: false,
      content:
        "<footer class='footer'><div class='tmp-container'><div class='footer-doi'><ul class='menu nav'><li class='first leaf menu-links menu-level-1'><a href='https://www.doi.gov/privacy'>DOI Privacy Policy</a></li><li class='leaf menu-links menu-level-1'><a href='https://www.usgs.gov/laws/policies_notices.html'>Legal</a></li><li class='leaf menu-links menu-level-1'><a href='https://www2.usgs.gov/laws/accessibility.html'>Accessibility</a></li><li class='leaf menu-links menu-level-1'><a href='https://www.usgs.gov/sitemap.html'>Site Map</a></li><li class='last leaf menu-links menu-level-1'><a href='https://answers.usgs.gov/'>Contact USGS</a></li></ul></div><hr><div class='footer-doi'><ul class='menu nav'><li class='first leaf menu-links menu-level-1'><a href='https://www.doi.gov/'>U.S. Department of the Interior</a></li><li class='leaf menu-links menu-level-1'><a href='https://www.doioig.gov/'>DOI Inspector General</a></li><li class='leaf menu-links menu-level-1'><a href='https://www.whitehouse.gov/'>White House</a></li><li class='leaf menu-links menu-level-1'><a href='https://www.whitehouse.gov/omb/management/egov/'>E-gov</a></li><li class='leaf menu-links menu-level-1'><a href='https://www.doi.gov/pmb/eeo/no-fear-act'>No Fear Act</a></li><li class='last leaf menu-links menu-level-1'><a href='https://www2.usgs.gov/foia'>FOIA</a></li></ul></div><div class='footer-social-links'><ul class='social'><li class='follow'>Follow</li><li class='twitter'><a href='https://twitter.com/usgs' target='_blank'><i class='fa fa-twitter-square'><span class='only'>Twitter</span></i></a></li><li class='facebook'><a href='https://facebook.com/usgeologicalsurvey' target='_blank'><i class='fa fa-facebook-square'><span class='only'>Facebook</span></i></a></li><li class='googleplus'><a href='https://plus.google.com/112624925658443863798/posts' target='_blank'><i class='fa fa-google-plus-square'><span class='only'>Google+</span></i></a></li><li class='github'><a href='https://github.com/usgs' target='_blank'><i class='fa fa-github'><span class='only'>GitHub</span></i></a></li><li class='flickr'><a href='https://flickr.com/usgeologicalsurvey' target='_blank'><i class='fa fa-flickr'><span class='only'>Flickr</span></i></a></li><li class='youtube'><a href='http://youtube.com/usgs' target='_blank'><i class='fa fa-youtube-play'><span class='only'>YouTube</span></i></a></li><li class='instagram'><a href='https://instagram.com/usgs' target='_blank'><i class='fa fa-instagram'><span class='only'>Instagram</span></i></a></li></ul></div></div></footer>",
    },
  ],
  host: 'earlywarning.usgs.gov',
};
