import banner from '../../assets/images/landfire/banner_2021.jpg';
import legendColor from '../../assets/images/i_legend_color.png';

export const template = {
  theme: 'ExtJSNeptune',
  cssFallback: true,
  analytics: {
    google: {
      id: 'G-P1JQNF783Q',
    },
  },
  blocks: [
    {
      block: 'top',
      name: 'cHeader',
      import: 'js.tools.shared.cHeader.cHeader',
      title: 'LANDFIRE Viewer',
      add: true,
      width: 'auto',
      height: 92,
      cssClass: '',
      collapsible: true,
      content: `<div style='width: 100%; height: 100%;'><a style='color:#2d2d2d;' href='/' title='Home'><img style='float: left; height: 92px; width: auto;' src='${banner}' /><span style='float: left; margin: 0;'>LANDFIRE Data Distribution Site</span></a></div>`,
      link: 'https://www.landfire.gov',
    },
    {
      block: 'left',
      name: 'cToc',
      import: 'js.tools.shared.cToc.cToc',
      add: true,
      width: 380,
      height: 'auto',
      title: 'TOC',
      collapsible: true,
      blocks: [
        {
          block: 'center',
          name: 'cTocTabPanel',
          import: 'js.tools.shared.cTocTabPanel.cTocTabPanel',
          add: true,
          blocks: [
            {
              add: true,
              title: 'Contents',
              name: 'cTocContentsScrollTab',
              import: 'js.tools.shared.cTocContentsScrollTab.cTocContentsScrollTab',
              blocks: [
                {
                  height: 100,
                  name: 'cDefaultToc',
                  import: 'js.tools.shared.cDefaultToc.cDefaultToc',
                  add: true,
                  titleLength: 70,
                  hideDatePicker: true,
                },
                {
                  name: 'cTransparency',
                  add: true,
                  import: 'js.tools.shared.cTransparency.cTransparency',
                  height: 100,
                  width: '90%',
                },
              ],
              toolbar: {
                position: 'top',
                overflowMenu: true,
                items: [
                  {
                    name: 'cRegionTool',
                    import: 'js.tools.landfire.cRegionTool.cRegionTool',
                    add: true,
                    width: 150,
                  },
                  {
                    name: 'cVersionSelectTool',
                    import: 'js.tools.landfire.cVersionSelectTool.cVersionSelectTool',
                    add: true,
                    width: 173,
                  },
                  {
                    name: 'cAddMapWindowTool',
                    import: 'js.tools.shared.cAddMapWindowTool.cAddMapWindowTool',
                    title: '',
                    add: true,
                    cssClass: '',
                    tooltip: 'New Map Window',
                  },
                  {
                    name: 'cAddWMSLayerTool',
                    import: 'js.tools.shared.cAddWMSLayerTool.cAddWMSLayerTool',
                    add: true,
                    tooltip: 'Add WMS Layer',
                    text: 'Add WMS Layer',
                  },
                  {
                    name: 'cRemoveWMSLayerTool',
                    import: 'js.tools.shared.cRemoveWMSLayerTool.cRemoveWMSLayerTool',
                    add: true,
                    tooltip: 'Remove WMS Layer',
                    text: 'Remove WMS Layer',
                  },
                  // {
                  //   name: 'cPopupButtonTool',
                  //   add: true,
                  //   import: 'js.tools.shrubland.cPopupButtonTool.cPopupButtonTool',
                  //   addFormatting: true,
                  //   popupTitle: 'Important Notice',
                  //   popupBody:
                  //     '<p>The LANDFIRE website and viewer will be offline Saturday, July 16, 2022, from 3 AM (CDT) to Sunday, July 17, 12 PM (CDT) due to scheduled maintenance. To prepare for this downtime, all LF downloads should be completed prior to the systems being taken offline. We apologize for any inconvenience this may cause.</p>',
                  //   popupHeight: 275,
                  //   text: 'Notice',
                  //   tooltip: 'Notice',
                  //   alwaysShow: true,
                  //   useOkButtons: false,
                  //   icon: 'fa-exclamation-triangle',
                  //   width: 120,
                  // },
                ],
              },
            },
            {
              add: true,
              title: 'Legend',
              name: 'cTocLegendTab',
              import: 'js.tools.shared.cTocLegendTab.cTocLegendTab',
              legend: [
                {
                  mx: 0.01,
                  my: 0.01,
                },
              ],
            },
            {
              add: true,
              title: 'Help',
              name: 'cHelpTab',
              import: 'js.tools.landfire.cHelpTab.cHelpTab',
              blocks: [
                {
                  name: 'cHelpContents',
                  import: 'js.tools.landfire.cHelpContents.cHelpContents',
                  add: true,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      block: 'center',
      blocks: [
        {
          block: 'relative',
          name: 'cMapWindow',
          import: 'js.tools.landfire.cMapWindow.cMapWindow',
          initialWinNum: 2,
          add: true,
          width: 580,
          height: 650,
          x: 410,
          y: 90,
          collapsible: true,
          toolbar: {
            position: 'top',
            add: true,
            overflowMenu: true,
            items: [
              {
                name: 'cZoomToRegionTool',
                title: '',
                add: true,
                import: 'js.tools.shared.cZoomToRegionTool.cZoomToRegionTool',
                cssClass: '',
                tooltip: 'Zoom to Extent',
              },
              {
                name: 'cPanTool',
                title: '',
                add: true,
                import: 'js.tools.shared.cPanTool.cPanTool',
                cssClass: '',
                tooltip: 'Pan Tool',
              },
              {
                name: 'cExtentDragBoxTool',
                title: '',
                add: true,
                import: 'js.tools.shared.cExtentDragBoxTool.cExtentDragBoxTool',
                cssClass: '',
                tooltip: 'Drag Zoom',
              },
              {
                name: 'cRevertExtentTool',
                title: '',
                add: true,
                import: 'js.tools.shared.cRevertExtentTool.cRevertExtentTool',
                cssClass: '',
                tooltip: 'Zoom to Previous',
              },
              {
                name: 'cIdentifyTool',
                title: '',
                add: true,
                import: 'js.tools.landfire.cIdentifyTool.cIdentifyTool',
                cssClass: '',
                tooltip: 'Identify Tool',
              },
              // {
              //   name: 'cElevationTool',
              //   title: '',
              //   add: true,
              //   import: 'js.tools.shared.cElevationTool.cElevationTool',
              //   cssClass: '',
              //   tooltip: 'Elevation Tool',
              // },
              {
                name: 'cDataDownloadBtn',
                add: true,
                import: 'js.tools.landfire.cDataDownloadBtn.cDataDownloadBtn',
                pressed: false,
                tooltip: 'Data Download Tool',
              },
              {
                name: 'cSpacer',
                import: 'js.tools.shared.cSpacer.cSpacer',
                add: true,
              },
              {
                name: 'cMapLegendTool',
                add: true,
                import: 'js.tools.shared.cMapLegendTool.cMapLegendTool',
                tooltip: 'Toggle map legend',
                pressed: false,
              },
            ],
          },
          blocks: [
            {
              name: 'cMapPanel',
              import: 'js.tools.shared.cMapPanel.cMapPanel',
              add: true,
              interactions: ['pan', 'zoom'],
              mouseCoordinates: {
                show: true,
                projection: 'EPSG:4326',
              },
              overviewMap: true,
              baseMapurl: 'https://osm-{1-4}.gs.mil/tiles/default/{z}/{x}/{y}.png',
              blocks: [
                {
                  name: 'cMapLegend',
                  block: 'relative',
                  import: 'js.tools.shared.cMapLegend.cMapLegend',
                  add: true,
                  legend: [
                    {
                      mx: 0.01,
                      my: 0.01,
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          block: 'relative',
          name: 'cAddWMSLayerForm',
          import: 'js.tools.shared.cAddWMSLayerForm.cAddWMSLayerForm',
          add: true,
          width: 350,
          height: 105,
          x: 390,
          y: 222,
          title: 'Add WMS Layers',
          addNewFolder: true,
        },
        {
          block: 'relative',
          name: 'cRemoveWMSLayerForm',
          import: 'js.tools.shared.cRemoveWMSLayerForm.cRemoveWMSLayerForm',
          add: true,
          width: 350,
          height: 105,
          x: 390,
          y: 222,
          title: 'Remove WMS Layers',
        },
      ],
    },
    {
      block: 'right',
      name: 'cTools',
      import: 'js.tools.shared.cTools.cTools',
      add: true,
      width: 250,
      height: 'auto',
      collapsible: true,
      collapsed: false,
      title: 'Tools',
      blocks: [
        {
          name: 'cSearch',
          add: true,
          import: 'js.tools.shared.cSearch.cSearch',
          width: 0,
          height: 0,
          zoomLevel: 10,
        },
        {
          name: 'cMeasure',
          add: true,
          collapsible: true,
          collapsed: true,
          import: 'js.tools.shared.cMeasure.cMeasure',
          color: '#000000',
        },
        {
          name: 'cBookmark',
          add: true,
          collapsible: true,
          collapsed: true,
          import: 'js.tools.shared.cBookmarkTool.cBookmarkTool',
          color: '#FF00DC',
          data: {
            childData: [
              {
                text: 'States',
                children: [
                  { text: 'Alabama', leaf: true, coords: [-88.7, 30.0, -84.5, 35.2] },
                  { text: 'Alaska', leaf: true, coords: [-168.6, 46.1, -129.1, 78.1] },
                  { text: 'Arizona', leaf: true, coords: [-115.0, 31.0, -108.7, 37.2] },
                  { text: 'Arkansas', leaf: true, coords: [-94.7, 32.7, -89.5, 36.7] },
                  { text: 'California', leaf: true, coords: [-124.6, 32.4, -114.0, 42.2] },
                  { text: 'Colorado', leaf: true, coords: [-109.2, 35.8, -101.9, 42.1] },
                  { text: 'Connecticut', leaf: true, coords: [-73.8, 40.4, -71.7, 42.6] },
                  { text: 'Delaware', leaf: true, coords: [-75.8, 38.4, -75.0, 39.9] },
                  { text: 'District of Columbia', leaf: true, coords: [-77.14, 38.77, -76.9, 39.0] },
                  { text: 'Florida', leaf: true, coords: [-87.8, 24.3, -79.7, 31.2] },
                  { text: 'Georgia', leaf: true, coords: [-85.7, 30.2, -80.6, 35.1] },
                  { text: 'Hawaii', leaf: true, coords: [-160.4, 18.1, -154.6, 23.0] },
                  { text: 'Idaho', leaf: true, coords: [-117.1, 41.9, -110.9, 49.1] },
                  { text: 'Illinois', leaf: true, coords: [-91.6, 36.9, -87.3, 42.6] },
                  { text: 'Indiana', leaf: true, coords: [-88.1, 37.7, -84.6, 41.8] },
                  { text: 'Iowa', leaf: true, coords: [-96.8, 39.0, -90.0, 44.8] },
                  { text: 'Kansas', leaf: true, coords: [-102.1, 35.1, -94.5, 41.8] },
                  { text: 'Kentucky', leaf: true, coords: [-89.6, 34.5, -81.9, 41.1] },
                  { text: 'Louisiana', leaf: true, coords: [-94.1, 28.9, -88.7, 33.1] },
                  { text: 'Maine', leaf: true, coords: [-71.2, 42.9, -66.7, 47.5] },
                  { text: 'Maryland', leaf: true, coords: [-79.5, 36.8, -75.0, 40.9] },
                  { text: 'Massachusetts', leaf: true, coords: [-73.6, 40.3, -69.8, 43.8] },
                  { text: 'Michigan', leaf: true, coords: [-90.6, 41.0, -82.2, 48.1] },
                  { text: 'Minnesota', leaf: true, coords: [-97.3, 42.9, -90.4, 49.9] },
                  { text: 'Mississippi', leaf: true, coords: [-91.8, 30.1, -88.1, 35.1] },
                  { text: 'Missouri', leaf: true, coords: [-95.9, 35.3, -88.9, 41.3] },
                  { text: 'Montana', leaf: true, coords: [-116.3, 41.2, -103.8, 52.3] },
                  { text: 'North Carolina', leaf: true, coords: [-84.5, 31.7, -75.3, 38.8] },
                  { text: 'North Dakota', leaf: true, coords: [-104.2, 44.1, -96.4, 50.8] },
                  { text: 'Nebraska', leaf: true, coords: [-104.3, 37.5, -95.1, 45.4] },
                  { text: 'Nevada', leaf: true, coords: [-120.1, 34.8, -113.8, 42.1] },
                  { text: 'New Hampshire', leaf: true, coords: [-72.6, 42.6, -70.6, 45.4] },
                  { text: 'New Jersey', leaf: true, coords: [-75.6, 38.8, -73.8, 41.4] },
                  { text: 'New Mexico', leaf: true, coords: [-109.1, 31.1, -102.7, 37.1] },
                  { text: 'New York', leaf: true, coords: [-80.0, 39.3, -71.7, 46.4] },
                  { text: 'Ohio', leaf: true, coords: [-85.6, 38.0, -79.7, 42.3] },
                  { text: 'Oklahoma', leaf: true, coords: [-103.1, 31.4, -94.3, 39.1] },
                  { text: 'Oregon', leaf: true, coords: [-124.7, 40.5, -116.3, 47.7] },
                  { text: 'Pennsylvania', leaf: true, coords: [-80.7, 38.3, -74.6, 43.6] },
                  { text: 'Rhode Island', leaf: true, coords: [-72.3, 41.2, -71.0, 42.1] },
                  { text: 'South Carolina', leaf: true, coords: [-83.5, 31.7, -78.4, 35.5] },
                  { text: 'South Dakota', leaf: true, coords: [-104.3, 40.8, -96.2, 47.7] },
                  { text: 'Tennessee', leaf: true, coords: [-90.4, 31.8, -81.6, 39.6] },
                  { text: 'Texas', leaf: true, coords: [-107.0, 25.7, -93.3, 36.6] },
                  { text: 'Utah', leaf: true, coords: [-114.1, 36.9, -109.0, 42.1] },
                  { text: 'Vermont', leaf: true, coords: [-73.5, 42.6, -71.3, 45.1] },
                  { text: 'Virginia', leaf: true, coords: [-83.7, 34.1, -75.0, 41.7] },
                  { text: 'Washington', leaf: true, coords: [-124.9, 43.8, -116.8, 50.7] },
                  { text: 'West Virginia', leaf: true, coords: [-82.9, 36.6, -77.6, 41.3] },
                  { text: 'Wisconsin', leaf: true, coords: [-93.1, 42.1, -87.2, 47.2] },
                  { text: 'Wyoming', leaf: true, coords: [-111.2, 39.7, -103.9, 46.2] },
                ],
                expanded: false,
              },
              {
                text: 'Region',
                expanded: false,
                children: [
                  { text: 'Alaska', leaf: true, coords: [-168.6, 46.1, -129.1, 78.1] },
                  { text: 'Atlantic North-East', leaf: true, coords: [-83.7, 34.0, -66.1, 49.4] },
                  { text: 'Atlantic South-East', leaf: true, coords: [-89.3, 24.1, -73.4, 37.9] },
                  { text: 'Central Plains', leaf: true, coords: [-108.5, 29.1, -85.5, 49.2] },
                  { text: 'Contiguous US', leaf: true, coords: [-126.5, 10.6, -65.4, 63.9] },
                  { text: 'East Coast', leaf: true, coords: [-89.9, 23.1, -58.9, 50.2] },
                  { text: 'Great Lakes', leaf: true, coords: [-93.2, 34.7, -74.8, 50.7] },
                  { text: 'Hawaii', leaf: true, coords: [-160.5, 17.6, -153.7, 23.4] },
                  { text: 'North-Central Plains', leaf: true, coords: [-105.0, 37.2, -88.9, 51.3] },
                  { text: 'Pacific North-West', leaf: true, coords: [-125, 39.75, -110, 50.75] },
                  { text: 'Pacific South-West', leaf: true, coords: [-124.7, 27.9, -107.3, 43.1] },
                  { text: 'South-Central Plains', leaf: true, coords: [-105.3, 27.0, -90.9, 39.5] },
                  { text: 'West Coast', leaf: true, coords: [-129.0, 30.0, -106.0, 50.0] },
                ],
              },
              {
                text: 'Locale',
                expanded: false,
                children: [
                  { text: 'Albuquerque, NM', leaf: true, coords: [-106.897, 34.849, -106.388, 35.275] },
                  { text: 'Allentown-Bethlehem, PA', leaf: true, coords: [-75.23, 40.62, -75.1, 40.81] },
                  { text: 'Amarillo, TX', leaf: true, coords: [-102.02, 34.97, -101.58, 35.4] },
                  { text: 'Anchorage, AK', leaf: true, coords: [-150.11, 60.97, -149.38, 61.4] },
                  { text: 'Atlanta, GA', leaf: true, coords: [-84.79, 33.32, -83.81, 34.17] },
                  { text: 'Austin, TX', leaf: true, coords: [-97.9, 30.1, -97.57, 30.52] },
                  { text: 'Baltimore-Annapolis, MD', leaf: true, coords: [-77.1, 38.79, -76.14, 39.67] },
                  { text: 'Baton-Rouge, LA', leaf: true, coords: [-91.4, 30.15, -90.8, 30.85] },
                  { text: 'Birmingham, AL', leaf: true, coords: [-87.15, 33.21, -86.58, 33.66] },
                  { text: 'Bismarck, ND', leaf: true, coords: [-100.99, 46.72, -100.64, 46.9] },
                  { text: 'Boise, ID', leaf: true, coords: [-116.53, 43.35, -116.09, 43.77] },
                  { text: 'Boston MA', leaf: true, coords: [-71.8, 41.85, -70.5, 42.93] },
                  { text: 'Carson City, NV', leaf: true, coords: [-119.89, 38.99, -119.61, 39.26] },
                  { text: 'Charlotte, NC', leaf: true, coords: [-81.1, 34.97, -80.5, 35.54] },
                  { text: 'Chattanooga,TN', leaf: true, coords: [-85.55, 34.85, -85.11, 35.28] },
                  { text: 'Chicago, IL', leaf: true, coords: [-88.57, 41.18, -87.04, 42.81] },
                  { text: 'Cincinnati, OH', leaf: true, coords: [-84.95, 38.79, -84.02, 39.6] },
                  { text: 'Cleveland-Akron, OH', leaf: true, coords: [-82.19, 40.83, -80.92, 41.89] },
                  { text: 'Colorado Springs, CO', leaf: true, coords: [-105.05, 38.65, -104.52, 39.16] },
                  { text: 'Columbus OH (-83.34,39.62,-82.47,40.36)', leaf: true, coords: [-83.34, 39.62, -82.47, 40.36] },
                  { text: 'Dallas-Ft.Worth, TX', leaf: true, coords: [-97.65, 32.36, -96.29, 33.3] },
                  { text: 'Des Moines, IA', leaf: true, coords: [-93.9, 41.45, -93.2, 41.89] },
                  { text: 'Denver, CO', leaf: true, coords: [-105.67, 39.09, -104.17, 40.32] },
                  { text: 'Detroit, MI', leaf: true, coords: [-83.66, 42.08, -82.57, 42.78] },
                  { text: 'El Paso, TX', leaf: true, coords: [-106.65, 31.6, -106.23, 32.03] },
                  { text: 'Fresno, CA', leaf: true, coords: [-120.03, 36.59, -119.58, 37.03] },
                  { text: 'Ft.Wayne, IN', leaf: true, coords: [-85.39, 40.84, -84.83, 41.28] },
                  { text: 'Greensboro - Winston salem, NC', leaf: true, coords: [-80.51, 35.73, -79.53, 36.27] },
                  { text: 'Harrisburg, PA', leaf: true, coords: [-77.14, 39.97, -76.53, 40.42] },
                  { text: 'Helena, MT', leaf: true, coords: [-112.27, 46.48, -111.87, 46.77] },
                  { text: 'Houston, TX', leaf: true, coords: [-95.92, 29.4, -94.83, 30.29] },
                  { text: 'Huntsville, AL', leaf: true, coords: [-86.87, 34.49, -86.36, 34.89] },
                  { text: 'Jackson, MS', leaf: true, coords: [-90.436, 32.098, -89.933, 32.52] },
                  { text: 'Jacksonville, FL', leaf: true, coords: [-81.95, 29.76, -81.26, 30.73] },
                  { text: 'Kansas City, MO', leaf: true, coords: [-95.07, 38.72, -94.59, 39.07] },
                  { text: 'Knoxville, TN', leaf: true, coords: [-84.28, 35.71, -83.7, 36.16] },
                  { text: 'Las Vegas, NV', leaf: true, coords: [-115.46, 35.88, -114.03, 36.86] },
                  { text: 'Lexington, KY', leaf: true, coords: [-84.65, 37.85, -84.35, 38.15] },
                  { text: 'Lincoln, NE', leaf: true, coords: [-96.91, 40.6, -96.45, 41.03] },
                  { text: 'Los Angeles - Glendale, CA', leaf: true, coords: [-118.93, 33.44, -117.45, 34.42] },
                  { text: 'Louisville, KY', leaf: true, coords: [-86.02, 37.97, -85.33, 38.52] },
                  { text: 'Lubbock, TX', leaf: true, coords: [-102.15, 33.35, -101.71, 33.78] },
                  { text: 'Memphis, TN', leaf: true, coords: [-90.29, 34.85, -89.592, 35.4] },
                  { text: 'Miami-Ft. Lauderdale, FL', leaf: true, coords: [-80.59, 25.37, -80.02, 27.05] },
                  { text: 'Minneapolis-St. Paul, MN', leaf: true, coords: [-93.87, 44.51, -92.72, 45.48] },
                  { text: 'Mobile, AL', leaf: true, coords: [-88.4, 30.47, -87.98, 30.9] },
                  { text: 'Modesto, CA', leaf: true, coords: [-121.15, 37.46, -120.71, 37.9] },
                  { text: 'Montgomery, AL', leaf: true, coords: [-86.49, 32.23, -86.11, 32.52] },
                  { text: 'Nashville, TN', leaf: true, coords: [-87.08, 35.93, -86.48, 36.43] },
                  { text: 'New Orleans, LA', leaf: true, coords: [-90.36, 29.73, -89.72, 30.1] },
                  { text: 'New York-Newark, NY', leaf: true, coords: [-75.03, 39.45, -73.81, 41.26] },
                  { text: 'Oklahoma City, OK', leaf: true, coords: [-97.8, 35.2, -97.17, 35.8] },
                  { text: 'Orlando, FL', leaf: true, coords: [-81.698, 28.366, -81.05, 28.895] },
                  { text: 'Philadelphia, PA', leaf: true, coords: [-75.95, 39.46, -74.47, 40.48] },
                  { text: 'Phoenix, AZ', leaf: true, coords: [-113.4, 32.81, -111.37, 34.14] },
                  { text: 'Portland, OR', leaf: true, coords: [-123.13, 45.22, -122.33, 45.77] },
                  { text: 'Providence, RI', leaf: true, coords: [-71.65, 41.6, -71.2, 42.03] },
                  { text: 'Raleigh-Durham, NC', leaf: true, coords: [-79.16, 35.58, -78.45, 36.15] },
                  { text: 'Reno, NV', leaf: true, coords: [-120.02, 39.18, -119.62, 39.75] },
                  { text: 'Riverside-San Bernardino, CA', leaf: true, coords: [-117.7, 33.65, -116.76, 34.33] },
                  { text: 'Sacramento, CA', leaf: true, coords: [-121.89, 37.73, -120.97, 39.01] },
                  { text: 'Salt Lake City-Ogden, UT', leaf: true, coords: [-112.14, 40.36, -111.73, 41.38] },
                  { text: 'San Diego, CA', leaf: true, coords: [-117.7, 32.44, -116.72, 33.55] },
                  { text: 'San Francisco-Oakland, CA', leaf: true, coords: [-122.63, 37.12, -121.59, 38.27] },
                  { text: 'San Juan, PR', leaf: true, coords: [-66.57, 17.98, -65.57, 18.51] },
                  { text: 'Savannah, GA', leaf: true, coords: [-81.4, 31.69, -80.8, 32.27] },
                  { text: 'Seattle, WA', leaf: true, coords: [-122.66, 46.94, -121.95, 48.04] },
                  { text: 'Shreveport, LA', leaf: true, coords: [-93.89, 32.22, -93.46, 32.65] },
                  { text: 'Springfield, MA', leaf: true, coords: [-72.92, 41.93, -72.16, 42.44] },
                  { text: 'St Louis, MO', leaf: true, coords: [-90.8, 38.34, -90.09, 38.92] },
                  { text: 'Stockton, CA', leaf: true, coords: [-121.52, 37.86, -121.08, 38.15] },
                  { text: 'Tampa-St.Petersburg, FL', leaf: true, coords: [-82.89, 27.46, -82.07, 28.29] },
                  { text: 'Topeka, KS', leaf: true, coords: [-96.06, 38.83, -95.44, 39.25] },
                  { text: 'Trenton, NJ', leaf: true, coords: [-74.97, 40.14, -74.58, 40.4] },
                  { text: 'Tucson, AZ', leaf: true, coords: [-111.15, 31.96, -110.58, 32.54] },
                  { text: 'Washington, DC', leaf: true, coords: [-77.7, 38.6, -76.7, 39.2] },
                  { text: 'Wichita, KS', leaf: true, coords: [-97.52, 37.37, -97.11, 37.9] },
                  { text: 'Worcester, MA', leaf: true, coords: [-72.18, 41.96, -71.53, 42.58] },
                ],
              },
              // {
              //   text: 'Custom Bookmarks',
              //   expanded: false,
              //   children: [],
              // },
            ],
          },
        },
        {
          name: 'cFeatureInfoPanel',
          import: 'js.tools.landfire.cFeatureInfoPanel.cFeatureInfoPanel',
          add: true,
          title: 'Identify Tool',
          height: 350,
          width: '100%',
          collapsible: true,
          collapsed: true,
          cssClass: '',
          ignoreDisplayNames: ['R', 'G', 'B', 'r', 'g', 'b', 'CLASSNAMES', 'legenField'],
          customRows: [
            // You can have as many parts as you want in a row, they will be combined in the order they appear.
            // use {Feature Property} to use those values from the featureInfo.
            // Use {{Feature Property}} to use that value as a reference. For example, LANDFIRE uses the 'legenField' to determine which featureInfo property to use as the value.
            // If 'legenField' has the value of 'CLASSNAMES', then the value for CLASSNAMES will be used.
            // HTML is not required, maybe you just want to combine multiple properties together
            ['<b>Color:</b> ', `<img src='${legendColor}' style='background-color:rgb({R},{G},{B})'></img>`, ' ', '{{legenField}}'],
          ],
        },
        // {
        //   name: 'cElevationPanel',
        //   import: 'js.tools.shared.cElevationPanel.cElevationPanel',
        //   add: true,
        //   title: 'Elevation Info',
        //   height: 130,
        //   collapsible: true,
        //   collapsed: true,
        //   cssClass: '',
        //   defaultLock: true,
        // },
        {
          name: 'cDataDownload',
          add: true,
          addQueueLocation: './downloads/addQueue.php',
          collapsible: true,
          collapsed: true,
          import: 'js.tools.landfire.cDataDownload.cDataDownload',
          shapeFile: 'landfire:viewer_layer_extent',
          workspace: 'landfire',
          geoserver: 'https://dmsdata.cr.usgs.gov/geoserver/wfs?',
          convertToMiles: true,
          maxArea: 500000,
          noBoxText:
            'A box has not been drawn yet. <br><br> To draw one, please select the <br>Data Download tool <i class="fa fa-arrow-circle-o-down mrlc-fb"></i><br>in the map window toolbar. <br><br> <a href="https://landfire.gov/insular_areas.php" target="_blank">Insular Area Download Page</a>',
          redirectButton: false,
          selectionLimit: 1,
          redirectText: `<div class="x-toolbar-text x-toolbar-text-default" id="redirectDownloadText"><b>NOTICE:</b><br> Your Area of Interest (AOI) <br/> is larger than the maximum area <br/> allowed to download in this viewer. <br>
          (193,000mi<sup>2</sup> or 500,000km<sup>2</sup>)

          <br><br>Please draw a smaller AOI or click <br><a href="https://landfire.gov/version_download.php" target="_blank">here</a> to access complete datasets.</div>`,
        },
        {
          name: 'cSpatialLocking',
          import: 'js.tools.shared.cSpatialLocking.cSpatialLocking',
          add: true,
          title: 'Spatial Locking Tool',
          height: 250,
          collapsible: true,
          cssClass: '',
          defaultLock: true,
        },
        {
          name: 'cArrangeWindows',
          import: 'js.tools.shared.cArrangeWindows.cArrangeWindows',
          add: true,
          title: 'Arrange Windows Tool',
          height: 250,
          collapsible: true,
          cssClass: '',
        },
      ],
    },
  ],
};
